### ISSUE TITLE
Crash Referencing terraform_remote_state

### ISSUE THREAD

**Issue by moorichardmoo** [hashicorp/terraform-plugin-sdk#100]
Hi

Terraform versions:
Terraform v0.11.3
+ provider.aws v1.10.0
+ provider.template v1.0.0

Crash log located here: https://gist.githubusercontent.com/moorichardmoo/5fb92530c7ec33de93163ce8d8517130/raw/9bc64e80a41d5d4d9c7af8d49e53bea00fc4fcc5/gistfile1.txt

Steps to reproduce:
terraform plan -var-file="terraform.tfvars" -var-file="secret.tfvars"

Expected Behavior:
Terraform plan created

Actual Behavior:
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Steps to Reproduce:
terraform init --backend-config="backend.conf" -reconfigure -upgrade
terraform plan -var-file="terraform.tfvars" -var-file="secret.tfvars"

I've tried a full reboot, upgrading, removing recently added parts of my .tf files, and have tried digging through the crash log but I can't see anything that might help. If you have any ideas I'd be grateful to hear them. 

Thanks

Richard

**Comment by radeksimko** [comment]
This is not reproducible in v0.12.17 + provider.aws v2.41.0 anymore, so I'm going to close it.

Instead Terraform will error out as expected:

```
Error: Incorrect attribute value type

  on main.tf line 14, in data "aws_lb" "example":
  14:   arn = "${data.terraform_remote_state.example.outputs.list}"

Inappropriate value for attribute "arn": string required.
```

(this is after modifying the attached repro case for 0.12 syntax & recent changes)
