### ISSUE TITLE
Diffs: going from zero value to nil

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform-plugin-sdk#102]
The current diff logic does not currently account for a transition from a zero value to a nil state. This can be seen [here](https://github.com/hashicorp/terraform/blob/e493407e7e8d1181165520f9d14ddc591e509477/helper/schema/schema.go#L1164), in that any nils returned during the diff process (in the config layer, specifically) do not get treated as nils, but converted to that type's zero value.

This creates problems like diffs being completely ignored for primitive transitions including, but not limited to:

```
false => nil
0 => nil
"" => nil
```

The first two are the most significant, as there has been plenty of precedent that these states are necessary in Terraform where a nil state has meaning, possibly instructing an API to disable a feature or configure it to inherit settings from a parent subsystem, and is why `GetOkExists` was exposed - which currently has its own issues, see hashicorp/terraform#17557. These two issues combined basically mean that a nil state only has meaning in a resource if the intention is to never move away from the nil state, which is a one-way trip that can't be reverted without state hacking.

As a note, both of these issues will be addressed in future releases (namely with the advent of HCL2, as mentioned in hashicorp/terraform#17557). This is mainly just a note to ensure there is a TODO to make sure the diff shortcomings are addressed.

**Comment by jakubpech** [comment]
Hi, 
any news regarding this issue? From the other related issues I found, I understand that the proper implementation of nils requires backward-incompatible changes in SDK. Are there any plans to release V2 SDK, which will use protocol 5 only?

We came to the point in our provider, where we can hardly move forward without the nils and we need to implement some exotic workarounds for the deeply nested data structures. The question is how long we'll need to support these workarounds and how dirty they can be. Do you think there is a chance to have it released in the next 6 months?

Our provider was written in a 0.12+ era so we don't have any historical dependencies. Is there some feature branch of SDK, where we can use protocol 5 at our own risk? All we need right now is to prevent that SDK will change all our nils to default values.

**Comment by paultyng** [comment]
v2 (currently in dev on the `version2` branch) will hopefully be released in the next few months. It will not contain exposure of the underlying type system yet, but that is one of the early goals to surface it more directly. And you are correct, it is protocol 5 only, but the goal with it is still largely to remain backwards compatible for existing provider codebases. 

The best tracking issue is probably #261
