### ISSUE TITLE
TF_REATTACH_PROVIDERS is not being picked up from terraform

### ISSUE THREAD

**Issue by jackdelahunt** [hashicorp/terraform-plugin-sdk#1049]
### SDK version
2.21.0

### Relevant provider source code
```go
var debug bool

flag.BoolVar(&debug, "debug", false, "set to true to run the provider with support for debuging")
flag.Parse()

plugin.Serve(&plugin.ServeOpts{
ProviderFunc: rhoas.Provider,
Debug:        debug,
})
```

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    rhoas = {
      source  = "registry.terraform.io/redhat-developer/rhoas"
      version = "0.1.0"
    }
  }
}

provider "rhoas" {
    offline_token = "..."
}

resource "rhoas_kafka" "instance" {
    kafka {
        name = "instance"
    }
}
```

### Expected Behavior
The environment variable from the provider in debug mode should be picked up by terraform core and break points should be hit when running `terraform apply`.

### Actual Behavior
The environment variable from the provider in debug mode is printed and the provider can be debugged on startup like defining its resources etc. as that is in its own process but any functions for creating resources which is called from the terraform core are not being called.

### Steps to Reproduce
1. export TF_REATTACH_PROVIDERS={ ... }
2. `terraform init`
3. `terraform apply`

**Comment by bflad** [comment]
Hi @jackdelahunt 👋 Thank you for raising this and sorry you ran into trouble here.

Are you setting the [`plugin.ServeOpts` type `ProviderAddr` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/plugin#ServeOpts.ProviderAddr) to `registry.terraform.io/redhat-developer/rhoas`? Setting that should update the provider address key within the `TF_REATTACH_PROVIDERS` environment variable as Terraform requires the full provider address to reattach properly to providers running in this mode.

**Comment by jackdelahunt** [comment]
Hey @bflad you were correct and this did solve the issue I was having thanks! 😄
