### ISSUE TITLE
schema.TypeInt Panics Instead of Returning Type Errors

### ISSUE THREAD

**Issue by gintau** [hashicorp/terraform-plugin-sdk#107]
### Terraform Version

```
0.11.7
plugin.terraform-provider-aws_v1.20.0_x4
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

```
* (service name).aws_security_group_rule.(resource_name): aws_security_group_rule.(resource_name): connection is shut down
* (service name).aws_iam_role.(resource_name): 1 error(s) occurred:

* (service name).aws_iam_role.api_role: aws_iam_role.(resource_name): unexpected EOF
* (service name).aws_security_group_rule.(resource_name): 1 error(s) occurred:

panic: Error reading level state: strconv.ParseInt: parsing "74D93920-ED26-11E3-AC10-0800200C9A66": invalid syntax
2018-05-24T15:32:08.721-0700 [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: 
2018-05-24T15:32:08.721-0700 [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: goroutine 3093 [running]:
2018-05-24T15:32:08.721-0700 [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc4201956c0, 0xc42077b080, 0x1, 0x1, 0xc420bed208, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-05-24T15:32:08.721-0700 [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:508 +0x4ac
```

### Expected Behavior

Refresh state successfully.

### Actual Behavior

Process panic out.

### Steps to Reproduce

1. update terraform from 0.11.1 to 0.11.7, new aws provider is downloaded by automatically.
2. terraform init, config s3 as backend
3. terraform state mv 5 resources, no resource is recreated, only renaming them. 
4. terraform refresh
5. starts getting panic above, tens of resources got error **unexpected EOF** or **connection is shut down**

### Additional Context

During init state already exists, backed config happens every time during our build process. No real config change in my case.

**Comment by radeksimko** [comment]
Hi folks,
sorry for the delay in responding to this report, I was unable to reproduce this crash in 0.12.

0.12 introduced much stronger config validation which runs very early on and so it's highly unlikely (if not impossible) for the provider/SDK to receive such invalid config which would cause such crash.

@bflad The config you provided is parsed as expected in 0.12 and Terraform returns human-readable error:

```
Error: retention_in_days: must be a whole number, got 1.5

  on main.tf line 6, in resource "aws_cloudwatch_log_group" "test":
   6: resource "aws_cloudwatch_log_group" "test" {
```
It doesn't point to the right LOC, but that's already being discussed in #146 and is unrelated to this issue.

With that I'm going to close this issue, but feel free to raise a separate one with a fresh crash log and config if you encounter this in `>=0.12.0`.
