### ISSUE TITLE
Proposal: Add variants of `validation.All` and `validation.Any` that accept `SchemaValidateDiagFunc`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-plugin-sdk#1071]
### Use-cases

There is currently no method to combine multiple `SchemaValidateDiagFunc`s without converting them to `SchemaValidateFunc`s and using `validation.All` or `validation.Any`.

### Proposal

Create variants of `validation.All` and `validation.Any`, e.g. `validation.AllDiag` and `validation.AnyDiag` that accept `SchemaValidateDiagFunc`s instead of `SchemaValidateFunc`s .

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-plugin-sdk/issues/780.
