### ISSUE TITLE
acctests: `ImportStateVerify` fails when config contains data sources with Terraform v1.3

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-plugin-sdk#1073]
Starting with Terraform v1.3, the `terraform import` command populates an empty state file with the imported resource and any data sources. Previously, only the target resource was written to the state file.

This causes acceptance test steps with `ImportStateVerify` to fail if the configuration contains any data sources.

In `testStepNewImportState` (at https://github.com/hashicorp/terraform-plugin-sdk/blob/6c09938937b7740074273ede0767c190fc1ed68b/helper/resource/testing_new_import_state.go#L17), data sources in the original state are skipped. Data sources from the imported state should be skipped as well.

**Comment by tobio** [comment]
Possible duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/1066

**Comment by gdavison** [comment]
Duplicate of #1066
