### ISSUE TITLE
How do I fix -/datadog / hashicorp/datadog -> Datadog/datadog conflict?

### ISSUE THREAD

**Issue by st-h** [hashicorp/terraform-plugin-sdk#1081]
I am dealing with some quite dated terraform code, that has been applied somewhen in the past, but then commented out for a long time. Right now, I just want to make terraform delete the resources that have been provisioned in the past.

Terraform version used is 0.13.7

The code seems to date back to terraform version 0.12.x

The main.tf file just consists of the Datadog provider and a module, that now shall be removed:

```
terraform {
  backend "azurerm" {

  }
}

provider "datadog" {
  version  = "3.16.0"
  validate = true
}

#module "datadog" {
#  source          = "../../../datadog"
#}
```

When I run this, I receive an error that the required provider can not be found:

```
2022-10-18T12:35:13.3613990Z Initializing provider plugins...
2022-10-18T12:35:13.4397090Z - Finding hashicorp/datadog versions matching "3.16.0"...
2022-10-18T12:35:13.4397884Z - Finding latest version of -/datadog...
2022-10-18T12:35:13.6582834Z - Installing -/datadog v3.16.0...
2022-10-18T12:35:14.1630095Z - Installed -/datadog v3.16.0 (signed by HashiCorp)
2022-10-18T12:35:14.3483111Z 
2022-10-18T12:35:14.3483957Z Warning: Additional provider information from registry
2022-10-18T12:35:14.3484156Z 
2022-10-18T12:35:14.3485118Z The remote registry returned warnings for registry.terraform.io/-/datadog:
2022-10-18T12:35:14.3486471Z - For users on Terraform 0.13 or greater, this provider has moved to
2022-10-18T12:35:14.3486951Z DataDog/datadog. Please update your source in required_providers.
2022-10-18T12:35:14.3487181Z 
2022-10-18T12:35:14.3492558Z 
2022-10-18T12:35:14.3493318Z Error: Failed to install providers
2022-10-18T12:35:14.3493550Z 
2022-10-18T12:35:14.3493871Z Could not find required providers, but found possible alternatives:
2022-10-18T12:35:14.3494099Z 
2022-10-18T12:35:14.3494743Z   hashicorp/datadog -> datadog/datadog
2022-10-18T12:35:14.3494902Z 
2022-10-18T12:35:14.3495245Z If these suggestions look correct, upgrade your configuration with the
2022-10-18T12:35:14.3495588Z following command:
2022-10-18T12:35:14.3495869Z     terraform 0.13upgrade .
2022-10-18T12:35:14.3496000Z 
2022-10-18T12:35:14.3527575Z ERROR Terraform init failed.
```

If I try to update the provider source to "DataDog/datadog" by adding a `versions.tf` file (which is what the 0.13upgrade command does), I get an error about the missing datadog provider when processing the resources in the module (that are no longer present)...

versions.tf
```
terraform {
  required_providers {
    datadog = {
      source = "datadog/datadog"
    }
  }
  required_version = ">= 0.13"
}
```

```
Error: Provider configuration not present

To work with module.datadog.datadog_monitor.ErrorRatePrivateProbe its original
provider configuration at provider["registry.terraform.io/-/datadog"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.datadog.datadog_monitor.ErrorRatePrivateProbe, after which you can
remove the provider configuration again.
```

I am quite confused by this behaviour, as with the old provider config, terraform seems to be able to install the terraform provider, but then complains that it does not find the required providers. If I then update the provider to the suggestion it then seems to require the old provider, that I just upgraded. Any ideas how to fix this issue? I have tried all workarounds I could find in related issues, but I am still seeing the same errors over and over again.

**Comment by bflad** [comment]
Hi @st-h 👋 Thank you for raising this and sorry you are running into trouble here.

Please note that this issue tracker is for the terraform-plugin-sdk Go module, which is what underlies many provider codebases, however it has no particular influence over the behaviors being seen here which come from [Terraform core](https://github.com/hashicorp/terraform). The maintainers here cannot provide the most authoritative answer to this issue, however I will give it a try.

During the Terraform 0.12 and 0.13 timeframe, provider "sources" were being added to the configuration language to enable usage of external provider registries, such as the [public Terraform Registry](https://registry.terraform.io). Prior to then, providers were all sourced from a common location with a default hostname (releases.hashicorp.com) and no namespace information. To introduce a full provider source address (hostname/namespace/name), the logic within Terraform was updated to use the public Terraform Registry by default and fill in the unknown namespace information with a `-` value. These provider addresses are stored with resource state so Terraform can track which provider is associated. It appears that your state may have some of these `-` namespace provider sources.

I believe your first option may be to follow the [Terraform 0.13 upgrade guide section on this topic](https://www.terraform.io/language/v1.1.x/upgrade-guides/0-13#explicit-provider-source-locations) and error messaging there to re-add missing configurations until the first apply can succeed.

Another thing you may be able to do in this situation would be to update those resource states to point to the expected provider source via the [`terraform state replace-providers command](https://www.terraform.io/cli/commands/state/replace-provider). For example something like:

```shell
terraform state replace-provider -/datadog DataDog/datadog
```

If you're looking for additional help beyond these, I would suggest reaching out to the [HashiCorp Discuss category for Terraform](https://discuss.hashicorp.com/c/terraform-core/27) where there are many more practitioners who may have knowledge about this particular (painful) upgrade process with Terraform 0.13.

**Comment by st-h** [comment]
@bflad Thank you very much for the kind and very helpful reply. Sorry about posting this in the wrong place. I have been able to fix the issue by using the replace-provider command. In case anyone reads this having a similar issue, I needed to modify the command a bit to work with bash in a CI environment:

```
terraform state replace-provider -auto-approve -- -/datadog DataDog/datadog
```
