### ISSUE TITLE
Cache API responses for use in multiple resources

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#11]
Formally (incorrectly) referred to as "batch API calls", the idea is for large number of resources, individual API calls can consume rate limits and cause throttling at best, incomplete state / plan at worst. 

If a provider supports it, need a way to call "describe all" and cache the results, and all resources of that kind can use those results until a cache-bust event occurs.

**Comment by paultyng** [comment]
Going to merge this with #7 as it's the same problem but different approaches, we should just look at it holistically.
