### ISSUE TITLE
Tests fail in GoogleCloudPlatform / magic-modules with sdk release 2.24.0

### ISSUE THREAD

**Issue by zli82016** [hashicorp/terraform-plugin-sdk#1104]
### SDK version

```
2.24.0
```

### Relevant provider source code

```go
https://github.com/GoogleCloudPlatform/magic-modules

```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior
The following tests should pass.

TestAccContainerNodePool_basicWithClusterId|TestAccContainerNodePool_autoscaling|TestAccContainerNodePool_totalSize|TestAccContainerNodePool_regionalAutoscaling|TestAccContainerNodePool_basic|TestAccContainerCluster_withResourceUsageExportConfig|TestAccComputeVpnTunnel_vpnTunnelBetaExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccProviderBasePath_setInvalidBasePath|TestAccProviderBasePath_setBasePath|TestAccSecurityScannerScanConfig_scanConfigBasicExample

### Actual Behavior
The above tests fail.

### References
- https://github.com/GoogleCloudPlatform/magic-modules/pull/6818

**Comment by zli82016** [comment]
It looks like the commit in sdk (https://github.com/hashicorp/terraform-plugin-sdk/commit/ef65fded9a54add675113b2567d32ac3abad0c5f#diff-3894fabafd3f4b1861dd167c6194c6d79e5824d2bec30d37b257d80a824255c2R19 ) causes the tests fail in GoogleCloudPlatform / magic-modules.

**Comment by bflad** [comment]
Hi @zli82016 👋 Thank you for raising this and sorry your provider is running into testing issues.

Two questions for you:

- Can you please post the failed test output and relevant test code? The maintainers here cannot access the GCP acceptance testing links for the failed tests to triage this issue.
- Does upgrading to 2.24.1 fix the issue(s)? If it relates to test configuration handling, this was a bug fix from that release:

> helper/resource: Prevented provider configuration already given error when TestStep type Config field already contained provider configuration block (https://github.com/hashicorp/terraform-plugin-sdk/issues/1092)

Thank you so much.

**Comment by zli82016** [comment]
Test code: https://gist.github.com/zli82016/80a171c9403f6a8a317d9a918e7c31fe
Test output: https://gist.github.com/zli82016/54bd8d0adbbb1790995357fe7cb00d46

**Comment by zli82016** [comment]
I checked the fix in 2.24.1. I do find the place to add the flag skipProviderBlock for our cases.

**Comment by zli82016** [comment]
V2.24.1 does not fix the tests.

**Comment by bflad** [comment]
If you have trace logging enabled, it should output the full Terraform configuration being applied with a message `Setting Terraform configuration`.

Looking at the test code itself, it is using the deprecated `TestCase` type `Providers` field (`Providers:    testAccProvidersOiCS,`). There is some legacy logic in the testing code that implicitly adds provider configuration blocks, but only when using that field. We can try to determine if that is safe to skip in this case. Are you able to try switching the `TestCase` to using the `ProviderFactories` or `ProtoV5ProviderFactories` field instead to see if that resolves this issue for you?

**Comment by zli82016** [comment]
Thanks, @bflad. I can see the Terraform configuration with enabled trace logging. 

I switched to ProviderFactories and the test runs successfully. 

It needs some work to switch to ProviderFactories for our system and I am not sure if we have the plan to do that.

Can you try to check if it is safe to skip the provider configuration block in this case? Thank

**Comment by zli82016** [comment]
Hello, @bflad , sorry to check again. Do you think is it safe to skip the provider configuration block in this case? Thanks.

**Comment by bflad** [comment]
It looks like this was [resolved last year](https://github.com/GoogleCloudPlatform/magic-modules/pull/6818), but if not, please feel free to submit a bug report with a full reproduction case.
