### ISSUE TITLE
Migrate Non-SDK Specific Best Practices Documentation

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#1151]
### Description

Now that [terraform-plugin-framework is generally available](https://www.hashicorp.com/blog/terraform-plugin-framework-is-now-generally-available) and [terraform-plugin-testing is released](https://discuss.hashicorp.com/t/announcing-the-terraform-plugin-testing-module/49914), we can expect that over time the traffic to the [terraform-plugin-sdk website documentation](https://developer.hashicorp.com/terraform/plugin/sdkv2) (Terraform > Plugin Development > SDKv2) will begin to lessen. Inside the SDK website documentation is a ["Best Practices" section](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices) which captures helpful information and consistency tips from the ecosystem over time. These pages are briefly described below.

| Page | Description |
|---|---|
| [Overview](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices) | Index page for others. |
| [Naming](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/naming) | Generic Resource, Data Source, and Attribute naming recommendations. |
| [Depending on Providers](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/depending-on-providers) | Interfacing to Terraform Providers is expected to be Terraform CLI or gRPC, not Go code itself. |
| [Deprecations, Removals, and Renames](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations) | Semi-SDK specific information for how to handle breaking change situations in providers. |
| [Detecting Drift](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/detecting-drift) | Capture all state during refresh, update state after modification (unfortunately risky half-pattern), and SDK-specific error checking/helpers. |
| [Handling Sensitive Data](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/sensitive-state) | Use `Sensitive` attribute behavior, don't encrypt attribute values manually. |
| [Testing Patterns](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/testing) | Generic information about the provider testing framework, examples of common use case tests. |
| [Versioning and Changelog](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/versioning) | Generic provider versioning and consistent changelog formatting. |
| [Writing Non-Go Providers](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/other-languages) | Policy and reasoning around HashiCorp only supporting the Go language at this time. |

There is quite a bit of this information which is not specific to terraform-plugin-sdk, so it might make sense to migrate some of the content to other repositories, which hold other sections of the website content.

### Proposal

In general, the steps for each page will be:

* In the target repository, copy/migrate the new mdx content and ensure its deployed in production (either by product release or special `release/website` Git tag updates)
* In terraform-website, introduce a redirect for the old URL path to the new URL page.
* In terraform-plugin-sdk, update the side navigation to href the new page.
* In terraform-plugin-sdk, remove the old mdx content

The proposed migration strategy for each page is:

| Page | Target Repository | Target Navigation |
|---|---|---|
| [Overview](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices) | Each repository as necessary | e.g. Plugin Development > Best Practices > Overview |
| [Naming](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/naming) | terraform-docs-common | Plugin Development > Best Practices > Naming |
| [Depending on Providers](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/depending-on-providers) | terraform-docs-common | Plugin Development > Best Practices > Interacting with Providers |
| (SPLIT) [Deprecations, Removals, and Renames](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations) | terraform-plugin-sdk | SDKv2 > Deprecations, Removals, and Renames |
| (SPLIT) [Deprecations, Removals, and Renames](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations) | terraform-plugin-framework | Framework > Deprecations, Removals, and Renames |
| [Detecting Drift](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/detecting-drift) | TBD (terraform-plugin-framework?) | TBD (may already be covered by Framework > Resources > Read?) |
| [Handling Sensitive Data](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/sensitive-state) | terraform-docs-common | Plugin Development > Best Practices > Handling Sensitive Data |
| [Testing Patterns](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/testing) | terraform-plugin-testing | Testing > Acceptance Testing > Patterns |
| [Versioning and Changelog](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/versioning) | terraform-docs-common | Plugin Development > Best Practices > Versioning and Changelog |
| [Writing Non-Go Providers](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/other-languages) | terraform-docs-common | Plugin Development > Best Practices > Provider Code Language |

### References

- https://github.com/hashicorp/terraform-plugin-sdk/pull/1150

**Comment by austinvalle** [comment]
All PRs are open and ready for review, order of releases should be:

1. `terraform-docs-common` should merge/deploy first (only adds new pages/navigation)
2. `terraform-website` should merge/deploy next (redirect dependent on new pages added in step 1)
3. `terraform-plugin-framework` should be next (new pages, relies on links from pages added in step 1)
4. `terraform-plugin-sdk` last (deletes duplicate pages + removes pages in sidebar)

**Comment by austinvalle** [comment]
- `terraform-docs-common` has been deployed 🚀 
- `terraform-website` redirects are in place to point to new best practice pages.
- `terraform-plugin-sdk` removals are merged to `main`, will be deployed with next release

- https://github.com/hashicorp/terraform-plugin-framework/pull/684 still needs to be reviewed + will go with next framework release

**Comment by austinvalle** [comment]
All done 🚀
