### ISSUE TITLE
GetOkExists returns false during create when empty value is specified for List type

### ISSUE THREAD

**Issue by parweza** [hashicorp/terraform-plugin-sdk#116]
HI,
GetOkExists returns false during create when empty value is specified for List type. Because of that We are not able differentiate whether customer has omitted this field in tf config or has provided empty value.
```hcl
resource "oci_file_storage_export" "my_export_fs1_mt1" {
  #Required
  export_set_id  = "${oci_file_storage_export_set.my_export_set_1.id}"
  file_system_id = "${oci_file_storage_file_system.my_fs_1.id}"
  path           = "${var.export_path_fs1_mt1}"

  export_options = [
  ]
}
```
with above config we are expecting to get `true` for ok onhttps://github.com/oracle/terraform-provider-oci/blob/master/provider/file_storage_export_resource.go#L177
but we are getting false. 
Can you please look into it?

Thanks,
Parwez
### Terraform Version

```
0.10.8
```

### Terraform Configuration Files

```hcl
...
```

**Comment by paultyng** [comment]
This will most likely be solved by #261 given explicit access to Unknown vs empty list and #133 which will provide direct access to config values. Closing in favor of those.
