### ISSUE TITLE
Panic on errors in ResourceData on by default in tests

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#12]
It is recommended to always error check `ResourceData.Set` for complex fields, however this is easy to forget (or ignore) which in turns leads to bugs. This is why "opt-in panic" ENV variables `TF_SCHEMA_PANIC_ON_ERROR` was introduced:
https://github.com/hashicorp/terraform/pull/16588

The goal of this issue is merely to make this a default (i.e. panic by default) when the resource is being tested through our testing framework.

**Comment by paddycarver** [comment]
We have decided not to do this, because of the impact on user experience in production, and have decided to head in a different direction. See #451.
