### ISSUE TITLE
Terraform terminal progress bar  for community providers 

### ISSUE THREAD

**Issue by MalloZup** [hashicorp/terraform-plugin-sdk#126]
Hi all i would like to implement a progress bar for a community terraform provider which i'm co-maintaining. ( https://github.com/dmacvicar/terraform-provider-libvirt)

Is this feature possible with the current `schema` and and what pointer/library best-practices would you suggest? Is there a way to control the IO of terraform?
 Where could i start to look at with the `0.11` version or also with the `unreleased` one.

Thank you in advance ! :sunflower:

**Comment by paultyng** [comment]
Merging this with #145 that is about status updates (including general progress)
