### ISSUE TITLE
Terraform CloudFormation Multi Region Stacksets

### ISSUE THREAD

**Issue by rads18** [hashicorp/terraform-plugin-sdk#1263]
Hello team,

We have been using AWS Stacksets to deploy directly from AWS UI(Cloudformation) and trying to use Terraform to deploy the same Stacksets templates.

Based on documentation it appears we should be able to supply multiple regions but i do not see a key to supply multiple regions for parallel execution. However, per document (link below) for Resource: aws_cloudformation_stack_set_instance it has a operational_preference parameter that allows **PARALLEL** execution.

[region_concurrency_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance) 
- (Optional) The concurrency type of deploying StackSets operations in Regions, could be in parallel or one Region at a time.

thanks
Rads

**Note: The below configuration works But only for one region (us-east-1). There is not provision to provide multiple regions, yet in the instance configuration and documentation we can do PARALLEL, what is the meaning and significance for that? Hence, the confusion!**

CreateCloudstackSet.tf

```
resource "aws_cloudformation_stack_set" "amitest" {
  name = "ami-test-stackset"

  parameters = {
    ImageName = "xxxxxx"
  }

  template_body = file("../cftemplates/TestAmiLambda.yaml")
}
```

My instance.tf file is:

```
resource "aws_cloudformation_stack_set_instance" "amitest" {
  account_id = "xxxxxxxx"
  region     = "us-east-1"
  timeouts {
    create = "60m"
  }
  operation_preferences {
    region_concurrency_type = "PARALLEL"
  }
  stack_set_name = aws_cloudformation_stack_set.amitest.name
}
```

main.tf

```
provider "random" {}

## Provider us-east-1
provider "aws" {
  region = "us-east-1"
}
```

**Comment by bendbennett** [comment]
Hi @rads18 👋 

Sorry you ran into trouble here. 

I'm wondering if perhaps this issue should have been opened on the [AWS Terraform Provider](https://github.com/hashicorp/terraform-provider-aws) repository as the [aws_cloudformation_stack_set_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance) is part of the AWS provider.

**Comment by rads18** [comment]
Thanks @bendbennett for getting back to me .
