### ISSUE TITLE
Is it possible to have a dependency between 2 attributes?

### ISSUE THREAD

**Issue by orgads** [hashicorp/terraform-plugin-sdk#1267]
### SDK version
```
2.10.1
```

Regarding https://github.com/hashicorp/terraform-provider-azurerm/issues/13337 about azurerm_key_vault_secret.

When `value` is changed, this results in changes also to `version` and to `id`, but these changes are not detected until apply.

Is it possible to have a dependency to informs tf that if `value` is changed this will result in other fields changing in the target state (known after apply)? Notice that this does *not* create a new resource (the operation doesn't delete the previous secret and create a new one), it just creates a new version on the existing secret, which is reflected in its id.

### Terraform Configuration Files
```hcl
resource "azurerm_key_vault_secret" "test" {
  name = "test"
  value        = "foo"
  key_vault_id = azurerm_key_vault.main.id
}
```

### Expected Behavior
Changing the value should detect that `version` and `id` will change on apply, and consider them as "known after apply".

### Actual Behavior
They're considered unchanged in the plan, and on apply they have unexpected values. This leads to inconsistent plan on dependent resources that use the id, or at least a need to apply twice.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. Change value to "bar"
4. `terraform apply`

### References
- https://github.com/hashicorp/terraform-provider-azurerm/issues/13337

**Comment by bflad** [comment]
Hi @orgads 👋 Thank you for raising this.

Yes, it is possible to do this in terraform-plugin-sdk based provider code (and terraform-plugin-framework based provider code when the provider is migrated). The `helper/schema.Resource` can have a [`CustomizeDiff` function](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Resource.CustomizeDiff) which runs during the plan and notifies Terraform that the attribute value is unknown after apply. The [`helper/customdiff.ComputedIf()` function](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff#ComputedIf) is a helper for this exact use case.

For example, the terraform-provider-aws `aws_ssm_parameter` resource is coded where the `version` attribute is marked as unknown when the `value` attribute changes:

https://github.com/hashicorp/terraform-provider-aws/blob/8ffcc5d56801b13773e0894cfb8a148766a980ed/internal/service/ssm/parameter.go#L132-L134

If the attribute value after update is known upfront, then a custom `CustomizeDiff` function can be written that calls [`(helper/schema.ResourceDiff).SetNew()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceDiff.SetNew) to notify Terraform in the plan of the updated value.

Hope this helps. Please note that general provider development questions should either be asked in the provider issue tracker so those provider maintainers can offer a tailored answer for their particular provider coding patterns or on [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) where there are many more developers to answer. This issue tracker here is used for bug reports and feature requests. Thanks!
