### ISSUE TITLE
Low performance in deduplicate strings function

### ISSUE THREAD

**Issue by AntoniJakubiak** [hashicorp/terraform-plugin-sdk#1311]
https://github.com/hashicorp/terraform-plugin-sdk/blob/b7c8ee78f0ccdcdaa2a3fe4b26229203c7f5c3a3/terraform/util.go#L16

A typical implementation is:
```
input []string

m := make(map[string]bool, len(input))
for _, v := range input {
  m[v] = true
}
output := make(input, len(m))
i := 0
for v := range m {
 output[i] = v
 i++
}

```

**Comment by austinvalle** [comment]
Hi there @AntoniJakubiak 👋🏻 ,

Can you provide some more detail about how this performance is affecting your usage of the [`github.com/hashicorp/terraform-plugin-sdk/terraform`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/terraform) Go module?

From what I see, the function referenced is only called by the `(terraform.State).Remove` function

**Comment by AntoniJakubiak** [comment]
Hi,

Sorry for bothering you. I thought, that I'm in the middle of different project.

;)

**Comment by austinvalle** [comment]
No problem @AntoniJakubiak!
