### ISSUE TITLE
Terraform crash while running terraform plan

### ISSUE THREAD

**Issue by hilaf-pipl** [hashicorp/terraform-plugin-sdk#138]
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.1.0
```

### Terraform Configuration Files

```hcl

data "aws_security_group" "App-SG" {
  vpc_id = "${data.aws_vpcs.CommonCrawl-VPC.ids}"

  tags {
    Name = "App-SG"
  }
}

data "aws_iam_instance_profile" "Common-Crawl-Instance-Profile" {
  name = "commoncrawl-instance-profile"
}

data "aws_vpcs" "CommonCrawl-VPC" {
  tags = {
    Name = "Common-Crawl-VPC"
  }
}

data "aws_subnet_ids" "CommonCrawl-VPC-AppSubnet" {
  vpc_id = "${data.aws_vpcs.CommonCrawl-VPC.ids}"

  tags {
    Name = "Common-Crawl-VPC-priv_subnet-1"
  }
}
```

### Debug Output

Set TF_LOG=trace, pasted the output in Github Gist: https://gist.github.com/hilaf-pipl/754024f77515e200779693c4a1713914

### Crash Output

Github Gist crash log: https://gist.github.com/hilaf-pipl/8f66778d8ef4e73d1e84e6ed2e930b98

### Actual Behavior

Terraform crashed after showing the errors in my code on terraform plan

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. click enter on region choice (us-east-1)

**Comment by radeksimko** [comment]
> I believe in Terraform 0.12 this class of type mismatch crashes has been fixed and will properly return an error.

I can confirm this. The same config returns the following error in 0.12:

```
Error: Incorrect attribute value type

  on main.tf line 7, in data "aws_security_group" "App-SG":
   7:   vpc_id = "${data.aws_vpcs.CommonCrawl-VPC.ids}"

Inappropriate value for attribute "vpc_id": string required.


Error: Incorrect attribute value type

  on main.tf line 30, in data "aws_subnet_ids" "CommonCrawl-VPC-AppSubnet":
  30:   vpc_id = "${data.aws_vpcs.CommonCrawl-VPC.ids}"

Inappropriate value for attribute "vpc_id": string required.

```

I will therefore consider this as closed.
