### ISSUE TITLE
Terraform Refresh on resource with Exists function can't handle deleted items

### ISSUE THREAD

**Issue by NeilW** [hashicorp/terraform-plugin-sdk#143]
### Terraform Version

```
Terraform v0.11.13
```

### Terraform Configuration Files

```hcl
Any cloud resource with an 'Exists' function
```

### Expected Behavior

Refresh brings the state into line with reality. The convention seems to be that deleted items are handled by the Read function setting the Id to the empty string. However if the resource has an Exists function, that is called instead and returns 'false'. Terraform refresh should mark the resource as missing (possibly with a warning) rather than throwing an error when it gets a 'false'. 

### Actual Behavior
Terraform refresh errors with 

Error: Error refreshing state: 1 error(s) occurred:

* brightbox_container.binnable: 1 error(s) occurred:

* brightbox_container.binnable: brightbox_container.binnable: Resource not found

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Remove item in the cloud using native tools
4. `terraform refresh`

**Comment by bflad** [comment]
Hi @NeilW 👋  When version 2 of the SDK was released, the `Exists` functionality was marked as deprecated. Across the ecosystem it was commonly found that implementing `Exists` led to confusion such as this and often led to duplicated API reading code in Terraform Providers. To that end, the recommendation these days is to only implement `Read`/`ReadContext`/`ReadWithoutTimeout` and signal to Terraform CLI about resource removal by calling `(*ResourceData).SetId("")`. 👍
