### ISSUE TITLE
Inaccurate diagnostics context for deprecated fields

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#146]
### Terraform Version

cb4f3004daac

Latest `master` (`52a055beca249b1d8e47408f8834d4c13b62e642`) of Packet provider compiled with cb4f3004daac of Terraform.

### Terraform Configuration Files
```hcl
provider "packet" {}

resource "packet_project" "tf_project_1" {
  name = "Terraform Fun"
}

resource "packet_device" "web1" {
  hostname         = "tf.coreos2"
  plan             = "t1.small.x86"
  facility         = "ewr1"
  operating_system = "coreos_stable"
  billing_cycle    = "hourly"
  project_id       = "${packet_project.tf_project_1.id}"
}
```

### Expected Behavior

```
$ terraform plan

...

Plan: 2 to add, 0 to change, 0 to destroy.

Warning: "facility": [DEPRECATED] Use the 'facilities' array instead.

  on main.tf line 10, in resource "packet_device" "web1":
   10:   facility         = "ewr1"



------------------------------------------------------------------------
```

### Actual Behavior

```
$ terraform plan

...

Plan: 2 to add, 0 to change, 0 to destroy.

Warning: "facility": [DEPRECATED] Use the 'facilities' array instead.

  on main.tf line 7, in resource "packet_device" "web1":
   7: resource "packet_device" "web1" {



------------------------------------------------------------------------
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by radeksimko** [comment]
It seems that type validation errors, such as float provided for TypeInt are also lacking context - perhaps the same cause/codepath. I saw that when reproducing #107 using code from https://github.com/hashicorp/terraform-plugin-sdk/issues/107#issuecomment-407137107

```
Error: retention_in_days: must be a whole number, got 1.5

  on main.tf line 6, in resource "aws_cloudwatch_log_group" "test":
   6: resource "aws_cloudwatch_log_group" "test" {

```

**Comment by bflad** [comment]
I don't recall seeing issues relating to this since terraform-plugin-sdk/v2, so I'm going to optimistically close it out on the assumption that the various code refactoring to support native diagnostics and pipe cty attribute path information throughout helper/schema and helper/validation helped in these scenarios. If that's not the case on recent versions of Terraform CLI and the SDK, please open a new issue and we can take a fresh look. 👍
