### ISSUE TITLE
provider-sdk issue with import for properties that are not returned by the service.

### ISSUE THREAD

**Issue by rcohenma** [hashicorp/terraform-plugin-sdk#147]
I work on the OCI provider.

We are wondering how we would be able to support import in terraform for resources that have a property that is ForceNew and is only supplied in the Create but not returned by the Service on a Get.
There are legitimate use cases for this for example Databases that expect a password field in the Create but the password cannot be returned on the Get for security reasons.

The behavior we are seeing is that when the user would be able import the resource without the password populated. The next apply would always result in a force new change caused by the password

I tried doing a Diff Suppress function

```go
func propNotReturnedByServiceSuppressFunction(key string, old string, new string, d *schema.ResourceData) bool {
	if old == "" {
		return true
	}
	return false
}
```

This works fine for subsequent applies after the import but it breaks the Create case.

If I have the that diff suppress function when I try to create a database the password gets excluded from the request and since it is a required field the request will fail. This looks like bug to me on the provider SDK. Why would having the diff suppress function cause to GetOkExists to return nothing for that property?

Do you have another suggestion as to how we can make this work?

Thanks

**Comment by paultyng** [comment]
@rcohenma does the above resolution address your needs?

**Comment by paultyng** [comment]
Going to close this as we haven't heard back. Please let me know if this is still an issue for you and how we can address it.
