### ISSUE TITLE
UX for Beanstalk changes is abysmal

### ISSUE THREAD

**Issue by kevinburkenotion** [hashicorp/terraform-plugin-sdk#149]
A single change to a typical Elastic Beanstalk configuration will generate 100-500 lines of Terraform output depending on how many settings you have configured. A lot of these have low information value, for example, here the configuration is changing from "false" to "false". There are tens to hundreds of lines printed for any change that look exactly like this.

```
      setting.2322805565.namespace: "aws:elbv2:listener:default" => "aws:elbv2:listener:default"
      setting.2322805565.resource:  "" => ""
      setting.2322805565.value:     "false" => "false"
```

I just deployed an error to production that broke software at the company I'm working with because I missed one line of changed diff out of 250 that remained the same and I would be interested in solutions that would reduce the risk of making a similar mistake.

**Comment by GRoguelon** [comment]
Hi @apparentlymart, any update? Thank you in advance.

**Comment by paultyng** [comment]
As Martin states above, rich map support would solve this, going to merge this in to #62
