### ISSUE TITLE
v0.12: Error verifying planned changes against actual changes with case-insensitive values

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform-plugin-sdk#152]
### Terraform Version

```
v0.12.0-alpha4.0.20190429183344-30199600eb15
```

### Terraform Configuration Files

```hcl
resource "oci_database_db_system" "test_db_system" {
	availability_domain = "${oci_core_subnet.test_subnet.availability_domain}"
	compartment_id = "${var.compartment_id}"
...
}

resource "oci_core_subnet" "test_subnet" {
        availability_domain = "${lower("${data.oci_identity_availability_domains.test_availability_domains.availability_domains.0.name}")}"
... 
}
```

### Expected Behavior

Running an "apply" succeeds with v0.11.

### Actual Behavior

In v0.12, the "apply" results in an error like this:

```
Error: Provider produced inconsistent final plan
        
        When expanding the plan for oci_database_db_system.test_db_system to include
        new values learned so far during apply, provider "oci" produced an invalid new
        value for .availability_domain: was cty.StringVal("loil:us-ashburn-ad-1"), but
        now cty.StringVal("LOil:US-ASHBURN-AD-1").
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

### Steps to Reproduce

`terraform apply`

### Additional Context

Both `oci_database_db_system` and `oci_core_subnet` resource have a `DiffSuppressFunc` assigned to the `availability_domain` field. The suppress function returns result of `strings.EqualFold(old, new)` (i.e. true if strings are case-insensitive equal).

Even though `oci_core_subnet` uses `lower()` to convert the input availability_domain to lower-case (e.g. `loil:us-ashburn-ad-1`), the service may return a mixed-case value (e.g. `LOil:US-ASHBURN-AD-1`) as part of a refresh on the resource.

**Comment by paultyng** [comment]
@alexng-canuck does the above response address your concerns? Will normalization fix the issue?

**Comment by paultyng** [comment]
Going to close this as we haven't heard back, if this is still an issue please just respond here and let me know and we can reopen.
