### ISSUE TITLE
"ValidateFunc is not yet supported on lists or sets"

### ISSUE THREAD

**Issue by immarvin** [hashicorp/terraform-plugin-sdk#156]
Hi, when I am trying to add some validation for TypeList attribute in my resource schema, `terraform validate` complain this message. I wonder why Terraform impose such restriction, is it necessary?
thanks

**Comment by ctrombley** [comment]
Is there a workaround for this?

**Comment by ozerovandrei** [comment]
Hi guys!

Any updates on this?

I see a https://github.com/hashicorp/terraform-plugin-sdk/blob/v1.11.0/helper/validation/list.go but it seems it's unusable because of https://github.com/hashicorp/terraform-plugin-sdk/blob/v1.11.0/helper/schema/schema.go#L852.

**Comment by AniketKariya** [comment]
it's nearly 3 years now, if there are no plans on implementing this, at least close this issue with acknowledgment.

**Comment by brianonn** [comment]
I needed this today.  It would be useful to have ValidateFuncs supported on `schema.TypeList` for my use case

**Comment by iamunni** [comment]
is there any workaround for this?

**Comment by bflad** [comment]
The newer Terraform Plugin Framework, which was [released last year](https://www.hashicorp.com/blog/terraform-plugin-framework-is-now-generally-available), was developed from the ground up to not impose type-based restrictions on configuration validation logic amongst [many other benefits](https://developer.hashicorp.com/terraform/plugin/framework-benefits). In particular, the HashiCorp Developer website includes framework documentation pages dedicated to validation for [resource](https://developer.hashicorp.com/terraform/plugin/framework/resources/validate-configuration), [data source](https://developer.hashicorp.com/terraform/plugin/framework/data-sources/validate-configuration), and [provider](https://developer.hashicorp.com/terraform/plugin/framework/providers/validate-configuration) configurations. It also provides a [SDK migration guide](https://developer.hashicorp.com/terraform/plugin/framework/migrating) for existing providers, including the ability to iteratively introduce framework resources alongside SDK resources using Terraform Plugin Mux, if desired.

Given the likelihood that this particular feature will not be implemented in _this_ SDK and that it is already implemented in the newer framework, I'm going to close this issue as suggested by https://github.com/hashicorp/terraform-plugin-sdk/issues/156#issuecomment-1105348253.
