### ISSUE TITLE
enhance terraform providers schema -json for docs generation

### ISSUE THREAD

**Issue by Heiko-san** [hashicorp/terraform-plugin-sdk#177]
Please enhance the command ` terraform providers schema -json` as provided by terraform 12 to reflect more information.
The JSON is very useful for writing scripts to automatically generate "Attribute Reference" docs for custom providers, as described here: https://discuss.hashicorp.com/t/how-to-document-custom-terraform-providers/2765.

However there is some information missing that is rather essential, e.g.: Default (at least if it is a value and not a DefaultFunc) or for nested block types (reflected under "block_types" rather then "attributes") there is almost no additional info, these blocks can be optional, have a description, ...
``` hcl
"my_block_attr": {
  Type: schema.TypeList,
  Optional: true,
  Computed:    true,
  Description: "This is my block type attribute.",
  Elem: &schema.Resource{
    Schema: map[string]*schema.Schema{
      "a_key": {
        ...
```
It would be helpful if these attributes would be reflected also for nested block fields.

Also there are more fields, that aren't reflected yet, but may be helpful for docs generation, e.g.: ForceNew, ConflictsWith and maybe Deprecated & Removed.

**Comment by paultyng** [comment]
The v2 RC (now on master) supports resource and block level descriptions, as well as deprecated flags. You can optionally send descriptions in markdown form. These additional fields satisfy all the needs for a language server, and can also be used by the documentation generation.

In addition, you can customize how the descriptions are built by overriding the description builder functions: https://github.com/hashicorp/terraform-plugin-sdk/blob/ac1c09290269b998204e08e90e6b2d7d376deb0d/helper/schema/core_schema.go#L19, for example, you could append default values to description strings prior to dumping the schema.

We are exploring new tooling to generate website docs using schema dumping, so going to close this issue as we have enhanced the JSON enough to support both use cases.
