### ISSUE TITLE
d.HasChanges("", "", "")

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform-plugin-sdk#194]
Today `d.HasChange` only takes a single argument - when in practice many are generally chained together, for example:

`if d.HasChange("foo") || d.HasChange("bar") {`

This'd be cleaner as one method which took a list of strings/arguments, for example:

```
func HasChanges(input []string..) bool {
  for _, v := range input {
    if HasChange(v) {
      return true
    }
  }

  return false
}
```

Which would greatly reduce the size of some of these if statements within providers

**Comment by paultyng** [comment]
You could probably just extend the old method if you are going to make it `...` anyway.
