### ISSUE TITLE
TypeSet is written with list indexes into the state and cannot be accessed

### ISSUE THREAD

**Issue by mavogel** [hashicorp/terraform-plugin-sdk#196]
Given a property is of `TypeSet`

```hcl
"upload": {
    Type:     schema.TypeSet,
    Optional: true,
    ForceNew: true,
```
- you will see in the log of the test, so the properties are actually written into the state
```
  upload.# = 1
  upload.0.content = foo
  upload.0.content_base64 = 
  upload.0.executable = true
  upload.0.file = /terraform/test.txt
```
- but actually the check fails:
```go
resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDockerContainerUploadConfig,
				Check: resource.ComposeTestCheckFunc(
					testAccContainerRunning("docker_container.foo", &c),
					testCheck,
					resource.TestCheckResourceAttr("docker_container.foo", "name", "tf-test"),
					resource.TestCheckResourceAttr("docker_container.foo", "upload.#", "1"),
					// TODO mavogel: although they are in the state they are not found... check fails
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.content", "foo"),
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.content_base64", ""),
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.executable", "true"),
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.file", "/terraform/test.txt"),
				),
			},
		},
	})
```

### Step to reproduce
- check out latest master of https://github.com/terraform-providers/terraform-provider-docker
- uncomment the checks in the given test and run the cmds
```sh
make testacc_setup
TF_LOG=INFO TF_ACC=1 go test -v ./docker -run ^TestAccDockerContainer_upload$ -timeout 360s
```

### References
- https://github.com/terraform-providers/terraform-provider-docker/pull/194

> We’ve noticed the same with the AWS provider. :point_up: Its likely that the acceptance testing framework shims (still using the older flatmap-style addressing) are missing a conversion with the hashes.

**Comment by pdecat** [comment]
With TypeSet, the format used to store set elements in the state isn't a list with zero-based index, but the computed hash of the set element is used:

```
// indexesIntoTypeSet is a heuristic to try and identify if a flatmap style
// string address uses a precalculated TypeSet hash, which are integers and
// typically are large and obviously not a list index
```

See https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.0.0-rc.2/helper/resource/testing.go#L970-L972

So in your case, you would have something like:

```
					resource.TestCheckResourceAttr("docker_container.foo", "upload.12345678.content", "foo"),
					resource.TestCheckResourceAttr("docker_container.foo", "upload.12345678.content_base64", ""),
					resource.TestCheckResourceAttr("docker_container.foo", "upload.12345678.executable", "true"),
					resource.TestCheckResourceAttr("docker_container.foo", "upload.12345678.file", "/terraform/test.txt"),
```

There are already occurrences of such tests in the docker provider code base: https://github.com/terraform-providers/terraform-provider-docker/blob/v2.7.1/docker/resource_docker_service_test.go#L425-L429

From my experience, the easiest way to determine the actual hashes for each element is to dump the state in debug level trace at the end of the read functions. Adding break points there also works and inspecting variables but I found that to be more painful.

Note: while this is possible with v1 of the SDK when not using the new binary driver: https://github.com/hashicorp/terraform-plugin-sdk/blob/v1.14.0/helper/resource/testing.go#L1438-L1458 ,
it is no longer the case in v2 as the binary driver is now mandatory and does not provide that facility (yet?): https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.0.0-rc.2/helper/resource/testing.go#L986

**Comment by appilon** [comment]
Hello all,

Indeed what @pdecat describes is correct, in V1 of the SDK, one would have to pre calculate the hash to index into the aggregate type for test checks.

In V2 of the SDK (and V1 with the binary driver enabled) the set hash is lost through the many layers of the binary setup. We have developed a workaround in the AWS provider, which eventually will land upstream in V2 of the SDK (and possibly backported to V1)

https://github.com/terraform-providers/terraform-provider-aws/pull/13556

We will hopefully have these helpers upstream soon.

**Comment by appilon** [comment]
@pdecat sorry about that, we are prioritizing landing it upstream and making it importable.

**Comment by ag-TJNII** [comment]
> From my experience, the easiest way to determine the actual hashes for each element is to dump the state in debug level trace at the end of the read functions. Adding break points there also works and inspecting variables but I found that to be more painful.

**Comment by mavogel** [comment]
Update @appilon : using `github.com/hashicorp/terraform-plugin-sdk/v2` with version `v2.6.1`  lets the checks pass also with `upload` still being of type `schema.TypeSet`:

```
resource.TestCheckResourceAttr("docker_container.foo", "upload.0.content", "foo"),
resource.TestCheckResourceAttr("docker_container.foo", "upload.0.content_base64", ""),
resource.TestCheckResourceAttr("docker_container.foo", "upload.0.executable", "true"),
resource.TestCheckResourceAttr("docker_container.foo", "upload.0.file", "/terraform/test.txt"),
```

IMHO we can close this issue then

**Comment by magodo** [comment]
@appilon Is there any issue to track the progress of Set support in binary testing framework?

**Comment by bflad** [comment]
Hi folks 👋  Apologies for the delayed response here.

Recent versions of the `helper/resource` package include new `TypeSet` check functions:

- [`TestCheckTypeSetElemAttr`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckTypeSetElemAttr)
- [`TestCheckTypeSetElemAttrPair`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckTypeSetElemAttrPair)
- [`TestCheckTypeSetElemNestedAttrs`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckTypeSetElemNestedAttrs)

These can be used to verify values inside `TypeSet` attributes by replacing the set element integer/hash with a `*`. They are also documented in the [acceptance testing documentation](https://www.terraform.io/plugin/sdkv2/testing/acceptance-tests/teststep#builtin-check-functions). If you have questions about usage, please feel free to reach out in the [HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/31). 👍
