### ISSUE TITLE
Plan-time validation if attempting to manage the same physical resource with two Terraform resources

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#202]
For example, consider the `aws_s3_bucket_policy` resource:

```hcl
resource "aws_s3_bucket" "b" {
  bucket = "my_tf_test_bucket"
}

resource "aws_s3_bucket_policy" "b" {
  bucket = "${aws_s3_bucket.b.id}"

  policy = ...
}
```
AWS permits only one bucket policy per bucket, and buckets are individuated by the `bucket.id` attribute. However, there is nothing to stop us creating multiple `aws_s3_bucket_policy` resources for the same `bucket` in our Terraform configuration.

A new schema behaviour, or other plan-time validation, could enforce at most one resource for each value of the specified attribute.

Proposed by @bflad.

**Comment by apparentlymart** [comment]
I wrote up some notes on an idea that relates to this in hashicorp/terraform#22094, but that it a larger idea conceptually so if there is a smaller version of it that fits in the SDK itself that'd be great!

**Comment by bflad** [comment]
I believe this may be the same as https://github.com/hashicorp/terraform-plugin-sdk/issues/224
