### ISSUE TITLE
Support for online validation during plan time

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#204]
Allow API calls when validating resource attributes.

## Example

This example is copied from from [tflint](https://github.com/wata727/tflint), a third-party tool that implements this behaviour.

Consider the following configuration file:
```
resource "aws_instance" "foo" {
  ami           = "ami-0ff8a91507f77f867"
  instance_type = "t1.2xlarge" # invalid type!
}
```
Since `t1.2xlarge` is a nonexistent instance type, an error will occur when you run `terraform apply`. But `terraform plan` and `terraform validate` cannot find this possible error beforehand. That's because it's an AWS provider-specific issue and it's valid as a Terraform configuration.

**Comment by radeksimko** [comment]
I think this is a duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/101 - not sure which one do we want to retain.

**Comment by kmoe** [comment]
Thanks, I didn't see #101. Closing this issue as a duplicate.
