### ISSUE TITLE
Terraform test cann't ignore skema attribute

### ISSUE THREAD

**Issue by yupwei68** [hashicorp/terraform-plugin-sdk#209]
### Terraform Version

```
 v0.12.10
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

terraform test success 

### Actual Behavior

error: After applying this step, the plan was not empty
DIFF, the others are the same, except one attribute XX_access_key:""=>"XXXXX"

### Steps to Reproduce

1. in skema behavior:
```
"XX_access_key": {
				Type:     schema.TypeString,
				Required: true,
                                Sensitive:true,
			},
```

2. in test:
```
resource.ParallelTest(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config:             testAccXX_complete(ri, testLocation()),
				Check: resource.ComposeTestCheckFunc(
					testCheckXXExists(resourceName),
					
			},
			{
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"XX_access_key", "XX"},
			},
		},
	})
```
I want to ignore this attribute in skema, because it doesn't return in state after creation. And it will cause the refresh plan not to be empty. But no matter I have tried to ignore it in "ImportStateVerifyIgnore", it does not work.

 I have then tried to write a DiffSuppressFunc function in skema to dismiss the difference, but it will influence the creation of the resource and turn out to be one error in resource creation.

How could I ignore one skema attribute in Terraform test if it does not return back after creation

**Comment by paultyng** [comment]
This is how the testing should work. I've verified this is working in other providers. Can you provide additional details or a reproduction so we can dig in further?

**Comment by yupwei68** [comment]
hi @paultyng, I was realized that the first step verify "terraform plan -refresh=false",while the second step "import Verify" verify that the state is the same with the previous step with schema empty. Am I right?

**Comment by paultyng** [comment]
Yes, the import step will drop everything from state, run your import code for the passed resource name, and compare it to make sure it matches the previous step (ignoring any passed attributes, typically these are attributes that are not provided by the upstream API).

**Comment by yupwei68** [comment]
hi @paultyng Thanks
