### ISSUE TITLE
Bespoke (contextual) CRUD functions

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#234]
## Problem statement

The main interface SDK exposes for providers to interact with Terraform core is CRUD functions as part of [`schema.Resource`](https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/schema#Resource):
https://github.com/hashicorp/terraform-plugin-sdk/blob/805741e3861bf69873b6a6db493b7f58fea75d9d/helper/schema/resource.go#L120-L124

```go
type Resource struct {
	// ...
	Create CreateFunc
	Read   ReadFunc
	Update UpdateFunc
	Delete DeleteFunc
}

type CreateFunc func(*ResourceData, interface{}) error
type ReadFunc func(*ResourceData, interface{}) error
type UpdateFunc func(*ResourceData, interface{}) error
type DeleteFunc func(*ResourceData, interface{}) error
```

While we have separate `type`s for each method, they all receive the same data through `*ResourceData`, which breaks single responsibility principle and leads to less experienced provider developers introducing common bugs and abusing the interface, such as:

 - `d.Timeout(TimeoutCreate)` in `Update`
 - forgetting to deal with "resource disappeared" scenario, i.e. forgetting to call `d.SetId("")` in `Read` when resource is not found, to allow Terraform to reconcile from that.
 - Calling `d.SetId("")` unnecessarily in `Delete` (lower-level implementation of `Delete` always ensures resource is removed from state, `d.SetId("")` is therefore unnecessary)
 - `Create` doesn't call `Read` when it may be necessary for pre-filling all data to state
 - `Create` calls `Update` unnecessarily which duplicates API calls
 - Calling `d.Get()` type calls in `Read` (which doesn’t work with import usually)

### AWS

The AWS provider uses linters to catch similar to some of the above bugs early, but lack of bespoke interfaces for CRUD prevents them from catching the above.

## Proposal

TODO

**Comment by bflad** [comment]
As you probably already know, this issue does not exist in [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework) 🎉  CRUD methods are implemented with bespoke Request and Response types and data is represented via Config, Plan, and State types.
