### ISSUE TITLE
Plan time validation for interpolated values

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-plugin-sdk#250]
## Problem

Often times a there is a computed value that we know the general "shape" of (ex: `vpc-1234`) and a downstream attribute interpolates this value. That downstream value has validation to ensure it begins with say `sg-`. It would be helpful if we could hint to Terraform that the computed attribute has an expected format and we could have the configuration fail plantime validation.

## Proposal

**Comment by paultyng** [comment]
Merging this to #61
