### ISSUE TITLE
Validate removed attributes before required ones

### ISSUE THREAD

**Issue by QuentinBrosse** [hashicorp/terraform-plugin-sdk#263]
Hi,

Validate the removed attributes before the required ones would allow a better UX.

## Example

Here is the first version of a test schema:
```go
&schema.Resource{
	Schema: map[string]*schema.Schema{
		"offer_id": {
			Type:     schema.TypeString,
			Required: true,
			ForceNew: true,
		},
	},
}
```

A bit later, we decide to replace the `offer_id` by `offer` (to handle offer name and UUID in the same attribute). After depreciating the `offer_id` field during some releases, we decide to remove it with the [`Schema.Removed`](https://godoc.org/github.com/hashicorp/terraform/helper/schema#Schema) field:
```go
&schema.Resource{
	Schema: map[string]*schema.Schema{
		"offer": {
			Type:     schema.TypeString,
			Required: true,
			ForceNew: true,
		},
		"offer_id": {
			Type:     schema.TypeString,
			Optional: true,
			Removed:  "Please use offer attribute instead",
		},
	},
}
```

After the provider update, the user will still have this old configuration:
```tf
resource "scaleway_test" "test" {
  offer_id = "11111111-1111-1111-1111-111111111111"
}
```

The `terraform [validate|plan]` command will throw this error:
```
Error: Missing required argument

  on example.tf line 15, in resource "scaleway_bla" "bla":
  15: resource "scaleway_test" "test" {

The argument "offer" is required, but no definition was found.
```

The user does not understand why the `offer` attribute is required, he already has an `offer_id` attribute. If the removed validation was done before the required one, the user would have this error:
```
Error: "offer_id": [REMOVED] Please use offer attribute instead

  on example.tf line 15, in resource "scaleway_bla" "bla":
  15: resource "scaleway_test" "test" {
```

In this way, the user will understand easily that the `offer_id` attribute has been replaced by the `offer` one.

**Comment by paultyng** [comment]
We are planning to drop support for `Removed` in v2, so this issue will no longer be relevant I believe.
