### ISSUE TITLE
Upgrading state error during acceptance tests involving for_each

### ISSUE THREAD

**Issue by pst** [hashicorp/terraform-plugin-sdk#264]
I am working on a Terraform provider for Kustomize. The provider has a data source that runs Kustomize and I additionally provide a resource that based on the K8s' dynamic client-go library handles the K8s communication. The provider works as intended. Usage looks like this:

```
data "kustomization" "test" {
  path = "base"
}

resource "kustomization_resource" "test" {
  for_each = data.kustomization.test.ids

  json = data.kustomization.test.resources[each.value]
}
```

While writing acceptance tests for the provider I am facing the following error:

```
=== RUN   TestAccDataSourceKustomization_basic
--- PASS: TestAccDataSourceKustomization_basic (0.07s)
=== RUN   TestAccResourceKustomization_basic
--- FAIL: TestAccResourceKustomization_basic (0.04s)
    testing.go:635: Step 0 error: Check failed: 1 error occurred:
        	* Check 1/1 error: Not found: kustomization_resource.test in [root]
        
        
    testing.go:696: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: State format upgrade failed: Error upgrading state file format from version 3 to version 4: error parsing resource address "kustomization_resource.test.[\"~G_v1_Namespace|~X|test\"]": strconv.ParseInt: parsing "[\"~G_v1_Namespace|~X|test\"]": invalid syntax.
        
        State: <nil>
FAIL
exit status 1
FAIL	github.com/pst/terraform-provider-kustomize	0.132s
```

As far as I can tell the error originates in the upgrade state from v3 to v4: https://github.com/hashicorp/terraform-plugin-sdk/blob/e664f5b78081fde148c4ea55a0e068dc62fb2274/internal/states/statefile/version3_upgrade.go#L353

Which seems to not be able to handle anything but integers as the index. Since `for_each` is new I am assuming v3 was never intended to support this.

Temporarily skipping the `for_each` and using the provider like this in the test makes the tests pass:

```
func testAccResourceKustomizationConfig_basic(path string) string {
	return testAccDataSourceKustomizationConfig_basic(path) + `
resource "kustomization_resource" "test" {
  json = data.kustomization.test.resources["~G_v1_Namespace|~X|test"]
}
`
```

Test output without `for_each`:

```
=== RUN   TestAccDataSourceKustomization_basic
--- PASS: TestAccDataSourceKustomization_basic (0.06s)
=== RUN   TestAccResourceKustomization_basic
--- PASS: TestAccResourceKustomization_basic (0.08s)
PASS
ok  	github.com/pst/terraform-provider-kustomize	0.174s

```

I am assuming the actual apply/destroy directly uses a v4 state. I am not sure if starting with a v3 state in the tests is intentional or a bug in the SDK.

**Comment by matpimenta** [comment]
I'm having a similar issue. It looks like the `Version` field of `terraform.State` is always populated from this constant `https://github.com/hashicorp/terraform-plugin-sdk/blob/master/terraform/state.go#L27 which is always `3`. 
I could change the constant to `4` but I don't know the impact of this across Terraform. Any thoughts?

**Comment by bflad** [comment]
I'm guessing that many state-related issues with acceptance testing in this SDK would've been resolved with v2 and later, which is now wholly dependent on interacting with actual Terraform CLI binaries and their stable output formats, rather than mimicking some the Terraform internals in this codebase. If you are still having issues with _that_ particular functionality, please open a new issue and we can take a fresh look.

Please also note though, that `for_each` support is _not_ currently implemented in the v2 testing framework. You can subscribe to https://github.com/hashicorp/terraform-plugin-sdk/issues/536 for further updates on that subject.
