### ISSUE TITLE
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag"

### ISSUE THREAD

**Issue by LorbusChris** [hashicorp/terraform-plugin-sdk#268]
### SDK version
```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.3.0"
}
```

### Description of Problem

In https://github.com/openshift/installer/ we have multiple plugins for different providers.
Some of those providers have migrated to `terraform-plugin-sdk` while others haven't and still use `terraform`.

Over in https://github.com/openshift/installer/pull/2745 I'm bumping these providers, and that's where I run into a problem:

```
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag
```

The initialization of them happens here, respectively:
https://github.com/hashicorp/terraform/blob/master/tfdiags/rpc_friendly.go#L58
and
https://github.com/hashicorp/terraform-plugin-sdk/blob/master/internal/tfdiags/rpc_friendly.go#L58

Since they are the same type, just from different vendored files, they can't both be initialized at the same time.

This happens in all runs of our unit as well as e2e tests. Links to exemplary CI runs below.

Is it maybe possilbe to deduplicate those and have one canonical location for them?
E.g. vendoring these types from this repo in the `terraform` repo, or the other way around?
Or creating a `common` module that both repos can depend on? 

### Expected Behavior
No panic

### Actual Behavior
panic

### References
- https://github.com/openshift/installer/pull/2745#issuecomment-561802328
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2745/pull-ci-openshift-installer-master-e2e-aws/8839
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2745/pull-ci-openshift-installer-master-unit/6946

**Comment by radeksimko** [comment]
Hi @LorbusChris 
Unfortunately providers were never designed to be imported as Go packages in other Go projects and their APIs don't provide any guarantees. I'm sorry we weren't clear about it before, but @paddycarver does a great job at explaining it in [this docs page](https://github.com/hashicorp/terraform-website/pull/974/files#diff-3cb1ccd0ee236532a8c512d9347608e2R9) which is soon to be merged and published on `terraform.io`. This will hopefully discourage more people from doing that.

The same page also describes how you can interact with Terraform in a supported way and what to do if the use case (presumably reason you are importing today) isn't supported.

> E.g. vendoring these types from this repo in the terraform repo, or the other way around?

One of the main motivations behind separating SDK from core was to cut down the number of dependencies (esp. transitive dependencies). We would effectively revert all this (still ongoing) effort by making SDK import core as we'd bring core's dependency tree back to providers.

The longer term plan is to cut out SDK logic from core and core logic from SDK (there's currently still a lot of duplicated packages) and also to cut out RPC logic from both. As the code you're referring to is related to the old RPC protocol, there will be very little motivation to invest any effort into extracting it as we'd rather see it gone.

Generally speaking I would suggest you to review the reasons for importing providers and discuss your use cases in the [Terraform Core issue tracker](https://github.com/hashicorp/terraform/issues/new/choose).

**Comment by LorbusChris** [comment]
@radeksimko thank you for providing context on this. Is there an open issue to track the removal of that RPC code?

**Comment by radeksimko** [comment]
@LorbusChris Removal of the old RPC protocol is related to our plans for deprecating Terraform 0.11, as all past versions (prior to 0.12) speak that protocol. We have published a blogpost outlining this plan for some major providers at https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers/

On SDK's side you can track any issue [labelled as `proto-5-only`](https://github.com/hashicorp/terraform-plugin-sdk/issues?q=is%3Aissue+is%3Aopen+label%3Aprotocol-5-only) which we use to label features that can only be delivered to a provider that speaks proto 5 (i.e. gRPC) and _not_ netRPC anymore (proto 4). In other words these features require us to break backward compatibility on the protocol level.

I can say that this is one of our priorities, but we want to get the communication part done right too and provide folks some time to migrate away from older Terraform versions.
