### ISSUE TITLE
Undocumented behavior in `WaitForState`

### ISSUE THREAD

**Issue by xanderflood** [hashicorp/terraform-plugin-sdk#269]
By default `WaitForState` will stop with a timeout error if the `StateRefreshFunc` returns nil 20 consecutive times. As far as I can tell, the [godoc](https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/resource#StateChangeConf) and [TF docs](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html) both don't mention this behavior.

The general idea seems to be that `WaitForState` treats the situation one way if `Refresh` returns nil and a pending state, but a different way if `Refresh` return non-nil and a pending state, counting the former as a "not found" and the latter as a regular "keep waiting" signal. Again, there's nothing I can find in the docs that reveals that these two things are treated differently or mentions this "NotFound" semantics. The docs for [StateRefreshFunc](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html) have the following to say about it:

> It returns three results. `result` is any object that will be returned as the final object after waiting for state change. This allows you to return the final updated object, for example an EC2 instance after refreshing it.

which seems to indicate that the value is ignored except at the end.

This lack of documention leads to unexpected behavior when a `Refresh` is written that doesn't bother to return a non-nil object. In my case, this is because I'm genuinely waiting for the object to be created, not waiting for it to enter a particular state.

So why this counting-not-founds behavior? It's not clear to me what benefits it adds, but if it is to be kept it should certainly be better documented, since it currently places a hidden limit on timeouts and produces an unhelpful error that doesn't explain why the operation didn't run as long as I intended it to.

## Workaround
Don't return nil! The return signature is `interface{}`, so you can return anything you like - I used `0`.

**Comment by xanderflood** [comment]
To clarify, the `NotFoundChecks` field is documented as:

> Number of times to allow not found

but there doesn't appear to be an explanation of the fact that "not found" is a term for `Refresh` returning nil, not do the docs mention that a default value will be inserted if this is left unset.

**Comment by paultyng** [comment]
I added some clarification in bafcfa8 on how not found is determined. The godoc updates will land in version 2.
