### ISSUE TITLE
Need schema attribute type of Resource

### ISSUE THREAD

**Issue by papineni87** [hashicorp/terraform-plugin-sdk#270]
hi ,

i am using terraform 0.12.6, and below is my requirement

```hcl
resource "abc" "test1" {
  x = 10
  y = xyz.test2 

resource "xyz" "test2" {
  a = 10
  b = 20
}
```

When i am reading resource abc , i have a input element y which has to read another resource  elements, i.e., i need a schema attribute of Resource ( like string,int,map .. ) so that i can read one resource from another resource

**Comment by radeksimko** [comment]
Hi @papineni87 
Thanks for the issue.

While modules themselves are capable of accepting and outputting whole resources this isn't currently possible for resource fields.

I would suggest subscribing to https://github.com/hashicorp/terraform-plugin-sdk/issues/155 which tracks exposure of nested structures that resources effectively are. I'm going to close this issue to keep discussion in one place.
