### ISSUE TITLE
Unassigned variable error occurs even if I already set the variable TF_VAR_xname before running acceptance tests

### ISSUE THREAD

**Issue by Enjolras67** [hashicorp/terraform-plugin-sdk#274]
### Terraform Version

```
$ terraform version
Terraform v0.12.17
```

### Terraform Configuration Files

```hcl
provider customprovider{
}

variable "xname" {
  description = "current user's name"
}
resource "custom_resource" "server" {
 count = 1
 name = "${var.xname}"
...
}
```

### Expected Behavior

run acceptance tests

### Actual Behavior

Test failed:
    testing.go:569: Step 0 error: config is invalid: Unassigned variable: The input variable "xname" has not been assigned a value. This is a bug in Terraform; please report it in a GitHub issue.

### Steps to Reproduce

export TF_VAR_xname=abc
go test ./... -v

**Comment by paddycarver** [comment]
Hey @Enjolras67,

Does this still not work in version 2 of the SDK? The way v2 runs tests has been updated to drive a real Terraform binary, so I suspect this issue is likely resolved.

**Comment by bflad** [comment]
Closing due to lack of response. If there is still a problem in this area, please open a new issue. Thank you!
