### ISSUE TITLE
Set a naming convention for validation functions

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#298]
With more validation functions coming in (https://github.com/hashicorp/terraform-plugin-sdk/pull/294 https://github.com/hashicorp/terraform-plugin-sdk/pull/296 ) it makes sense to think about defining some conventions around the names and perhaps a hierarchy.

Ideally the convention should be easy enough to understand that it is obvious for newcomers where does a new validation function go and what it should be called.

--- 

### Ideas

 - move functions under `helper/validation/<type>`, e.g. `helper/validation/string`, `helper/validation/int` etc. - that would allow us to omit types from the function names themselves
 - it is a common convention in many languages and codebases to prefix functions that have "boolean outcome" with `Is` (e.g. `IsEmpty`, `IsWhiteSpace`). Our functions do not actually return `bool`, but technically have boolean-ish outcome (validation will pass or not, but may return warnings). We should discuss whether it makes sense to adopt this convention.
 - Until we have a better story around negation of validation function our convention has to account for dedicated negated versions of functions. e.g. `IsUUID` vs `IsNotUUID`, or `IsValidUUID` vs `IsNotValidUUID`. i.e. the function name should communicate whether it's positive or negative validation.

I'm not setting any of these proposal to stone yet, but rather creating this issue as a space for discussion about it.

**Comment by bflad** [comment]
Aye, if I recall, there was some efforts to do this as part of the version 2 major update. However, we do not intend to further extend these validation functions for _this_ SDK and instead we will focus on creating validation naming conventions for [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework) (potentially not including them in the SDK codebase itself). A good place to track that discussion would be https://github.com/hashicorp/terraform-plugin-framework/issues/240. 👍
