### ISSUE TITLE
Re-wire diagnostic locations to testing framework

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#3]
This is an example of a test failure after upgrading SDK to 0.12:

```
=== RUN   TestAccPanosEthernetInterface_basic
--- FAIL: TestAccPanosEthernetInterface_basic (2.68s)
    testing.go:568: Step 0 error: errors during apply:
        
        Error:  ethernet1/8 'ethernet1/8' is not a valid reference
        
          on /opt/teamcity-agent/temp/buildTmp/tf-test673682631/main.tf line 2:
          (source code not available)

```

Where it's clear that we can do much better job in providing context - i.e. where that error comes from.

**Comment by paddycarver** [comment]
I'm going to close this out, as our switch to binary testing (I believe) resolved this issue. If people are still encountering this problem, please feel free to open a new issue with more details.
