### ISSUE TITLE
Documented handling of inaccurate plans doesn't seem to work?

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform-plugin-sdk#305]
### SDK version

```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.5.0"
}
```

### Relevant provider source code

See examples in: https://discuss.hashicorp.com/t/handling-innacurate-plans-with-the-plugin-sdk/4184

```go
	"configuration": {
		Type:             schema.TypeString,
		Required:         true,
		DiffSuppressFunc: suppressEquivalentConfigurationDiffs,
	},
},
CustomizeDiff: customdiff.ComputedIf("configuration", func(diff *schema.ResourceDiff, meta interface{}) bool {
	return diff.HasChange("configuration")
}),
```

### Expected Behavior
Following the documented guide for 0.12 compatibility on handling inaccurate plans: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#inaccurate-plans
```go
CustomizeDiff: customdiff.ComputedIf("version", func(d *schema.ResourceDiff, meta interface{}) bool {
        return d.HasChange("content") || d.HasChange("content_type")
})
```

### Actual Behavior
Apply a customdiff to handle a TypeString with an EOF string which is interpolated, which produces the inaccurate plan

### Steps to Reproduce
- Apply `customdiff.ComputedIf` to `TypeString` field
- Set field with EOF containing interpolation
- Error: Provider produced inconsistent final plan

### References
https://discuss.hashicorp.com/t/handling-innacurate-plans-with-the-plugin-sdk/4184

**Comment by bflad** [comment]
Hey @iwarapter 👋  Is this still an issue for you? If so, does enabling the [`Schema.DiffSuppressOnRefresh`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.DiffSuppressOnRefresh) field on the attribute (available in v2.11.0) and removing the `CustomizeDiff` help your situation?

**Comment by iwarapter** [comment]
Hey @bflad thanks for getting back on this - went and checked the relevant resource and I cant reproduce the issue at all (without even upgrading or adding the suppress on refresh). I suspect this may have been something dumb in my original diff suppress func so feel to close this.

**Comment by bflad** [comment]
No worries, @iwarapter 👍  This stuff is fairly complicated to implement and troubleshoot. I'm going to close this issue out for now, but please don't hesitate to reach out if you are able to reproduce it again so we can take a fresh look. 😄
