### ISSUE TITLE
Deprecate (helper/schema.ResourceData).Partial and (helper/schema.ResourceData).SetPartial

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#312]
### SDK version

```
v1.6.0
```

### Relevant provider source code

```go
func exampleThingUpdate(d *schema.ResourceData, meta interface{}) error {
	// ...

	d.Partial(true)

	if d.HasChange("widget") {
		// ... update widget
		d.SetPartial("widget")
	}

	d.Partial(false)

	// ...
}
```

### Expected Behavior

That coding `d.Partial()` and `d.SetPartial()` into the update logic is beneficial.

### Actual Behavior

Their usage is only beneficial in very small edge cases, e.g. when those attributes are not refreshed on the next run after an error occurs (Terraform is called with `-refresh=false`). As another side effect, only the configuration value is passed through into the state, not the potentially different API result after re-read, which could be incorrect.

Most resources should already be coded to perform a full refresh of all possible attribute values for drift detection, so partial state updates would (and should 😄 ) be overwritten on the next Terraform run.

### Steps to Reproduce

1. `terraform apply` (with error)
1. `terraform apply -refresh=false` (not recommended)

### References

- https://github.com/bflad/tfproviderlint/issues/91

**Comment by paultyng** [comment]
I added the 2.0.0 milestone to this as I think we can deprecate in 1.x and then remove in the 2.x line.

**Comment by ewbankkit** [comment]
The _Writing Custom Providers_ chapter of **Extending Terraform** - 
https://www.terraform.io/docs/extend/writing-custom-providers.html#error-handling-amp-partial-state - should be updated to remove references to _partial mode_.

**Comment by paultyng** [comment]
Thanks @ewbankkit, I opened an issue over on the website to do so.
