### ISSUE TITLE
Drop "Removed" functionality from schema.Schema

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-plugin-sdk#320]
### SDK version

```
v1.4.0
```

### Relevant provider source code

```go
			"ip_allocation_policy": {
				Type:          schema.TypeList,
				MaxItems:      1,
				ForceNew:      true,
				Optional:      true,
				ConflictsWith: []string{"cluster_ipv4_cidr"},
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
	 						
						... some irrelevant attributes ... 

						"use_ip_aliases": {
							Type:     schema.TypeBool,
							Removed:  "This field is removed as of 3.0.0. If previously set to true, remove it from your config. If false, remove it.",
							Computed: true,
							Optional: true,
						},

						"create_subnetwork": {
							Type:     schema.TypeBool,
							Removed:  "This field is removed as of 3.0.0. Define an explicit google_compute_subnetwork and use subnetwork instead.",
							Computed: true,
							Optional: true,
						},

						"subnetwork_name": {
							Type:     schema.TypeString,
							Removed:  "This field is removed as of 3.0.0. Define an explicit google_compute_subnetwork and use subnetwork instead.",
							Computed: true,
							Optional: true,
						},

						"node_ipv4_cidr_block": {
							Type:     schema.TypeString,
							Removed:  "This field is removed as of 3.0.0. Define an explicit google_compute_subnetwork and use subnetwork instead.",
							Computed: true,
							Optional: true,
						},
					},
				},
			},
```

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "test" {
  name               = "tf-test-cc"
  location           = "us-central1-a"
  initial_node_count = 1
  ip_allocation_policy {
  }
}
```

### Actual Behavior
terraform apply wants to populate every field including the removed ones:
```
      + ip_allocation_policy {

			...

          + create_subnetwork             = (known after apply)
          + node_ipv4_cidr_block          = (known after apply)
          + subnetwork_name               = (known after apply)
          + use_ip_aliases                = (known after apply)
        }
```
The state shows the two boolean fields and not the string fields:
```
    ip_allocation_policy {

			...			

        create_subnetwork             = false
        use_ip_aliases                = false
    }
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform show`
### References

Seems like the solution proposed in https://github.com/hashicorp/terraform-plugin-sdk/issues/285#issuecomment-570594226 would stop this behavior.

https://github.com/terraform-providers/terraform-provider-google/issues/5586

**Comment by paultyng** [comment]
I think until the fix for #285 lands, you could potentially address this by not flagging these as computed?

**Comment by c2thorn** [comment]
Just tried that out, and unfortunately they still show in state. I think it might have something to do with the attributes being within a list? Other removed booleans that appear in the schema root are not showing in state.

I also tried setting the booleans to nil manually before setting them:

```
d.Set("ip_allocation_policy", flattenIPAllocationPolicy(cluster, d, config))
```
```
func flattenIPAllocationPolicy(c *containerBeta.Cluster, d *schema.ResourceData, config *Config) []map[string]interface{} {
		...
	return []map[string]interface{}{
		{
 				... 
			"use_ip_aliases":                nil,
			"create_subnetwork":             nil,
		},
	}
}
```

But this just makes them default to `false`. If I set these two to `true` they show up as `true`.

I'm unable to do something like 
```
d.Set("ip_allocation_policy.0.use_ip_aliases", nil)
```

because this returns
```
Error: ip_allocation_policy.0.use_ip_aliases: can only set full list
```

**Comment by paultyng** [comment]
Once we land v2 of the SDK we may be able to do some work on this. Unfortunately there is a bit of nuance in the `Removed` flag. Core doesn't actually have that concept, so the SDK is just emulating this by telling core these fields are part of the schema, but then erroring if they are supplied, so as far as core knows they are just normal schema fields, which is why it looks like this. Until we only have to support the new protocol though it will be hard to clean up, if its possible.

I think long term we will most likely remove this functionality (keeping deprecation though, so you can provide warnings up until the point of removal).

**Comment by paultyng** [comment]
Just a minor data point, I confirmed extra fields in state (not mentioned in schema) are silently ignored, so no need to track what the removed names should be.
