### ISSUE TITLE
Explicitly surface the concepts of blocks and attributes in the SDK

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-sdk#321]
Currently the SDK takes resources, schemas, and attributes and makes decisions on what should be blocks, attributes, and object types. This should explicitly be decided by the developer.

**Comment by paddycarver** [comment]
With the introduction of terraform-plugin-go, I think this is complete. I don't believe there are any plans to bring that functionality to helper/schema.
