### ISSUE TITLE
Better unknown value handling in Configure or PrepareProviderConfig

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform-plugin-sdk#331]
Terraform core allows providers to be configured referencing values that won't be known until apply, since in some cases providers don't need a complete configuration to create a plan. This provides some utility for providers expecting it, but the current SDK does not expose that a value is unknown, so defaults are often applied instead. This usually results in confusing errors from the provider, or even the provider being used with the incorrect configuration. 

The SDK could assist in the validation of unknown config values. The current protocol provides 2 calls that both may need to handle this situation:

 - `PrepareProviderConfig` is where the configuration defaults are inserted and the entire config is validated (akin to a "plan" for provider configuration). Unknown values currently pass through `PrepareProviderConfig` untouched.
 - `Configure` is where the configuration is applied to the provider, and this is where the "unknown" status of configuration values is lost.

**Comment by paultyng** [comment]
Related to #261

**Comment by apparentlymart** [comment]
There is some background discussion on this in hashicorp/terraform#24164, including a real example of an existing provider (`mysql`) attempting to operate in a partially-configured state.

**Comment by hazcod** [comment]
Additionally, I have the case where my `kubernetes` provider is using output values from `scaleway` provider. During plan & apply, the kubernetes provider will error out because of missing config..

**Comment by paddycarver** [comment]
With the release of terraform-plugin-go, this is now supported through that library. It is not supported through helper/schema yet, and I don't know that it ever will be, or even could be. Given that, I'm going to close this issue out, but people should feel free to comment here if this solution is unworkable for some reason.
