### ISSUE TITLE
helper/resource.TestCheckResourceAttrPair() Does Not Return Error If Comparing Self

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#334]
### SDK version

```
v1.7.0
```

### Relevant provider source code

```go
// Usually less obvious with variable usage
resource.TestCheckResourceAttrPair("example_thing.test", "attr", "example_thing.test", "attr"),
```

### Terraform Configuration Files

N/A -- can be covered via unit testing

### Expected Behavior

The acceptance testing function should return an error saying the same resource state values are being checked against each other, which will always pass. It is more likely the developer intended to check either different attributes in the same resource (seems like an odd case, but should be still allowed) or different resources (most likely; e.g. checking data source attribute versus resource attribute).

### Actual Behavior

No errors returned by `TestCheckResourceAttrPair()` and acceptance testing passes.

### Steps to Reproduce

```
TF_ACC=1 go test ./... -count=1 -run='ExampleThing_' -v
```

### References

- https://github.com/terraform-providers/terraform-provider-aws/pull/10932#discussion_r382574335

**Comment by paultyng** [comment]
Going to close this since the PR was merged in v2.
