### ISSUE TITLE
Docs: 'remember to flag RequiresRefresh mentioned below' is only mention of that attribute

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform-plugin-sdk#343]
### SDK version
master at time of writing, @ e664f5b78081fde148c4ea55a0e068dc62fb2274

### Relevant provider source code

n/a

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

`RequiresRefresh` attribute mentioned below.

### Actual Behavior

Not mentioned anywhere else in repo.

### Steps to Reproduce

Read docs? 🙂 

### References

https://github.com/hashicorp/terraform-plugin-sdk/blob/e664f5b78081fde148c4ea55a0e068dc62fb2274/helper/schema/resource.go#L147

https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/schema#Resource

**Comment by bflad** [comment]
I'm not sure why this issue didn't automatically close previously, but the current Go documentation does not include this errant statement. 👍
