### ISSUE TITLE
ValidateFunc should support validation of two fields dependent on each other that are defined in resource schema

### ISSUE THREAD

**Issue by saloneerege** [hashicorp/terraform-plugin-sdk#354]
### Current Terraform Version

```
Terraform v0.12.20
```

### Use-cases

I am writing a custom provider in which I have 2 fields defined in the schema namely : host_instance_type and storage_capacity. What is the best way to write a validation function for storage_capacity whose behavior is different for different host_instance_type ? In this the storage_capacity, must be specified only for a specific host_instance_type (say A). But storage_capacity should not be specified for a host_instance_type (say B).

### Attempted Solutions

Currently there seems to be no solution for performing such a validation in the terraform plan stage.  I can perform such a validation in terraform apply which might not be the most efficient way to do it.
### Proposal

ValidateFunc should support a method where two fields of the resource can be compared with a custom validate function.

**Comment by paultyng** [comment]
I think this is the same issue as #233 

Until a better way to support this is added, you do have a **Plan** time hook with the `CustomizeDiff` method. You can look at other providers who have utilized it to write more sophisticated multi-attribute validation at **Plan** time.
