### ISSUE TITLE
HasChange wrongly returns TRUE on nested shema.Set structures

### ISSUE THREAD

**Issue by obourdon** [hashicorp/terraform-plugin-sdk#361]
### SDK version

```
v1.7.0
```

### Relevant provider source code

When investigating [Terraform AWS provider issue #11059](https://github.com/terraform-providers/terraform-provider-aws/issues/11059) I came across some cases where nested schema.Set structures as the one [mentioned in the 2nd part of this entry](https://github.com/terraform-providers/terraform-provider-aws/issues/11059#issuecomment-599631533) produce unnecessary calls later down in the code

```go
...
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

HasChange should return false as entries are perfectly equivalent

### Actual Behavior

[This test](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_security_group.go#L695) returns true because
of reflect.DeepEqual which returns false when traversing Func(s)

### Steps to Reproduce

See aforementioned issue

### References

- [Terraform AWS provider issue #11059](https://github.com/terraform-providers/terraform-provider-aws/issues/11059)
- [The code I have implemented which prevents this](https://github.com/hashicorp/terraform-plugin-sdk/compare/master...obourdon:master)

**Comment by paddycarver** [comment]
I believe the merging of #362 resolves this. Please feel free to comment if that's not the case, and we can reopen this issue.
