### ISSUE TITLE
ImportStateVerify: true seems to verify all instances in state, not just referenced ResourceName

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-sdk#367]
I seemed to uncover this bug in working on the random provider. Will update here with additional repro's, just finishing up work over there and didn't want to forget it.

**Comment by paddycarver** [comment]
@paultyng any more info on this?

**Comment by bflad** [comment]
I'm curious if this is still an issue -- the last few v2.0.x releases have addressed some peculiarities with `ImportStateVerify` handling.

**Comment by bflad** [comment]
Closing this out -- if there are still problems, let's open a new issue with full details 👍
