### ISSUE TITLE
Cannot find packages

### ISSUE THREAD

**Issue by lordsaibat** [hashicorp/terraform-plugin-sdk#372]
### Expected Behavior
No errors when go get package.

### Actual Behavior
go get github.com/hashicorp/terraform-plugin-sdk/plugin
package github.com/hashicorp/hcl/v2: cannot find package "github.com/hashicorp/hcl/v2" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2 (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2 (from $GOPATH)
package github.com/hashicorp/hcl/v2/hcldec: cannot find package "github.com/hashicorp/hcl/v2/hcldec" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/hcldec (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2/hcldec (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclsyntax: cannot find package "github.com/hashicorp/hcl/v2/hclsyntax" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOPATH)
package github.com/hashicorp/hcl/v2/ext/typeexpr: cannot find package "github.com/hashicorp/hcl/v2/ext/typeexpr" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/ext/typeexpr (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2/ext/typeexpr (from $GOPATH)
package github.com/hashicorp/hcl/v2/gohcl: cannot find package "github.com/hashicorp/hcl/v2/gohcl" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/gohcl (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2/gohcl (from $GOPATH)
package github.com/hashicorp/hcl/v2/hclparse: cannot find package "github.com/hashicorp/hcl/v2/hclparse" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2/hclparse (from $GOPATH)
package github.com/hashicorp/hcl/v2/ext/dynblock: cannot find package "github.com/hashicorp/hcl/v2/ext/dynblock" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/v2/ext/dynblock (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/v2/ext/dynblock (from $GOPATH)

### Steps to Reproduce
go get github.com/hashicorp/terraform-plugin-sdk/plugin

**Comment by mikeletux** [comment]
Take a look into that:
https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k

You might be using the old $GOPATH approach.
Regards.

/Miguel

**Comment by paultyng** [comment]
When I run this in a clean directory, I get the following output:

```sh
$ go version
go version go1.14 linux/amd64
$ go clean --modcache
$ go get github.com/hashicorp/terraform-plugin-sdk/plugin
go: downloading github.com/hashicorp/terraform-plugin-sdk v1.9.0
go: found github.com/hashicorp/terraform-plugin-sdk/plugin in github.com/hashicorp/terraform-plugin-sdk v1.9.0
go: downloading github.com/hashicorp/go-plugin v1.0.1
go: downloading github.com/zclconf/go-cty v1.2.1
go: downloading github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f
go: downloading google.golang.org/grpc v1.27.1
go: downloading github.com/hashicorp/go-hclog v0.9.2
go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: downloading github.com/golang/protobuf v1.3.4
go: downloading github.com/mitchellh/cli v1.0.0
go: downloading github.com/mitchellh/go-testing-interface v1.0.0
go: downloading github.com/hashicorp/hcl/v2 v2.0.0
go: downloading github.com/hashicorp/terraform-svchost v0.0.0-20191011084731-65d371908596
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-getter v1.4.0
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/oklog/run v1.0.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/hashicorp/go-version v1.2.0
go: downloading github.com/apparentlymart/go-textseg v1.0.0
go: downloading github.com/hashicorp/go-safetemp v1.0.0
go: downloading github.com/posener/complete v1.2.1
go: downloading github.com/zclconf/go-cty-yaml v1.0.1
go: downloading github.com/mattn/go-isatty v0.0.5
go: downloading cloud.google.com/go v0.45.1
go: downloading github.com/vmihailenco/msgpack v4.0.1+incompatible
go: downloading github.com/mitchellh/reflectwalk v1.0.1
go: downloading github.com/aws/aws-sdk-go v1.25.3
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading google.golang.org/api v0.9.0
go: downloading google.golang.org/genproto v0.0.0-20200310143817-43be25429f5a
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/bgentry/speakeasy v0.1.0
go: downloading github.com/agext/levenshtein v1.2.2
go: downloading github.com/armon/go-radix v1.0.0
go: downloading golang.org/x/sys v0.0.0-20200302150141-5c8b2ff67527
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
go: downloading golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading google.golang.org/appengine v1.6.1
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/ulikunitz/xz v0.5.5
go: downloading github.com/apparentlymart/go-cidr v1.0.1
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading github.com/google/go-cmp v0.3.1
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading go.opencensus.io v0.22.0
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
```
