### ISSUE TITLE
d.Get() is always empty after importing a resource

### ISSUE THREAD

**Issue by remilapeyre** [hashicorp/terraform-plugin-sdk#375]
### SDK version
```
v1.0.0
```

### Use-cases

In the Consul provider we have a resource with the following schema:

```hcl
resource "consul_key_prefix" "myapp_config" {
  path_prefix = "myapp/config/"

  subkeys = {
    "database/name"     = "foo"
  }

  subkey {
    path  = "database/password"
    value = "bar"
    flags = 2
  }
}

```

`subkeys` is actually a shortcut for defining multiple `subkey` at once, with `flag` set to 0. When refreshing the keys, must must add each key either to `subkey` or `subkeys` based on the user configuration so the diff is made properly.

During the read after importing such resource the state always appears empty no matter the actual code. Is this on purpose?

This is a known issue as it's mentioned in https://github.com/hashicorp/terraform-plugin-sdk/issues/234:

> Calling d.Get() type calls in Read (which doesn’t work with import usually)

but it's not clear whether this may change in the future or not. If this is on purpose and will not change, I think I may be able to bypass the issue by using a custom diff function and being smarter but I would like to avoid this if possible.

Related issue: https://github.com/terraform-providers/terraform-provider-consul/pull/189#issuecomment-607936558

**Comment by bflad** [comment]
Hey @remilapeyre 👋  Sorry for the _super_ late reply here, but imported resources start with no state, only the identifier passed in via the Terraform CLI command. We have plans to potentially include any available configuration in the import request sent to providers but introducing that data where it is accessible via `(*ResourceData).Get()` in resource import functions is not likely to be implemented in _this_ SDK, unless it is determined to be very straightforward to implement. I'd recommend subscribing to https://github.com/hashicorp/terraform-plugin-framework/issues/220 for further updates on this topic for now. 👍
