### ISSUE TITLE
Allow custom deprecation warnings to be thrown

### ISSUE THREAD

**Issue by chrisst** [hashicorp/terraform-plugin-sdk#376]
### Use-cases

Currently deprecation warnings are only able to be thrown if a Schema field is being removed but there are often discrete values of a given field that are no longer going to be valid but many other values would still be.
One such example is an API that accepts an enum that will have certain options deprecated soon and I would like to throw a deprecation warning for any configs that have that enum value still set. 
Another example is when a feature was managed as part of a string map but we want to create a new field to manage that feature outside of the map. I would like to throw a deprecation warning for users that are still using the map to manage this feature and transition them to using the new field. Concrete example of this in https://github.com/terraform-providers/terraform-provider-google/pull/5873

### Proposal

This could be implemented as a schema level field such as DeprecatedIf that could take a method which would allow custom logic to determine if the value provided should emit a warning. It could also be addressed with more control over logging from the provider but I wanted to add this as a feature request separate from the logging issue in case there would be additional features built into the deprecation logic that this could be added into.

**Comment by chrisst** [comment]
Being able to surface the information to the user is the primary use case, so being able to throw warning would be enough. But since the Deprecated property is a distinct part of the interface right now I wasn't sure if there was a plan for building more functionality around it or if it was to remain a glorified helper for generating warnings.

**Comment by paultyng** [comment]
It is not used for anything in core currently (although we have begun surfacing it in the protocol for the Language Server). But yes, its just informational for users, not for any dependent functionality.
