### ISSUE TITLE
Provider configuration not available during testing

### ISSUE THREAD

**Issue by NickLarsenNZ** [hashicorp/terraform-plugin-sdk#387]
### SDK version

```
1.9.1
```

### Relevant provider source code

**dummy/provider_test.go** _supplying a provider configuration_

```go
func init() {
	testAccProvider = Provider().(*schema.Provider)

	raw := map[string]interface{}{
		"some_block": map[string]interface{}{
			"some_key": "some_value",
		},
	}

	err := testAccProvider.Configure(terraform.NewResourceConfigRaw(raw))
	if err != nil {
		fmt.Printf("provider config error: %s", err)
	}

	testAccProviders = map[string]terraform.ResourceProvider{
		"dummy": testAccProvider,
	}
}
```

### Terraform Configuration Files

```hcl
provider "dummy" {
  some_block = {
    some_key = "blah"
  }
}

resource "dummy_file" "d" {
  path       = "./thefile.txt"
  firstline  = "alpha"
  secondline = "bravo"
}
```

### Debug Output

https://gist.github.com/NickLarsenNZ/7546b4c1dfb14bc8b7eed9b233341e9d

### Expected Behavior

During testing, the provider configuration should be available as it is during normal operation.
In this case I use a value from the provider config inside a resource. 
- This works fine during apply (with the provider config in HCL)
- but not during testing (with a raw provider config).

### Actual Behavior

- The test fails because the value from the raw provider configuration does not appear in the resource (in this case a file).
- `terraform apply` works as expected.

### Steps to Reproduce

1. Clone the example code: https://github.com/NickLarsenNZ/terraform-provider-dummy
2. Run the failing tests
   ```sh
   TF_LOG=trace go test ./...
   ```
   Notice the lines:
   ```log
   2020/04/15 13:13:22 [TRACE] buildProviderConfig for provider.dummy: no configuration at all
   2020/04/15 13:13:22 [TRACE] GRPCProvider: GetSchema
   2020/04/15 13:13:22 [TRACE] GRPCProvider: Configure
   ---> some_block wasn't defined
   ```
   Also notice the empty value in the actual resource contents:
   ```log
        got:
        alpha
        bravo
        some_key: 
        
        
        expected:
        alpha
        bravo
        some_key: some_value
   ```
3. Compare with the working example configuraton
   - Build and install the provider
     ```sh
     mkdir -p ~/.terraform.d/plugins
     go build -o ~/.terraform.d/plugins/terraform-provider-dummy_v0.0.0
     ```
   - Terraform Apply
     ```sh
     cd example/
     terraform init
     TF_LOG=trace terraform apply -auto-approve
     ```
     Notice the line:
     ```log
     2020/04/15 13:15:05 [TRACE] buildProviderConfig for provider.dummy: using explicit config only
     ```

     Also notice the correct file contents in `thefile.txt`:
     ```log
     alpha
     bravo
     some_key: blah

     ```

### References

- (Empty) Plugin SDK Community Discussion: https://discuss.hashicorp.com/t/provider-configuration-empty-during-acceptance-testing/7183

**Comment by NickLarsenNZ** [comment]
@evanphx @topfunky  @hornbeck  @dylanegan 
Apologies for spamming, just wasn't sure if this hasn't been seen yet, and if you're supposed to tag someone.

**Comment by paultyng** [comment]
Is this using the new binary testing driver or the legacy testing driver? It looks like its the legacy testing driver but unsure.

We typically recommend using environment variables for configuration of the provider and not supplying it in config unless you specifically need to test aspects of the provider configuration. I can point you to some examples in other repos, which is probably the best way to see how others do this.

Part of the reason we introduced the new binary testing driver is because the old testing model diverged from the experience of running the CLI in a few significant ways and provider instantiation is included in that list.

**Comment by NickLarsenNZ** [comment]
Thanks @paultyng, I'm not sure if I'm using the new binary testing driver (I hadn't heard of it).

If you could point me to some examples of testing provider configs that would be great.

In the past I have tested based on environment variables as is common, however in this case I want to check for the existence of config blocks. I think this is a single line check, as opposed to checking the existance of any environment variables mapping to the attributes within the block. At least to me this feels like a more natural test case.

**Comment by NickLarsenNZ** [comment]
@paultyng just wondering if you can link me to an example using the binary testing driver?

**Comment by paddycarver** [comment]
If you're using v2.0.0 or higher, the binary acceptance testing driver is the _only_ driver available. So you're using it by default on version 2.0.0 or higher of the SDK. For v1.7.0 and higher, #262 has more details.

**Comment by techBeck03** [comment]
> Thanks @paultyng, I'm not sure if I'm using the new binary testing driver (I hadn't heard of it).
> 
> If you could point me to some examples of testing provider configs that would be great.
> 
> In the past I have tested based on environment variables as is common, however in this case I want to check for the existence of config blocks. I think this is a single line check, as opposed to checking the existance of any environment variables mapping to the attributes within the block. At least to me this feels like a more natural test case.

I can't find where these reference links were posted.  Did anyone find a reference repo where an example was given for configuring a provider outside of environment variables?  I've tried using the `Provider.Configure` function but the configured provider properties don't seem to be set in my acceptance tests.

Thanks!
