### ISSUE TITLE
Terraform Apply (which invokes create then read) and Terraform Refresh (which just invokes read) result in different .tfstate outputs

### ISSUE THREAD

**Issue by dcaponi** [hashicorp/terraform-plugin-sdk#392]
### Description
When I create a resource, I do a subsequent call to a `read` function that requests the created resource by id from my API so I can capture the state of my resource in a local `.tfstate` file that includes any fields not explicitly set by a user, but set by the API. I call the Set function with no errors being returned, and I pass in the the same input on `terraform apply` (which creates/updates then invokes the read to update local .tfstate) and `terraform refresh` (which also invokes read) but each results in different .tfstate output between the two. 

### SDK version

```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.9.1"
}
```

### Relevant provider source code

schema (some fields omitted for brevity)
```go
func AppSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": &schema.Schema{
			Type:     schema.TypeString,
			Required: true,
		},
                "connector_id": &schema.Schema{
			Type:     schema.TypeInt,
			Required: true,
		},
                 "provisioning": &schema.Schema{
			Type:     schema.TypeSet,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
		                    "enabled": &schema.Schema{
			                Type:     schema.TypeBool,
			                Required: true,
		                    },
	                        },
			 },
		},
        }
}
```

resource read function - only first `log.Println("")` statement is observed
```go
func appCreate(d *schema.ResourceData, m interface{}) error {
  // build app struct and api call to create app (omitted for brevity)

  d.SetId(fmt.Sprintf("%d", *(app.ID)))
  return appRead(d, m)
}

func appRead(d *schema.ResourceData, m interface{}) error {
  // api call to get app (omitted for brevity)

  d.SetId(fmt.Sprintf("%d", *(app.ID)))
  d.Set("name", app.Name)

  // set other fields omitted for brevity

  log.Println("[READ] Setting Provisioning")
  if err := d.Set("provisioning", provisioning.Flatten(app.Provisioning)); err != nil{
    log.Printf("[ERROR] There was a problem flattening provisioning!")
  }
  return nil
}
```

output from `provisioning.Flatten(app.Provisioning)` (observed in both apply and refresh)
```
[map[enabled:false]] 
```

### Terraform Configuration Files

I do not explicitly set provisioning here, although it can be set. The API state is set to a default if no choice is made, and I expect on read (called after create) for the tfstate to be updated to reflect what is actually in the API response

```hcl
resource onelogin_apps basic {
  connector_id = 20938
  name =  "Form-Based fff"
}
```

### Debug Output

[debug output](https://gist.github.com/dcaponi/73d1b7a7c2268222bdc5bdcc0db98a14)
(Line 929 is where the loggers in the above code snippet log out)

### Expected Behavior

Expected .tfstate output for "provisioning" after terraform apply
```json
"provisioning": [
  {
    "enabled": false
  }
]
```

### Actual Behavior

Actual .tfstate output for "provisioning" after terraform apply
```json
"provisioning": []
```

**Comment by paddycarver** [comment]
Do you happen to know what the API response looks like that produces that output? In Read it looks like you're making an API call to read back from the API, I'd be interested in seeing if there are any differences in it that correlate to the different states.

**Comment by dcaponi** [comment]
Read Called After `terraform apply` results in this response
```
{
   "id":1021833,
   "name":"Form-Based",
   "visible":true,
   "description":"",
   "notes":"",
   "icon_url":"https://cdn-shadow.onlgn.net/images/icons/square/5558229540474713/old_original.png?1427294311",
   "auth_method":0,
   "allow_assumed_signin":false,
   "connector_id":20938, 
   "created_at":"2020-04-20T18:46:55Z",
   "updated_at":"2020-04-20T18:46:55Z",
   "provisioning":{
      "enabled":false
   },
   "sso":{
      "certificate":null
   },
   "configuration":{},
   "parameters":{
      "email":{
         "id":36773,
         "label":"Username",
         "skip_if_blank":false,
         "provisioned_entitlements":false
      },
      "password":{
         "id":36774,
         "label":"Password",
         "skip_if_blank":false,
         "provisioned_entitlements":false
      }
   },
   "role_ids":[]
}```

Read called after `terraform refresh` results in this response
```
{
   "id":1021833,
   "name":"Form-Based fff",
   "visible":true,
   "description":"",
   "notes":"",
   "icon_url":"https://cdn-shadow.onlgn.net/images/icons/square/5558229540474713/old_original.png?1427294311",
   "auth_method":0,
   "allow_assumed_signin":false,
   "connector_id":20938,
   "created_at":"2020-04-20T18:46:55Z",
   "updated_at":"2020-04-20T18:46:55Z",
   "provisioning":{
      "enabled":false
   },
   "sso":{
      "certificate":null
   },
   "configuration":{},
   "parameters":{
      "email":{
         "id":36773,
         "label":"Username",
         "skip_if_blank":false,
         "provisioned_entitlements":false
      },
      "password":{
         "id":36774,
         "label":"Password",
         "skip_if_blank":false,
         "provisioned_entitlements":false
      }
   },
   "role_ids":[ ]
}
```

**Comment by dcaponi** [comment]
Hey everyone, is there any update around this issue? I'd love to pass the word to my team so we know whether we need to start looking into alternatives for updating `.tfstate` or not.

**Comment by paultyng** [comment]
What does the code for `provisioning.Flatten` look like? Is there a repo we could look at it? It's hard to reason about what is happening here without the code.

**Comment by paultyng** [comment]
You mention `parameters` fields don't make it to the state, but I don't see them in the schema?

**Comment by dcaponi** [comment]
Right sorry, I corrected my last response. The same problem happens in both `parameters` and `provisioning` (I chose to focus on provisioning since its a smaller instance of the problem). I'm working with my security team to get our repo checked out before making it public. Let me get back to you on the other question.

**Comment by dcaponi** [comment]
For now, this is what `provisioning.Flatten` does

```
func Flatten(prov *models.AppProvisioning) []map[string]interface{} {
	return []map[string]interface{}{
		map[string]interface{}{
			"enabled": *prov.Enabled,
		},
	}
}
```

**Comment by dcaponi** [comment]
@paultyng here is the public repo. The branch Im working on is called `feature/saml-app-resource`
https://github.com/onelogin/onelogin-terraform-provider/tree/feature/saml-app-resource

**Comment by paultyng** [comment]
I see a couple issues at first, it needs to be a slice of interface with the values inside of it I believe. Also it should probably just be `TypeList` since its just a single item. For sets, you would probably need to use `schema.Set`.

**Comment by paultyng** [comment]
Something like this.

```go
func Flatten(prov *models.AppProvisioning) []interface{} {
	return []interface{}{
		map[string]interface{}{
			"enabled": *prov.Enabled,
		},
	}
}
```

Here is an example in the AWS provider that also has `MaxItems: 1`: https://github.com/terraform-providers/terraform-provider-aws/blob/64cc781a9d5d962f8718b7d87fe40cad7d055953/aws/resource_aws_kinesis_analytics_application.go#L1325

**Comment by dcaponi** [comment]
Thank you for the tip! I'll plug this in and see what it does.

Curious though; If thats it, then why does `terraform refresh` update the `.tfstate` with no problems... wouldn't an issue here mean both `terraform apply` and `terraform refresh` fail to update `.tfstate` correctly?

**Comment by dcaponi** [comment]
Update: After returning an array of interfaces and changing my schema to a TypeList, I still observe the same behavior (i.e. `terrafrom apply` puts `"provisioning": []` in `tfstate` and `terraform refresh` puts the expected value `"provisioning": [{ "enabled": false }]` in `tfstate`)

**Comment by paultyng** [comment]
And no errors output in the trace log when you enable that? Do you have the trace output handy?

Regarding why they are different, I can't say for sure without digging in fully, but my guess is that when you are doing a plan/apply, there is a lot more sensitivity to the type system, because the apply'd information has to match the plan information much more closely, vs during refresh, there may be a bit more relaxed evaluation of the typing. This is a legacy holdover of the old 0.11 type system I'd imagine.

**Comment by paultyng** [comment]
You may also want to utilize this environment variable: `TF_SCHEMA_PANIC_ON_ERROR` (can set it to any non-empty string, ie `1`). It will cause typically ignored errors to cause a panic, and can help pinpoint issues in the type usage sometimes.

**Comment by dcaponi** [comment]
Here's what I did:

```	log.Printf("Attempting to set provisioning %s", provisioning.Flatten(app.Provisioning))
        // prints out Attempting to set provisioning [map[enabled:%!s(bool=false)]] in both apply and refresh

	if err := d.Set("provisioning", provisioning.Flatten(app.Provisioning)); err != nil {
		return fmt.Errorf("Error setting parameters: %s", err) // no error here
	}
```

> This is a legacy holdover of the old 0.11 type system I'd imagine.
does that imply that this needs to get updated? I have the most up to date plugin (1.9.1)

> Do you have the trace output handy?

[tf plan to execute (yes/no)](https://gist.github.com/dcaponi/97bc901dc25dfe7ef6a842de59ea79d8)

[tf apply output](https://gist.github.com/dcaponi/4a6969686b616fffec99116724a49e18)

[tf refresh output](https://gist.github.com/dcaponi/12084d3b8fa8160a4cec56ef0badc6ab)

**Comment by dcaponi** [comment]
One thing I did notice, and I don't know if this is part of the problem, is that the nested fields (provisioning, parameters etc...) are neither marked as `computed` in the schema, nor are they `required`. 

I cant mark these fields as computed since that removes the ability to set the field. e.g. I cant mark `provisioning` as computed because, although it defaults to false from the API, a user may want to set it to `enabled: true` Marking this `computed` means users can't override the default provisioning value, and marking as `required` means users cant accept the API default.

Do you think this is part of it? If so, is there some way to mark a field as `computed_unless_specified` or something like that? What if I have a `typeSet` or a `typeList` that has some items specified by a user and some items set by the API?

**Comment by dcaponi** [comment]
I also noticed this warning because I wasn't setting some boolean fields that "may cause weird downstream errors"

```
2020/04/29 10:58:07 [WARN] Provider "registry.terraform.io/-/onelogin" produced an invalid plan for onelogin_apps.basic, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .visible: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .allow_assumed_signin: planned value cty.False does not match config value cty.NullVal(cty.Bool)
```

however on correcting that (by setting those fields) and making that warning go away, that still did not result in my non-primitive fields being set in `.tfstate`

**Comment by dcaponi** [comment]
Friendly poke: Did you guys find anything that may be causing the difference there?

I managed to get around this by changing all my `typeSet`s to `typeList`s as this is not reproduced when using the `typeList` implementation, so maybe something is up with `typeSet` in particular.

I'm still really curious what the issue was so if you do find it and are willing to share, I'd be happy to hear :)

**Comment by rick-masters** [comment]
@dcaponi
"I cant mark these fields as computed since that removes the ability to set the field."

Why not set the field as both Optional and Computed with no Default? My understanding is that allows a user to set it and in that case the computed value becomes whatever they configured.

**Comment by dcaponi** [comment]
Hey @rick-masters thanks for the update I think I stumbled on that at some point in June or so. I _think_ the issue here can be marked as resolved
