### ISSUE TITLE
TypeSet persists the incorrect value to state in datasource

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-plugin-sdk#395]
### SDK version

```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.4.0"

```

### Relevant provider source code

```go
func dataSourceGoogleContainerCluster() *schema.Resource {
	// Generate datasource schema from resource
	dsSchema := datasourceSchemaFromResourceSchema(resourceContainerCluster().Schema)

	// Set 'Required' schema elements
	addRequiredFieldsToSchema(dsSchema, "name")

	// Set 'Optional' schema elements
	addOptionalFieldsToSchema(dsSchema, "project", "zone", "region", "location")

	return &schema.Resource{
		Read:   datasourceContainerClusterRead,
		Schema: dsSchema,
	}
}

func datasourceContainerClusterRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	clusterName := d.Get("name").(string)

	location, err := getLocation(d, config)
	if err != nil {
		return err
	}

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	d.SetId(containerClusterFullName(project, location, clusterName))

	return resourceContainerClusterRead(d, meta)
}
```

Notably, the datasource and resource share a Read method and the schema for the datasource is based off of the resource one (with transformations to field properties to make it all generally output-only).

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "with_private_cluster" {
  name               = "manc"
  location           = "us-central1-a"
  initial_node_count = 1

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block = "10.0.0.0/16"
      display_name = "INTERNAL"
    }
    cidr_blocks {
      cidr_block = "10.0.0.0/18"
      display_name = "EXTERNAL"
    }
  }
}

resource "google_container_node_pool" "np" {
  name               = "manc"
  location           = "us-central1-a"
  cluster            = google_container_cluster.with_private_cluster.name
  initial_node_count = 1
}

data "google_container_cluster" "data" {
  name = "manc"
  location = "us-central1-a"
}
```

### Debug Output

Nothing notable- I played around with extra logging, and we're calling `d.Set` with the value I expect and the schema looks as expected.

### Expected Behavior

The datasource returns both `cidr_blocks` values. Or, at least, an error if we're trying to set an invalid value.

### Actual Behavior

The datasource returns a single `cidr_blocks` value in the datasource (the resource returns both, including during import). From `terraform show`:

```
  "master_authorized_networks_config" = [
    {
      "cidr_blocks" = [
        {
          "cidr_block" = "73.35.171.195/32"
          "display_name" = "net2"
        },
      ]
    },
  ]
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* [Original Issue](https://github.com/terraform-providers/terraform-provider-google/issues/6128)

**Comment by bflad** [comment]
Hi @rileykarson 👋  Can you see if https://github.com/hashicorp/terraform-plugin-sdk/pull/197, released in v2.0.0 of the Terraform AWS Provider, fixes this issue?

**Comment by rileykarson** [comment]
I can test once the the google provider has updated to SDK v2: https://github.com/hashicorp/terraform-provider-google/issues/6976

**Comment by rileykarson** [comment]
Seems to be resolved!

```
    master_authorized_networks_config = [
        {
            cidr_blocks = [
                {
                    cidr_block   = "10.0.0.0/16"
                    display_name = "INTERNAL"
                },
                {
                    cidr_block   = "10.0.0.0/18"
                    display_name = "EXTERNAL"
                },
            ]
        },
    ]
```

**Comment by bflad** [comment]
Hooray! 🎉  Closing this out then. If there does happen to be any lingering issue here, we can track in a new issue and take a fresh look. 👍
