### ISSUE TITLE
Add resource.TestCheckSetAttr

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#4]
Allow easier testing of values in sets.

Basically bring this https://github.com/terraform-providers/terraform-provider-aws/blob/09e815670ecdb2872b0acf9e68aad6e40df7a4f3/aws/resource_aws_waf_rule_test.go#L230-L234
into the SDK.

**Comment by bflad** [comment]
Recent versions of the `helper/resource` package include new `TypeSet` check functions:

- [`TestCheckTypeSetElemAttr`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckTypeSetElemAttr)
- [`TestCheckTypeSetElemAttrPair`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckTypeSetElemAttrPair)
- [`TestCheckTypeSetElemNestedAttrs`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckTypeSetElemNestedAttrs)

These can be used to verify values inside `TypeSet` attributes by replacing the set element integer/hash with a `*`. They are also documented in the [acceptance testing documentation](https://www.terraform.io/plugin/sdkv2/testing/acceptance-tests/teststep#builtin-check-functions). If you have questions about usage, please feel free to reach out in the [HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/31). 👍
