### ISSUE TITLE
Remove provisioners from protobuf def

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#408]
Regenerate `tfplugin5.proto` on both `master` and `v1-maint`, as the `Provisioner` definition has snuck back in by accident.

**Comment by paultyng** [comment]
I think we should just leave it alone since it matches the core .proto file, unless there is any easy way to exclude the types in generation on the command line.

**Comment by paddycarver** [comment]
I believe we've decided not to include this in 2.0.0, to retain parity between the core and SDK protobuf files. If someone believes we have not reached consensus on this, please reopen the issue.
