### ISSUE TITLE
auto-subtracting timeouts

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-plugin-sdk#412]
### SDK version

```
v1.4.0
```

### Use-cases

Many resources allow users to set a configurable timeout, but then the provider developer has to figure out what to do with that piece of information. If a method sends multiple API requests, we typically send the configured timeout value exactly for each request instead of actually taking into account how long the request took. This means that if a method has N requests in it and the user set their timeout as T, we could end up taking up N*T time to apply their config instead of T.

For a more concrete example, see `google_container_cluster`: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_container_cluster.go, where the Update() function could end up taking more than 20x as long as the configured timeout.

This isn't super important- I don't think users have ever really noticed, or cared. However, it still feels really awkward, and would be nice to have fixed eventually.

### Attempted Solutions

We could totally do it resource-by-resource by timing how long things took and subtracting that from the total allowed timeout, but I think people would forget to do it. An SDK solution would make it much easier to be consistent across resources.

### Proposal

There might be a way to do this completely outside of the provider code at all by having a timeout on whatever calls into the provider CRUD methods.
If that's scary (or not flexible enough), you could also make the call to d.Timeout auto-subtract so it returns a smaller number each time it's called (or make a new function that did something similar).

**Comment by paultyng** [comment]
v2 already applies the timeout automatically to each context if you opt in to the new context aware methods: https://github.com/hashicorp/terraform-plugin-sdk/blob/ac1c09290269b998204e08e90e6b2d7d376deb0d/helper/schema/resource.go#L267-L278

So I think this should be covered? You can just keep using the existing context?

**Comment by danawillow** [comment]
Oh that's so exciting! Closing this out, looking forward to upgrading :)
