### ISSUE TITLE
Allow multiple CHANGELOG links per line

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#429]
The changelog for v1.11.0 is improperly formatted, because there were three PR links in one line:
https://github.com/hashicorp/terraform-plugin-sdk/blob/v1-maint/CHANGELOG.md

Update the `sed` command in `changelog_links.sh` to handle this properly.

**Comment by paultyng** [comment]
Do we need to use link replacement? Does the README get the standard enhancement for GitHub markdown where you can just type `#400`: #400
