### ISSUE TITLE
Support rsa public keys for encryption

### ISSUE THREAD

**Issue by bernata** [hashicorp/terraform-plugin-sdk#432]
### SDK version
```
```

### Use-cases
I would like to use the aws provider to encrypt a iam user aws secret key to an rsa public key and output the result as an `encrypted_secret`. Currently, pgp is supported; however, it is quite cumbersome to take an rsa public key and convert to a pgp key.

### Attempted Solutions
I tried the following solutions:
1. Create a self-signed certificate and import using `gpgsm`. The problem is I couldn't export the public key out of `gpgpsm` in armored ascii format.
1. Use a tool like "monkeysphere" which has a `pem2pgp` command. This command always failed to parse the pem file.
1. Write some command line tool to create a pgp key from a rsa public key. I stopped going through this path when I had to dig deep into pgp spec. I felt it was overkill to require this for my purpose.

### Proposal
The aws secret key is quite short; and so using rsa oaep encryption would be a straightforward change. I created a sample PR in the helper code:
https://github.com/hashicorp/terraform-plugin-sdk/pull/428

I haven't created a PR in the terraform aws provider, but I will do that. But the idea is the terraform will look like:
```terraform
resource "aws_iam_access_key" "application-access-key" {
  user = aws_iam_user.application-user.name
  rsa_key = <<EOF
----- BEGIN PUBLIC KEY -----
....
----- END PUBLIC KEY -----
EOF
}

resource "local_file" "credentials-application" {
    filename = "${path.module}/credentials"
    file_permission="0600"

    content = <<EOF
[application-user]
aws_access_key_id = ${aws_iam_access_key.application-access-key.id}
aws_secret_access_key = ${aws_iam_access_key.application-access-key.encrypted_secret}

EOF
}
```
I could have the encryption code in the terraform provider as well; but thought it makes sense to put it together with the pgp encryption code.

### References
- [#9900](https://github.com/terraform-providers/terraform-provider-aws/issues/9900) Asking about an alternative to pgp. Suggested using keybase w/ saltpack.
- [#11053](https://github.com/terraform-providers/terraform-provider-aws/issues/11053) Asking about using aws kms keys for encryption.

**Comment by paddycarver** [comment]
Are you attempting to encrypt values to avoid storing sensitive information in state? I'm sorry, I'm not 100% clear on the goal here.

**Comment by bernata** [comment]
> Are you attempting to encrypt values to avoid storing sensitive information in state? I'm sorry, I'm not 100% clear on the goal here.

Yes. Sorry, I don't think I made that clear in my original post. The aws secret key created by the `aws_iam_access_key` resource is sensitive. Today, terraform supports encrypting the secret key to a pgp key, but as I mentioned, pgp keys are not easy to translate from openssl style pem encoded keys.

**Comment by paddycarver** [comment]
That strategy is [officially discouraged](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state) today; it was an experiment that we tried but don't feel was successful.

I'm going to close this out, as we'd prefer not to add this functionality to the SDK at this time, as it may give the impression that discouraged patterns are recommended.

**Comment by bernata** [comment]
> That strategy is [officially discouraged](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state) today; it was an experiment that we tried but don't feel was successful.
> 
> I'm going to close this out, as we'd prefer not to add this functionality to the SDK at this time, as it may give the impression that discouraged patterns are recommended.

Thanks @paddycarver  for the info. While I understand that using backend encryption solves many scenarios. I think that using pgp/rsa keys to encrypt aws generated secrets is a scenario that terraform should not overlook. I added more specific comments about the scenario on the (issue)[https://github.com/hashicorp/terraform/issues/516#issuecomment-622583499] where it is being discussed. I do hope you will all reconsider.

**Comment by paddycarver** [comment]
Thanks for weighing in on the issue @bernata! I think the more likely outcome is going to be a more comprehensive solution from core and/or the protocol, because at the moment using those encryption techniques breaks some of the constraints Terraform needs to operate safely.

So I think it's less a situation of reconsidering, and more a situation of figuring out how to support that use case safely. Hope that clarifies things a little, and helps explain why we're being aggressive about discouraging this.

**Comment by bernata** [comment]
Thanks @paddycarver I look forward to see what the outcome will be. Is there any estimate for when a plan will be formulated? If there is something you can share, then please let me know.

**Comment by paultyng** [comment]
Hey @bernata, to give you a better idea of timing, better sensitive value handling in core is not being looked at for the next minor version (0.13), but it is on deck to be looked at seriously after that.
