### ISSUE TITLE
Better handling of schema panic on error

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-sdk#455]
This is a follow-on to #451 

We may be able to plumb a `testing.T` down to the `ResourceData` (perhaps via `context.Context`) and a gRPC interceptor or something. If it were available, instead of a `panic` the SDK could simply `t.Errorf` but continue execution.

Considering time and cost of acc test runs, this would probably be a more user friendly approach.

**Comment by bflad** [comment]
Unofficially since terraform-plugin-framework v1.0.0, there are no more plans for major refactoring of `helper/schema`, so closing this out. Framework based providers do not have this issue.
