### ISSUE TITLE
Diagnostic attribute path not surfaced in error message

### ISSUE THREAD

**Issue by jta** [hashicorp/terraform-plugin-sdk#456]
### SDK version
```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk/v2",
  "Version": "v2.0.0-rc.1"
}
```

### Relevant provider source code

Resource with the following schema:
```go
        Schema: map[string]*schema.Schema{
            "nested": {
                Type:     schema.TypeList,
                Required: true,
                Elem: &schema.Resource{
                    Schema: map[string]*schema.Schema{
                        "attr": {
                            Type:     schema.TypeString,
                            Required: true,
                        },
                    },
                },
            },
       }, 
```

### Terraform Configuration Files

```hcl
resource "custom" "test" {
  // "nested" is required, but not provided
}
```

### Expected Behavior

I would expect the error message to tell me `nested` is missing, similar to the message i would have gotten if the type were `schema.TypeString`:

```
Error: Missing required argument

  on main.tf line 12, in resource "custom" "test":
  12: resource "custom" "test" {

The argument "nested" is required, but no definition was found.
```

### Actual Behavior

I do get an error, but there is no indication as to what attribute is missing:

```
Error: Required attribute is not set

  on main.tf line 12, in resource "custom" "test":
  12: resource "custom" "test" {
```

AFAICT, the diagnostic attribute path is correctly serialized to proto.Diagnostic, so this may be a case of terraform itself not surfacing the information, but for backward compatibility it would be useful to encode the path information in diagnostic detail field, even if it is potentially redundant.

**Comment by appilon** [comment]
Hello @jta ,

Terraform unfortunately does not have normal "required" support for "block types" such as `TypeList`. The SDK though should be "faking" it by setting `MinItems` to 1 automatically. Could you please run [`terraform providers schema`](https://www.terraform.io/docs/commands/providers/schema.html) in an example configuration using this provider and attributes, and then post the results?

**Comment by bflad** [comment]
Related: #535

@appilon here's the `terraform providers schema -json` output from that issue: https://github.com/hashicorp/terraform-plugin-sdk/issues/535#issuecomment-682750157

**Comment by paddycarver** [comment]
As this should [now be fixed](https://github.com/hashicorp/terraform-plugin-sdk/issues/535#issuecomment-755263375) I'm going to close this issue out.

Feel free to open a new issue if this is still occurring.
