### ISSUE TITLE
helper/schema.ResourceData Inverse HasChanges Receiver Method

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#457]
### SDK version

```
v1.12.0
```

### Use-cases

When working in `Update` functions where there are two API calls required, it is often required to guard each of them via [`(helper/schema.ResourceData).HasChange()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/schema?tab=doc#ResourceData.HasChange) or [`(helper/schema.ResourceData).HasChanges()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/schema?tab=doc#ResourceData.HasChanges), e.g.

```go
func resourceExampleThingUpdate(d *schema.ResourceData, meta interface{}) error {
  if d.HasChange("attr1") {
    // update attr1
  }

  if d.HasChange("attr2") {
    // update attr2
  }
}
```

In the Terraform AWS Provider, there is a typical situation that all update handling except resource tagging happens in one API call, while resource tagging is a separate API call. For resources with a lot of attributes, this leads to harder to maintain logic:

```go
	if d.HasChanges(
		"cloudwatch_alarm",
		"cloudwatch_metric",
		"description",
		"dynamodb",
		"dynamodbv2",
		"elasticsearch",
		"enabled",
		"firehose",
		"iot_analytics",
		"iot_events",
		"kinesis",
		"lambda",
		"republish",
		"s3",
		"sns",
		"sql",
		"sql_version",
		"sqs",
	) {
		input := &iot.ReplaceTopicRuleInput{
			RuleName:         aws.String(d.Get("name").(string)),
			TopicRulePayload: expandIotTopicRulePayload(d),
		}

		_, err := conn.ReplaceTopicRule(input)

		if err != nil {
			return fmt.Errorf("error updating IoT Topic Rule (%s): %w", d.Id(), err)
		}
	}

	if d.HasChange("tags") {
		o, n := d.GetChange("tags")

		if err := keyvaluetags.IotUpdateTags(conn, d.Get("arn").(string), o, n); err != nil {
			return fmt.Errorf("error updating tags: %s", err)
		}
	}
```

### Proposal

Instead of needing to list out every possible attribute in a long list, it would be great if we could succinctly just say "any changes but this/these", e.g. `d.HasChangesOtherThan("tags")`

e.g.

```go
	if d.HasChangesOtherThan("tags") {
		input := &iot.ReplaceTopicRuleInput{
			RuleName:         aws.String(d.Get("name").(string)),
			TopicRulePayload: expandIotTopicRulePayload(d),
		}

		_, err := conn.ReplaceTopicRule(input)

		if err != nil {
			return fmt.Errorf("error updating IoT Topic Rule (%s): %w", d.Id(), err)
		}
	}

	if d.HasChange("tags") {
		o, n := d.GetChange("tags")

		if err := keyvaluetags.IotUpdateTags(conn, d.Get("arn").(string), o, n); err != nil {
			return fmt.Errorf("error updating tags: %s", err)
		}
	}
```

Some potential bikeshed function signatures:

1. `func (d *ResourceData) HasChangesBeyond(keys string...) bool`
1. `func (d *ResourceData) HasChangesExcept(keys string...) bool`
1. `func (d *ResourceData) HasChangesOtherThan(keys string...) bool`
1. `func (d *ResourceData) HasChangesOutside(keys string...) bool`

I think we'd want the variadic version from the get-go.

### References

- https://github.com/terraform-providers/terraform-provider-aws/pull/13293/files

**Comment by ewbankkit** [comment]
**OtherThan** sounds more fluent to me, but **Except** has precedent with the SQL `EXCEPT` statement.

**Comment by bflad** [comment]
Here's another really good example of something we'd like to avoid: https://github.com/terraform-providers/terraform-provider-aws/pull/5225#discussion_r448517893

**Comment by bflad** [comment]
SDK version 2 pull request: https://github.com/hashicorp/terraform-plugin-sdk/pull/558 (using `Except` naming to start)
