### ISSUE TITLE
assume_role_policy should not be always required

### ISSUE THREAD

**Issue by AntonAleksandrov13** [hashicorp/terraform-plugin-sdk#481]
### SDK version

```
Terraform v0.12.26
```

### Use-cases

I need to establish cross-account access between two AWS roles. Putting it in simple words, a role from AWS account A needs to assume role provided in Account B. I am granting role to assume role B using assume_role_policy.
However, as assume_role_policy is required, I have provide the same parameter for role B. Even though, I don't need role B to assume any roles, since it simply provides access to resources inside Account B.

### Attempted Solutions

I have attempted setting up empty statement in assume role policy, which is not allowed. And in the end, I have made backwards compatibility with the role in Account A(now both roles can assume each other).
In the end, I have added assume statement that allows ec2 service to assume the mentioned role in Account B.

### Proposal

I understand limitations of AWS and their API, that does not allow role creation without AssumeRoleStatement. I suggest making assume_role_policy not-required param and send the following json if this param is not provided:
```
{"Version":"2012-10-17","Statement":[{"Effect":"Allow",
        "Principal":{"Service":["ec2.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}
```

### References

The mentioned limitation is AWS API - > https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html
Look inside Request params.

**Comment by paddycarver** [comment]
Hi, this appears to be an issue for the AWS provider, not the plugin SDK, and as such should be opened in [their repository](https://github.com/terraform-providers/terraform-provider-aws/issues). Please let us know by replying to this issue if this isn't an issue with the AWS provider and is instead an issue with the SDK used to develop providers, and we can reopen it to discuss.
