### ISSUE TITLE
Publish GitHub Releases in addition to tags

### ISSUE THREAD

**Issue by fbreckle** [hashicorp/terraform-plugin-sdk#483]
With the github layout updates, there is no apparent way to reach the releases page anymore. Adding '/releases` to the url works.

Per https://github.blog/changelog/2020-06-23-design-updates-to-repositories-and-github-ui/ , releases can be enabled in the sidebar.

**Comment by paddycarver** [comment]
As best I can tell, this isn't a feature or setting we need to enable. It's just that our past releases have been tags, not GitHub Releases, and tags don't show up in the sidebar. For example, here is what I see:

![Screenshot from 2020-06-26 09 50 15](https://user-images.githubusercontent.com/59249/85881483-856f6600-b792-11ea-8aa0-86a924c6b2dd.jpeg)

To resolve this, it looks like we'd need to do some combination of creating releases from old tags and/or creating releases for future tags.

**Comment by bflad** [comment]
With recent updates to the project release process, GitHub Releases are now automatically published with the snippet of the CHANGELOG: https://github.com/hashicorp/terraform-plugin-sdk/releases
