### ISSUE TITLE
Missing SetPartial and Partial Deprecation from v2 upgrade guide

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-sdk#484]
Our upgrade guide makes no mention of the deprecation of `ResourceData.Partial` and `ResourceData.SetPartial` that we talk about in #312 and have subsequently evolved our understanding of. We should document that situation for users upgrading.

**Comment by paddycarver** [comment]
#476 has more info on this, as well.

**Comment by falzm** [comment]
That'd be nice, since it started triggering linting errors all of a sudden... Besides, is there a reason than only the `ResourceData.SetPartial()` method has been deprecated and not `ResourceData.Partial()`? From my understanding of #312, both should be.
