### ISSUE TITLE
mfa_delete enabled is not working via Terraform

### ISSUE THREAD

**Issue by anilsakr** [hashicorp/terraform-plugin-sdk#505]
Anils-MacBook-Air:Dome9 anilreddy$ terraform apply
aws_s3_bucket.example: Refreshing state... [id=mfa-delete-test3]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_s3_bucket.example will be updated in-place
  ~ resource "aws_s3_bucket" "example" {
        acl                         = "private"
        arn                         = "arn:aws:s3:::mfa-delete-test3"
        bucket                      = "mfa-delete-test3"
        bucket_domain_name          = "mfa-delete-test3.s3.amazonaws.com"
        bucket_regional_domain_name = "mfa-delete-test3.s3.us-west-2.amazonaws.com"
        force_destroy               = false
        hosted_zone_id              = "Z3BJ6K6RIION7M"
        id                          = "mfa-delete-test3"
        region                      = "us-west-2"
        request_payer               = "BucketOwner"
        tags                        = {
            "Name" = "mfa-delete-test-3"
        }

      + lifecycle_rule {
          + enabled = true
          + id      = "log"
          + prefix  = "log/"

          + expiration {
              + days = 90
            }
        }
      + lifecycle_rule {
          + enabled = true
          + id      = "tmp"
          + prefix  = "tmp/"

          + expiration {
              + date = "2016-01-12"
            }
        }

      ~ versioning {
            enabled    = true
          ~ mfa_delete = false -> true
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_s3_bucket.example: Modifying... [id=mfa-delete-test3]

Error: Error putting S3 versioning: AccessDenied: Mfa Authentication must be used for this request
        status code: 403, request id: B2056D7BFE7DBBEE, host id: AzB1YjDFdlJ50TynXKW0I4jg/La/xJXwW9hS3Ort/nbLGBHA93a/91TKpFLW2Mh/xQ+V2qVg4ik=

  on s3bucket.tf line 6, in resource "aws_s3_bucket" "example":
   6: resource "aws_s3_bucket" "example" {

**Comment by paddycarver** [comment]
This appears to be an issue with the AWS provider, and should be addressed on [their issue tracker](https://github.com/terraform-providers/terraform-provider-aws/issues) instead. This issue tracker is for the SDK.
