### ISSUE TITLE
Add Description for injected ID attributes

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-sdk#509]

**Comment by bflad** [comment]
Can resources explicitly declare the `id` attribute schema and have it take effect today (I haven't tried 😅 )? e.g.

```go
&schema.Resource{
  Schema: map[string]*schema.Schema{
    "id": {
      Type: schema.TypeString,
      Computed: true,
      Description: "ohai!",
    },
  },
}
```

**Comment by bflad** [comment]
I've confirmed that the above does work in the real world (and shows up in things like terraform-plugin-docs).
