### ISSUE TITLE
helper/logging/transport.go http.RoundTripper implementation allow correlating request and responses

### ISSUE THREAD

**Issue by edulop91** [hashicorp/terraform-plugin-sdk#546]
### SDK version

Master branch

### Use-cases

I was spending some time debugging a performance issue with the TF Okta provider. As part of this exercise, I set the log TF_LOG level to trace. Through [this](https://github.com/hashicorp/terraform-plugin-sdk/blob/46a198e66e23b565ce2a74d7bdddcff64fb55971/helper/logging/transport.go#L17) code, we get nice output for request/response. Unfortunately, as far as I can tell there is no way to correlate a request with a given response in this http.RoundTripper implementation (especially in the `IsDebugOrHigher` branch) .

### Proposal

It would be nice to be able to add enough information to correlate a request/response pair. This could be as simple as adding a UUID that would be printed when `IsDebugOrHigher` for both the request and response output. I'm happy to submit the change if appropriate!

Alternatively, it would be really nice if we can start instrumenting terraform and providers with opentelemetry.

**Comment by paddycarver** [comment]
We've opened #695 to pitch a proposal that I believe would enable this. We're very interested in feedback on that proposal, if people have any.

**Comment by bflad** [comment]
terraform-plugin-sdk version 2.20.0 now includes a [`terraform-plugin-log`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-log) based `HTTP.Transport` that includes a unique identifier for each HTTP transaction in the `tf_http_trans_id` structured logging field.

Additional details about this functionality can be found on the website documentation: https://www.terraform.io/plugin/sdkv2/logging/http-transport
