### ISSUE TITLE
Where are the GO SDK examples for the terraform init/plan/apply?

### ISSUE THREAD

**Issue by khwang0101** [hashicorp/terraform-plugin-sdk#547]
Hi:

Please help us to find where is the sample `Hello World` examples for `terraform init/plan/apply` using the Terraform GO SDK. My Go version is `1.13.3` and terraform is `v0.12.23`:

$ go version
go version go1.13.3 linux/amd64

$ terraform version
Terraform v0.12.23

Thanks in advanced.

Kevin

**Comment by khwang0101** [comment]
I posted the same question in the  @ HashiCorp twitter, but got no response at all. Is a support blog or Slack channel that I could reach out to you?  Thanks.

Kevin

**Comment by paddycarver** [comment]
Hey @khwang0101, this is the issue tracker for the tooling used to create Terraform providers. https://discuss.hashicorp.com may be a more appropriate setting for this question. If you're looking for how to get started with developing a Terraform provider, our Learn track is probably the best resource at the moment. https://learn.hashicorp.com/collections/terraform/providers
