### ISSUE TITLE
Default values for TypeList

### ISSUE THREAD

**Issue by AlexanderEkdahl** [hashicorp/terraform-plugin-sdk#56]
It is currently not possible to populate TypeList values with default values.

```
"default_cached_methods": &schema.Schema{
  Type:     schema.TypeList,
  Elem:     &schema.Schema{Type: schema.TypeString},
  Optional: true,
  Default:  []string{"GET", "HEAD"},
},
```

Useful for attributes which are required by the provider

**Comment by mavogel** [comment]
Related to #142

**Comment by radeksimko** [comment]
Hi folks,
that's right - we do not support defining default values for complex types _yet_. I will close this in favour of #142 is that issue covers both sets and lists.
