### ISSUE TITLE
Give providers option to handle testing errors (e.g., skip tests based on error)

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-plugin-sdk#568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We propose giving providers the option to be called back with errors encountered during acceptance testing.

At least for AWS, knowing which services and features are supported in different regions (e.g., `us-east-1`) and partitions (e.g., ISO, GovCloud, China, commercial) is difficult. New services and features may come online in one subsection of AWS but not others. The features and services may or may not ever be added to all areas of AWS. Having tests fail because a service or feature is unavailable is misleading (and leaves dangling resources) and should instead result in a skipped test.

Currently, the PreCheck field is helpful for many situations. However, often it is not possible to assess that a service or feature is unavailable or functions differently in a partition or region _until we get an error._ There are no cost-free API calls to determine the limitation.

### Design

**Design Objective:** Allow providers the option to handle errors.

**Design:** Add an optional field to `TestCase` so that the provider can be called back when an error occurs. The provider can handle the error by 1) skipping or 2) fataling the test, or 3) consuming the error. If the provider does not consume, skip or fatal the error, the provider can hand the error back to plugin SDK to handle as it normally would.

### Example

Route53 in the AWS GovCloud partitions does not support operations related to PublicDNS. There are no cost-free API calls to determine that GovCloud has this limitation. But, running a Route53 acceptance test in GovCloud results in this error. Using this PR, we can skip the test rather than reporting a failure.

How this enhancement might look from the AWS Provider:

```go
func testAccAWSRoute53RecordPublicDNSErrorCheck(err error, t *testing.T) {
	re := regexp.MustCompile(`Operations related to PublicDNS are not supported in this aws partition`)

	if re.MatchString(err.Error()) {
		t.Skipf("skipping test; this partition %s does not support PublicDNS operations", testAccGetPartition())
	}
}

func TestAccAWSRoute53Record_basic(t *testing.T) {
	var record1 route53.ResourceRecordSet
	resourceName := "aws_route53_record.default"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:      func() { testAccPreCheck(t) },
		ErrorCheck:    func(err error) { testAccAWSRoute53RecordPublicDNSErrorCheck(err, t) },
		IDRefreshName: resourceName,
		Providers:     testAccProviders,
		CheckDestroy:  testAccCheckRoute53RecordDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccRoute53RecordConfig,
				Check: resource.ComposeTestCheckFunc(
					testAccCheckRoute53RecordExists(resourceName, &record1),
				),
			},
		},
	})
}
```

### References

* terraform-providers/terraform-provider-aws#15022

**Comment by paultyng** [comment]
If instead of this `SkipErrorRegex` field, we just added a function callback that let you process the error instead, maybe thats a more generic solution here:

```go
func TestAccAWSRDSClusterInstance_PerformanceInsightsEnabled_AuroraMysql1(t *testing.T) {
	var dbInstance rds.DBInstance
	resourceName := "aws_rds_cluster_instance.test"
	rName := acctest.RandomWithPrefix("tf-acc-test")

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckAWSClusterDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAWSClusterInstanceConfigPerformanceInsightsEnabledAuroraMysql1(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckAWSClusterInstanceExists(resourceName, &dbInstance),
					resource.TestCheckResourceAttr(resourceName, "performance_insights_enabled", "true"),
				),
				ErrorCheck: func(err error) error {
					// if regex matches, do t.Fail instead of just passing the error through or something...
				}
			},
		},
	})
}
```

**Comment by YakDriver** [comment]
@paultyng I like that too. I can adjust the PR.
