### ISSUE TITLE
helper/schema feature: nestable resources

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform-plugin-sdk#57]
I've talked about this feature on several threads now. Time to centralize the conversation!
## Background

**The context**: some resources are so closely related to each other that they are nearly always considered together: Security Group / Rule, DNS Zone / Record, IAM Group / User, etc.

**The legacy implementation**: it was common to model these as "sub-resources" in the schema, e.g. [Security Group Rules Sub-Resource](https://github.com/hashicorp/terraform/blob/cf901c90d118e45ac2083b4a2834e8bf6848136a/builtin/providers/aws/resource_aws_security_group.go#L47-L137)

**The problem**: "sub-resources" are bug-prone, difficult for provider implementors to work with, and require that all details be known at resource definition time.

**Interim solution**: lean on top-level resources for their simplicity in implementation and their flexibility (e.g. [Security Group Rule Top-Level Resource](https://github.com/hashicorp/terraform/blob/cf901c90d118e45ac2083b4a2834e8bf6848136a/builtin/providers/aws/resource_aws_security_group_rule.go))

**Remaining problem**: top-level resources are clunky and verbose to work with in configs
## Proposed Solution

Add a `helper/schema` feature I'm calling "nestable resources", allowing provider authors to configure places to nest top-level resources into the definition of a related resource.

A sketch of what this might look like from the provider implementation side, using Security Group Rules as an example:

``` go
// in SecurityGroup resource definition...
"ingress": &schema.NestedResource{
  ResourceType: "aws_security_group_rule",

  // FixedAttributes are always set on the nested resource
  FixedAttributes: map[string]interface{}{
    "type" = "ingress",
  },

  // MappedAttributes define which fields of the parent resource to
  // map into the nested resource
  //    - keys: parent attribute name
  //    - values: nested resource attribute name
  MappedAttributes: map[string]string{}{
    "id": "security_group_id",
  },
},
// ...
```

This would make the following two configs equivalent:

``` js
resource "aws_security_group" "foo" {
  // ...
  ingress {
    // ...
  }
}
```

``` js
resource "aws_security_group" "foo" {
  // ...
}

resource "aws_security_group_rule" "foo" {
  security_group_id = "${aws_security_group.foo.id}"
  // ...
}
```

**Comment by paultyng** [comment]
Going to merge this to #220 

0.12 supports "named blocks", and once that is supported in the SDK, it should cover some of the use cases described here. Anything more significant, including handling of resources invoking other resources, is probably better left to upstream Terraform. If the usecase for the true nesting of real resources is just about code reusability, we can achieve that in other ways.
