### ISSUE TITLE
Provisioners belonging to providers

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform-plugin-sdk#58]
Currently there is a strict separation between providers and provisioners, which makes sense given the current set of available provisioners.

However I have some use-cases where a provisioner and a provider would be more closely related:
- For AWS opsworks (working on that in hashicorp/terraform#1892), certain lifecycle events are triggered via the API and could be useful to use as provisioners on an opsworks stack.
- With Rundeck (see hashicorp/terraform#2412) one could trigger a rundeck job as a provisioner, allowing rundeck to handle the details of SSHing into the necessary machines and retaining the audit logs of what was done.

While these certainly _could_ be implemented as standalone provisioners that happen to interact with the same APIs as the provider, this is inconvenient both as an implementer (need to re-implement things such as client instantiation, credentials handling) and as a user (need to duplicate all of the provider settings inside the provisioner block, rather than just having them inherit from the provider as we see with resources).

It feels to me like it would be most convenient for providers to be able to provide provisioners as well as resources, and then provider-provided provisioners would get access to the same "meta" value that the resource definitions get access to, which most providers use to stash their API client. Presumably in the dependency graph such a provisioner would depend both on the resource it's provisioning and on the provider it came from.

I'm mainly just opening this ticket to start a discussion about the issue and see if folks have other similar use-cases or alternative approaches.

**Comment by radeksimko** [comment]
Am I right that this is no longer relevant since vendor provisioners were deprecated and built-in provisioners are planned to stay in core?

i.e. I think this issue can now be closed?

**Comment by bflad** [comment]
I agree, @radeksimko, for the same exact reasons. Provisioner support was also purposefully not added to protocol version 6. If for some reason we would intend on re-introducing this type of functionality across the plugin protocol, it is probably best as a new design issue if/when that time comes. 👍

**Comment by apparentlymart** [comment]
Indeed... the main new insight that we've become aware of in the meantime is that a `provisioner` block is functionally equivalent to a resource which either has only a "create" action or only a "destroy" action, depending on the `when` argument, and there are real examples in the public provider registry of resource types doing such actions in that way, instead of as provisioner plugins.

I think the main thing we're missing to complete that story are some official providers that can more-or-less replace `local-exec`, `remote-exec` and `file`, where the first two would essentially be hooks for shell-powered custom actions during create and destroy while the last would (I think) ideally be a declarative declaration of the existence of a file on a remote system, with a similar meaning to `local_file` in the `hashicorp/local` provider.

However, none of that requires any changes in the plugin SDK, since it could all be implemented today with either this SDK or the new framework, either by other teams at HashiCorp or by third-party provider developers. (and indeed, some of those use-cases already have third-party providers available to meet them)
