### ISSUE TITLE
Upgrading from 2.0.1 to 2.0.2 breaks test with ExpectNonEmptyPlan

### ISSUE THREAD

**Issue by abergmeier** [hashicorp/terraform-plugin-sdk#583]
### SDK version

```
2.0.2
```

### Relevant provider source code

```go
func TestAccExasolRole_rename(t *testing.T) {

	dbName := fmt.Sprintf("%s_%s", t.Name(), nameSuffix)

	renamedDbName := fmt.Sprintf("%s_RENAMED", dbName)

	locked := exaClient.Lock()
	defer locked.Unlock()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:  nil,
		Providers: test.DefaultAccProviders,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`%s
resource "exasol_connection" "test" {
	name = "%s"
	to = "foo"
}
`, test.HCLProviderFromConf(&locked.Conn.Conf), dbName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("exasol_connection.test", "name", dbName),
					testExists("exasol_connection.test"),
				),
			},
			{
				ExpectNonEmptyPlan: true,
				Config: fmt.Sprintf(`%s
resource "exasol_connection" "test" {
	name = "%s"
	to = "foo"
}
`, test.HCLProviderFromConf(&locked.Conn.Conf), renamedDbName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("exasol_connection.test", "name", renamedDbName),
					testExists("exasol_connection.test"),
					testExistsNotByName(dbName),
				),
			},
		},
	})
}
```

### Debug Output
Provides no additional log for `TC_LOG=trace`.

### Expected Behavior
The test should still succeed.
`ForceNew` is set to `false` thus I expect a change.

### Actual Behavior
The test now fails with:

```
Step 2/2 error: Expected a non-empty plan, but got an empty plan!
```

### Steps to Reproduce
```bash
TF_ACC=true TF_LOG=trace go test -v
```

**Comment by abergmeier** [comment]
I did have a look at `testStepNewConfig`. At least to my feeble mind it is very unclear how this should work let alone detect non-empty plans (seems like the check is done after _apply_!?). Maybe getting rid of the conditionals and handling all permutations uniformly would make it more straight forward.

**Comment by paddycarver** [comment]
I think #580 should solve this.

**Comment by abergmeier** [comment]
I tried
```
go get github.com/hashicorp/terraform-plugin-sdk/v2@769f2e7f32a5ed550a0cb414e5508aed53600b77
```
but it seems like for some reason it is not getting the version without the error.

**Comment by paddycarver** [comment]
That is very odd. Does `@master` work, now that it's been merged?

We'll be cutting a release shortly, so that's the permanent fix we're heading for. We're just trying to fix one last bug to roll up into that release, and we should be all set.

**Comment by paddycarver** [comment]
I spoke too soon. 2.0.3 is rolling out now, and should address this. Please feel free to reply to this issue if you continue to have this problem with 2.0.3, and we'll reopen it and investigate some more.

**Comment by abergmeier** [comment]
> I spoke too soon. 2.0.3 is rolling out now, and should address this. 

Still broken with 2.0.3.

**Comment by paddycarver** [comment]
Do you have a reproduction of this we could run ourselves while debugging? And have you tried manually applying the plan in question and ensuring there is actually a diff after applying it?

**Comment by abergmeier** [comment]
> And have you tried manually applying the plan in question and ensuring there is actually a diff after applying it?

Output from Terraform is:

```
  # exasol_role.test_role will be updated in-place
  ~ resource "exasol_role" "test_role" {
        id   = "TEST_ROLE"
      ~ name = "test_role" -> "test_role1"
    }
``

**Comment by abergmeier** [comment]
> Do you have a reproduction of this we could run ourselves while debugging?

I can reproduce this quite easily. But you would have to setup a VM and then some.

I personally would not ask for debugging. My philosophy is that debugging is a last straw only when you have exhausted all testing means. Currently it seems to me like there is a lot about the SDK, which is not yet tested. Thus to me the first step is to add a test that validates that when a name change happens a non-empty plan is present.
That said - the current AccTest code would probably need a refactor for this to work.
I might take a stab at that if you are willing to lay out under which conditions you would be willing to accept a refactor into upstream.

**Comment by abergmeier** [comment]
So I looked into the code and there are two possibilities.
Either:
1. The docs for `ExpectNonEmptyPlan` are ambigous/wrong
2. The implementation is missing code path to handle `!PlanOnly`

To fix this issue you can then:
1. Add quite a lot of documentation for which test permutations `ExpectNonEmptyPlan` is allowed to be used.
2. Implementing for `!PlanOnly`. This in turn may very well break current tests since default for `ExpectNonEmptyPlan` is *cough* unlucky.

IMO the best solution to this confusion might be to add a custom `ExpectedPlan` callback, which overrides `ExpectNonEmptyPlan`. This callback could then also be used to check Plans in all up to three stages: apply, first diff test, second diff test.

**Comment by abergmeier** [comment]
Another approach would be a `CheckPlan` which works similar to `Check` but executed before the plan is applied.

**Comment by abergmeier** [comment]
For the cleanup I now propose: https://github.com/hashicorp/terraform-plugin-sdk/pull/597

**Comment by abergmeier** [comment]
Seems to be not of interest.
