### ISSUE TITLE
Reset resource without destroying/recreating

### ISSUE THREAD

**Issue by eirslett** [hashicorp/terraform-plugin-sdk#59]
Many providers have support for "restore from factory-settings"-like functionality, e.g. you can revert a machine state to a droplet image or ISO file, without destroying the resource itself. This could be useful to expose through Terraform (`terraform reset my-server`?) since in immutable infrastructure, you might want to reset a resource, but not lose its otherwise ephemeral properties, like its IP address, or the contents of a data disk which is separate from the boot disk.
(Not all providers support floating IPs and/or disk mounts separate from the resource itself)

**Comment by paultyng** [comment]
In order to accomplish this you would still need something that "changed" in Terraform (ie. a throwaway version or something that caused this to invoke the upstream API), but as mentioned above, its not something that easily fits in to the Terraform model.
