### ISSUE TITLE
Documentation for developing 3rd party providers in Python or NodeJs?

### ISSUE THREAD

**Issue by curiousdev** [hashicorp/terraform-plugin-sdk#600]
Any documentation or specific source code that I can review to implement providers in another language?

**Comment by nazarewk** [comment]
From my experience its infeasibly slow to implement provider in Python (probably same for NodeJS) due to interpreter startup time and Terraform running the provider many times over the course of single plan/apply.

you can see my experiment at https://github.com/nazarewk/python-terraform-plugin

**Comment by curiousdev** [comment]
I'll take a look at that experiment. Something like dotnet-core or rust should be snappy enough.

**Comment by paddycarver** [comment]
We've written up and published some information on [our policy on non-Go providers](https://www.terraform.io/docs/extend/best-practices/other-languages.html), explaining why we don't support them at this time.
