### ISSUE TITLE
Have a way refer to fixture files inside test config

### ISSUE THREAD

**Issue by thiagoarrais** [hashicorp/terraform-plugin-sdk#608]
### SDK version

```json
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk/v2",
  "Version": "v2.0.4"
}
```

### Use-cases

I'd like to refer to fixture files in the Terraform config used for testing. This would allow the use of filesystem functions like `filebase64` during acceptance testing.

I had been doing this with the v1 SDK by using `path.cwd`:

```tf
resource "my_provider_some_resource" "foo" {
  prop = filebase64("${path.cwd}/fixture/my_file")
}
```

But since v2 it no longer points to the test source directory. It points  instead to a temp dir where my fixture files cannot be located:

```
    resource_some_resource_test.go:84: Step 1/2 error: Error running pre-apply refresh: 
        Error: Invalid function argument
        
          on config398631862/terraform_plugin_test.tf line 28, in resource "my_provider_some_resource" "foo":
          28:   prop = filebase64("${path.cwd}/fixture/my_file")
            |----------------
            | path.cwd is "/tmp/plugintest891370063/work265214818"
        
        Invalid value for "path" parameter: no file exists at
        /tmp/plugintest891370063/work265214818/fixture/my_file;
        ...
```

### Attempted Solutions

I've been working around this by injecting `$PWD` into the config string itself:

```go
    configString := fmt.Sprintf(`
locals {
	test_cwd = "%s"
}

resource "my_provider_some_resource" "foo" {
  prop = filebase64("${local.test_cwd}/fixture/my_file")
}
`, os.Getenv("PWD"))
```

### Proposal

First proposal is to copy the source directory to tmp before running the tests, that way `path.cwd` can keep working.

Second proposal is to provide some special `TF_VAR_test_cwd` that can be read into the test config via a `variables` block.

**Comment by bflad** [comment]
Related: https://github.com/hashicorp/terraform-plugin-sdk/issues/235 😄

**Comment by innovate-invent** [comment]
Relative paths work as expected for me. Everything is relative to the provider folder.

Here is my function that loads it:
```
func testAccConfigTemplate(file string, t *testing.T) *template.Template {
	if tmpl, err := template.ParseFiles(file); err == nil {
		return tmpl
	} else {
		t.Fatalf("Failed to parse config template: %v", file)
	}
	return nil
}
```

`"test-fixtures/history.tf"` is a path I pass to it.
