### ISSUE TITLE
Missing required attribute mismatch

### ISSUE THREAD

**Issue by lconnell** [hashicorp/terraform-plugin-sdk#624]
### SDK version
```
v2.0.4
```

### Relevant provider source code
```go
// Provider -
func Provider() *schema.Provider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"api_key": &schema.Schema{
				Type:        schema.TypeString,
				Required:    true,
				Sensitive:   true,
				DefaultFunc: schema.EnvDefaultFunc("CADA_API_KEY", nil),
			},
			"endpoint": &schema.Schema{
				Type:        schema.TypeString,
				Required:    true,
				DefaultFunc: schema.EnvDefaultFunc("CADA_API_ENDPOINT", nil),
			},
		},
		ResourcesMap: map[string]*schema.Resource{
			"cada_host":       resourceHost(),
			"cada_host_group": resourceHostGroup(),
		},
		DataSourcesMap: map[string]*schema.Resource{
			"cada_host":       dataSourceHost(),
			"cada_host_group": dataSourceHostGroup(),
			"cada_user":       dataSourceCadaUser(),
		},
		ConfigureContextFunc: providerConfigure,
	}
}

func providerConfigure(ctx context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
	endpoint := d.Get("endpoint").(string)
	apiKey := d.Get("api_key").(string)

	// Warning or errors can be collected in a slice type
	var diags diag.Diagnostics

	if (endpoint != "") && (apiKey != "") {
		config := cada.ClientConfiguration{
			APIKey:    apiKey,
			Endpoint:  endpoint,
			UserAgent: GetUserAgent(),
		}

		c := cada.NewClient(config)

		return c, diags
	}

	return nil, diags
}
```

### Terraform Configuration Files
```hcl
provider "cada" {
  # endpoint = "https://myendpoint.net/cada"
  api_key = "test"
}
```

### Debug Output
examples (master) $ terraform plan
provider.cada.endpoint
  Enter a value: ggg

Error: Missing required attribute

  on <input-prompt> line 1:
  (source code not available)

The attribute "api_key" is required, but no definition was found.

### Expected Behavior
Error output should indicate that "endpoint" was not found as "api_key" is defined. If I swap these variables and comment out "api_key" then it will error that "endpoint" was not found.

### Actual Behavior
The error output should indicate accurately which attribute is missing

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### References
Couldn't find any

**Comment by innovate-invent** [comment]
I just spend a lot of time pulling my hair out on this one for my own provider. `api_key` is a undocumented reserved key much like `id` in resource schemas. Change `api_key` to anything else (like `apikey`) and it will work.

**Comment by paddycarver** [comment]
I'm going to close this, as it appears there's not actually a problem with detecting whether required attributes are set (and if there were... that's more Terraform core's functionality than SDK functionality). Getting a comprehensive list of reserved field names is a good next move, and #632 is great for tracking that.
