### ISSUE TITLE
Use "go list -m" to get user SDK version in issue template

### ISSUE THREAD

**Issue by invidian** [hashicorp/terraform-plugin-sdk#641]
Currently the following command is suggested to get version of SDK one uses:
```sh
go mod edit -json | jq '.Require[] | select(.Path=="github.com/hashicorp/terraform-plugin-sdk/v2")'
```

However, this requires `jq` binary and may not be accurate, if one use `replace` option in `go.mod`.

I think asking users to run the command below would be better, as it will show which version of SDK is used for building
```sh
go list -m github.com/hashicorp/terraform-plugin-sdk/v2
```

Sample output:
```console
$ go list -m github.com/hashicorp/terraform-plugin-sdk/v2
github.com/hashicorp/terraform-plugin-sdk/v2 v2.2.0
```

See https://golang.org/ref/mod#go-list-m for more details.

**Comment by paddycarver** [comment]
Thanks! I like this a lot better than the `jq` version. I've opened #671 to make these changes.
