### ISSUE TITLE
helper/schema: can't track changes to individual fields in a schema.Set

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform-plugin-sdk#65]
Currently, when we have a logical resource in a `schema.Set` (e.g. an `ebs_block_device` in an `aws_instance`), and there are computed fields, we key the hash off the minimal unique set of fields. Because if this, changes to other fields of that set don't register as a diff. This not only prevents changes that require a new resource from being detected (changing the `volume_size` or `iops` of an `ebs_block_device` won't create a new instance and volume), but it prevents mutable fields like tags from being updated. 

This ultimately prevents us from implementing features like hashicorp/terraform#3531, where changes to a `tags` field would require an update.
- Adding all fields by default to the hash value doesn't work, because computed fields change the hash value, so there is always a diff between the config and the state. 
- Adding only the fields mutable within the config to the hash value also doesn't work, because the new hash value still creates a new set in the diff, which will trigger the ForceNew for all the remaining fields.

**Comment by magodo** [comment]
> Adding only the fields mutable within the config to the hash value also doesn't work, because the new hash value still creates a new set in the diff, which will trigger the ForceNew for all the remaining fields.

Hi @jbardin 

Why does the new hash is different from the current hash given the mutable fields are not modified?

Plus, does this issue still existed in current sdk?

**Comment by paultyng** [comment]
I don't think this is still an issue and not sure what work needs to be done as its pretty old/dated. Are you experiencing a specific issue in sets/hashing?

**Comment by jbardin** [comment]
Nope, this is long out of date, and I had since forgotten it was still open. We now have a defined behavior in `cty.Set`, and should base sdk changes of of that.
