### ISSUE TITLE
Provider API Batch Requests

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform-plugin-sdk#66]
Have ya'll considered adding support for batching API requests? We are using Terraform to instrument 50+ websites and services in a single repository and occasionally hit throttling limits when dealing with DNS resources. I know we could segregate our `.tfstate` file so we don't have to process them on every apply but even so it seems like it should be possible to do something like

```hcl
resource "aws_route53_record" "example-com_A_example-com" {
  zone_id = "${aws_route53_zone.example-com.zone_id}"
  type = "A"
  name = "example.com"
  ttl = "1"
  records = ["${module.example-com.public_ip}"]
  batch {
    name = "example.com"
  }
}

resource "aws_route53_record" "example-com_CNAME_www-example-com" {
  zone_id = "${aws_route53_zone.example-com.zone_id}"
  type = "CNAME"
  name = "www"
  ttl = "1"
  records = ["example.com"]
  batch {
    name = "example.com"
  }
}
```

This would only work on a per-resource-type basis, and, if the provider supported it, batching could be controlled by the added configuration shown above.

Is this idea feasible?

**Comment by paultyng** [comment]
Related to #11

**Comment by paultyng** [comment]
Merging with #7
