### ISSUE TITLE
schema ResourceData Set does not work for nested types like TypeList

### ISSUE THREAD

**Issue by DavidGOrtega** [hashicorp/terraform-plugin-sdk#670]
### SDK version
```
github.com/hashicorp/terraform-plugin-sdk/v2 v2.4.0
```

### Relevant provider source code

```go
d.Set("machine.0.custom_data", customData)
```

### Terraform Configuration Files
```tf
resource "runner" "runner-az" {
    token = "arszDpb3xtNdKaXmQ6vN"
    repo = "https://gitlab.com/DavidGOrtega/3_tensorboard"
    driver = "gitlab"
    labels = "tf"
    machine {
      cloud = "azure"
      region = "us-west"
      instance_type = "m"
    }
} 
```

### Expected Behavior
Data should contain the given customData

### Actual Behavior
Totally ignored

### References
 - #81 
 - #459
 - #618

**Comment by paddycarver** [comment]
@DavidGOrtega have you checked the error return from `d.Set`? Are you sure it's not returning an error?

**Comment by bflad** [comment]
Hi @DavidGOrtega 👋  As mentioned above, catching the returned `error` from the `(*ResourceData).Set()` call, e.g.

```go
if err := d.Set("machine.0.custom_data", customData); err != nil {
  // return fmt.Errorf("unable to set machine custom_data: %w", err) // if using non-context-aware CRUD functions
  return diag.Errorf("unable to set machine custom_data: %w", err)
}
```

Should yield more information about any issues while writing state data. If you have any questions or further information to provide, such as the error output, please create a new issue and we can take a fresh look. 👍
