### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#679]
We probably want some sort of acceptance/integration test flow here, as the behaviour we want to verify involves modifying the filesystem in multiple test steps.

The TestControl interface (https://github.com/hashicorp/terraform-plugin-test/blob/master/guard.go#L79) can be mocked in order to test log output during test runs.

**Comment by bflad** [comment]
I'm not sure of the context of this issue as it was transferred from the old terraform-plugin-test repository, so I'm going to close this now. If there's something we should consider for the acceptance testing framework as it exists now, let's create a new issue. 😄
