### ISSUE TITLE
Do not try to locate terraform if only running unit tests

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-sdk#683]
Currently a TestMain will error terraform is not available, even when not running acceptance tests. This issue may be moot with the reattach driver.

**Comment by bflad** [comment]
I believe this may have been behavior with the older test driver. As far as I know, the Terraform CLI search/install logic will only be invoked by Go testing code that invoke `helper/resource` `ParallelTest()`/`Test()`/`UnitTest()` in the current test framework.
