### ISSUE TITLE
Not enough arguments in call to zipDecompressor.Decompress

### ISSUE THREAD

**Issue by jebeaudet** [hashicorp/terraform-plugin-sdk#685]
Hi
A simple provider project with this dependency : 
```github.com/hashicorp/terraform-plugin-sdk v1.16.0```

will pull transitively on `terraform-plugin-test`  2.1.2 and `go-getter` 1.5.0. In version 1.4.2, [a new parameter was added](https://github.com/hashicorp/go-getter/pull/256) to the `Decompress` method resulting in an error like : 
```
>>> Running tests ...
# github.com/hashicorp/terraform-plugin-test/v2
../../go/pkg/mod/github.com/hashicorp/terraform-plugin-test/v2@v2.1.2/helper.go:148:31: not enough arguments in call to zipDecompressor.Decompress
	have (string, string, bool)
	want (string, string, bool, os.FileMode)
FAIL	some/path [build failed]
```

Am I supposed to fix the `go-getter` version and/or the `terraform-plugin-test` ?

**Comment by paddycarver** [comment]
terraform-plugin-test v2.1.3 should resolve this. Please let us know if it does not.
