### ISSUE TITLE
Improve plan diff output

### ISSUE THREAD

**Issue by favoretti** [hashicorp/terraform-plugin-sdk#704]
### SDK version
```
latest
```

### Use-cases
When a test step contains a plan diff - SDK outputs complete object, forcing us to look for that one (or more) field that has changed. On large objects it's a very cumbersome task taking a lot of time in vain.

### Attempted Solutions
Bought better glasses, didn't help... 

### Proposal
Either:
* reduce plan diff output to just the fields that caused the diff with an ability to opt in for displaying full objects by an environment variable
* add an extra output section containing just the fields that caused the diff

**Comment by jacobbednarz** [comment]
Unsure if it's along the same lines but for a larger string value, the ability to restrict the lines of context would also be handy. For example given the following change:

```
Terraform will perform the following actions:

  # cloudflare_worker_script.my_script will be updated in-place
  ~ resource "cloudflare_worker_script" "my_script" {
      ~ content = <<-EOT
            const html = `<!DOCTYPE html><body>  <h1>Hello World!</h1>  <p>This markup was generated by a Cloudflare Worker.</p></body>`

            async function handleRequest(request) {
              return new Response(html, {
                headers: { "content-type": "text/html;charset=UTF-8", },
              })
            }

          + // example single line change
            addEventListener("fetch", event => {
              return event.respondWith(handleRequest(event.request))
            })
        EOT
        id      = "script_1"
        name    = "script_1"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

It would be handy to be able to restrict the output to 3-5 lines either side of the change itself.

```
```
Terraform will perform the following actions:

  # cloudflare_worker_script.my_script will be updated in-place
  ~ resource "cloudflare_worker_script" "my_script" {
      ~ content = <<-EOT
            ...
              })
            }

          + // example single line change
            addEventListener("fetch", event => {
              return event.respondWith(handleRequest(event.request))
            })
        EOT
        id      = "script_1"
        name    = "script_1"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
```
