### ISSUE TITLE
Test v1-maint so we can release it

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-sdk#712]
We merged some fixes (#702) to v1-maint that passed code review and looked good, but we need to run them through some tests with providers before we can feel confident including them in a tagged release. We should run tests against the v1-maint branch so we can cut a release.

**Comment by kmoe** [comment]
Ran acceptance tests for `terraform-provider-random` and `terraform-provider-http` against tip of `v1-maint` (f0cdc46192c5078a5a8ef81ad38378ddd96ee286) with the following Terraform versions and found no unexpected failures:
 - `0.12.30`
 - `0.13.6`
 - `0.14.5`
 - `0.14.7`
