### ISSUE TITLE
Call to "Provider.Schema" block from "Resource.Schema.Schema.ValidateFunc"

### ISSUE THREAD

**Issue by etiennejournet** [hashicorp/terraform-plugin-sdk#724]
Hello,

I'm working on a provider and I'd like to know if it's possible to call some elements of the provider configuration from inside a validation function (called in the ValidateFunc field of a Resource.Schema Schema object).
I was thinking of calling the Provider.Schema object but not sure it is already instanciated during the call to "resourceMyResource()" and not sure I can pass it as an argument to the ValidateFunc.

Sorry If this seems unclear or naive but I'm sort of a beginning in Go and with your SDK (which is pretty clear though, I was able to onboard it faster than expected, good job guys).

Regards,

**Comment by paddycarver** [comment]
This is not possible, as the validation can happen before the provider is configured. Using the CustomizeDiff hook is the earliest you can validate and guarantee you'll have access to the provider configuration.
