### ISSUE TITLE
Support 0.12 Diagnostics in Providers

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform-plugin-sdk#74]
Errors:

      * aws_db_subnet_group.main: only lowercase alphanumeric characters, hyphens, underscores, periods, and spaces allowed in "name"

Suggestion 1) Specify the module in which the error occurred. If a module has only one of a certain resource, I'd prefer to name it, for example, `aws_subnet.main`, but in current TF I use `aws_subnet.mymodule` to make error messages more useful.

Suggestion 2) For errors like the above, output the specific bad value that was passed for `name`.

**Comment by paultyng** [comment]
Diagnostic support will be in v2.0.0
