### ISSUE TITLE
Default attribute for a schema

### ISSUE THREAD

**Issue by ujjwal-ibm** [hashicorp/terraform-plugin-sdk#768]
### SDK version

```
2
```

### Use-cases

For every attribute of type List/Set, I am suggesting an option of having a default attribute depending on the parent.

### Proposal

```
Schema: map[string]*schema.Schema{
			"servers": {
				Type:     schema.TypeList,
				Computed: true,
				DefaultAttribute: servers.id

- [ ]  // Should be an array of IDs in case maxitems > 1

				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "id of the server",
						},

						"name: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "name of the server",
						},
					},
				},
			},
```

**Comment by bflad** [comment]
Hi @ujjwal-ibm 👋  Thank you for raising this.

Would you be able to elaborate further on this feature request proposal? It is a little unclear to me from the code about the intended use case, expected configuration, or expected behaviors.

**Comment by bflad** [comment]
Closing due to lack of response. If you wish to discuss this further, please reach out or create a new issue with the requested information. 👍
