### ISSUE TITLE
Allow access to provider data in validation functions

### ISSUE THREAD

**Issue by jason-johnson** [hashicorp/terraform-plugin-sdk#774]
### SDK version

```
v2.6.1
```

### Use-cases

I have a `data_source` for which I try to do validation on passed in values.  But which values are valid also depends on the provider settings.

### Attempted Solutions

Unfortunately I can find no way to get the provider data (the struct returned from the ConfigureContextFunc function) to the validation function.  I tried making a value in the provider constructor and pass that value both to `configure` (to set the value) and the `data_source` constructor (to pass to the validation function for reading at validation time) but when running an acceptance test to test it, it seems configure is not getting called until after `validate` so the variable is not filled in.

### Proposal

If there were some way for the validation to reference the provider data it would make my validation correct.

**Comment by bflad** [comment]
Hi @jason-johnson 👋  Thank you for raising this.

The reason that provider data is not passed through to validation functions in providers today is that the `ConfigureProvider` RPC request is not performed during `terraform validate`. I believe the current reason for this behavior is to allow `terraform validate` to work outside the context of having all necessary credentials for the configuration being validated.

There may be possibility of introduce a `terraform validate` flag in Terraform CLI to enable the additional behavior (or another feature), which the maintainers here will reach out to the Terraform CLI maintainers to discuss.

Depending on the implementation complexity required to not introduce backwards incompatibilities, this functionality may only land in the next generation of the framework being actively designed and developed in https://github.com/hashicorp/terraform-plugin-framework. It may very well be possible that separate fields and function types are introduced in this version of the framework to remove this concern, but I did want to ensure this point was noted up front.

**Comment by bflad** [comment]
Circling back through some of the issues, I believe that #101 covers this use case, so I'm going to close this issue as a duplicate to focus any discussions or designs there. That issue also mentions `CustomizeDiff` as a potential workaround in this situation, which is accurate in this situation, although it is not called during the `terraform validate` command at the moment for the reason mentioned above.
