### ISSUE TITLE
Support changing provider configurations during test steps

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-sdk#779]
### SDK version

```
v2.7.0
```

### Use-cases

To be able to test upgrading providers between different versions, it would be helpful if we could specify a different set of providers per test step, not just in the test case.

### Proposal

Adding the `ProviderFactories`, `ProtoV5ProviderFactories`, `ProtoV6ProviderFactories`, and `ExternalProviders` properties from `resource.TestCase` to `resource.TestStep`.

**Comment by bflad** [comment]
The acceptance testing framework (helper/resource) in v2.17.0 now allows provider developers to specify providers at the `TestStep` level rather than just `TestCase`. This means that real world state migration/upgrade testing can now be implemented acceptance tests. e.g.

```go
resource.Test(t, resource.TestCase{
	Steps: []resource.TestStep{
		{
			ExternalProviders: map[string]resource.ExternalProvider{
				"random": {
					VersionConstraint: "...", // last version of old schema version
					Source:            "example-namespace/example",
				},
			},
			Config: "...",
			Check:  /* ... */,
		},
		{
			ProviderFactories: testAccProviders,
			Config:            "...",
			Check:             /* ... */,
		},
	},
})
```
