### ISSUE TITLE
Stop silently converting map Elem from Resource to TypeString

### ISSUE THREAD

**Issue by josephholsten** [hashicorp/terraform-plugin-sdk#78]
Proposed resolution: modify all the schemas which use `Type: TypeMap` with `Elem: Resource`; then tighten this validation in `getValueType()`

Arguably a follow on to hashicorp/terraform#12638

In [`helper/schema/schema.go:getValueType`](https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L1364) we see:

```go
if _, ok := schema.Elem.(*Resource); ok {
	// TODO: We don't actually support this (yet)
	// but silently pass the validation, until we decide
	// how to handle nested structures in maps
	return TypeString, nil
}
```

This has allowed us to write a provider which looks like it's actually validating its elements, but does no such thing.

```
return &schema.Resource{
	Schema: map[string]*schema.Schema{
		"create_vnic_details": {
			Type:     schema.TypeMap,
			Optional: true,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"assign_public_ip": {
						Type:     schema.TypeBool,
						Optional: true,
					},
				},
			},
		},
	},
}
```

I do notice this was originally introduced by @radeksimko in https://github.com/hashicorp/terraform/commit/1df1c21d5b6a45f8f4cbfffa058e17165c1935b9

### Expected Behavior

`getValueType()` should have returned an error like `"create_vnic_details: unexpected map value type: schema.Resource"`

### Actual Behavior

Silently allowed using `create_vnic_details.assign_public_ip` but instead of rendering as `"true"` or `"false"`, renders as `"1"` or `"0"`

### Steps to Reproduce
I can do an actual test of this if desired. 
Create a provider with the above schema, then use to access `create_vnic_details.assign_public_ip`

**Comment by paultyng** [comment]
This is the same as #62 , merging with that one.
