### ISSUE TITLE
diff.HasChanges("", "",...)

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-plugin-sdk#785]
Similar to https://github.com/hashicorp/terraform-plugin-sdk/issues/194 , but specific to `schema.ResourceDiff`

Example Use Case:
https://github.com/hashicorp/terraform-provider-aws/pull/20336/files

**Comment by anGie44** [comment]
Solved with https://github.com/hashicorp/terraform-plugin-sdk/pull/626

**Comment by bflad** [comment]
https://github.com/hashicorp/terraform-plugin-sdk/pull/626 with the `(ResourceDiff).HasChanges()` method was merged and will release in terraform-plugin-sdk/v2 v2.11.0 👍
