### ISSUE TITLE
Determine what protocols are supported

### ISSUE THREAD

**Issue by reneherrero** [hashicorp/terraform-plugin-sdk#786]
### SDK version

```
github.com/hashicorp/terraform-plugin-sdk/v2 v2.7.0
```

### Use-cases

Provide a way to determine what protocols are supported (ex: 5.1) by the provider referencing this library.

This is a mandatory field introduced by the Provider Registry Protocol: https://www.terraform.io/docs/internals/provider-registry-protocol.html#response-properties-1

### Attempted Solutions

* Searched documentation
* Searched in code
* Google 

### Proposal

Not sure what's the best way to expose this info.

Putting the info in the `README.md` would seem like an easy first step.

### References

N/A

**Comment by juancsr** [comment]
I'm having the same issue, can anyone shed a light on this?

**Comment by bflad** [comment]
Hi @reneherrero 👋  Thank you for raising this.

Providers written in v2 of this framework are implemented using a protocol version 5 server (essentially requiring Terraform CLI 0.12+). Uploads to the public Terraform Registry default to this protocol version, unless a [Terraform Registry manifest file](https://www.terraform.io/registry/providers/publishing#terraform-registry-manifest-file) is included with a different protocols value.

Will certainly keep this open to document this better.

**Comment by rene-at-dell** [comment]
Cool, thanks for the info @bflad
