### ISSUE TITLE
Add dev_overrides information to README

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#800]
Using `dev_overrides` in config leads to a better provider development workflow. Show users how to do this in the README.

https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers

**Comment by bflad** [comment]
This will certainly get documented! However, it'd probably be best done once as part of https://github.com/hashicorp/terraform-website/issues/2131, so therefore closing this issue in preference of that one. 👍
