### ISSUE TITLE
DiffSuppressFunc should be used for "Objects have changed outside of Terraform" logic

### ISSUE THREAD

**Issue by NiklasWagner** [hashicorp/terraform-plugin-sdk#801]
### Terraform Version
```
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.55.0
```

### Terraform Configuration Files
```terraform
provider "aws" {
  region  = "eu-west-1"
  profile = "xpay"
}

data "aws_caller_identity" "this" {}

data "aws_iam_policy_document" "allow_ecr_read" {
  statement {
    effect = "Allow"

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.this.account_id}:root",
        # the account ids must be valid, otherwise terraform/aws will time out
        "arn:aws:iam::173546646657:root",
        "arn:aws:iam::733016082947:root",
        "arn:aws:iam::159609169035:root",
      ]
    }

    actions = [
      "ecr:DescribeRepositories",
      "ecr:ListImages",
      "ecr:DescribeImages",
    ]
  }
}

resource "aws_ecr_repository" "this" {
  name = "aaa2-ecr-bug"
}

resource "aws_ecr_repository_policy" "this" {
  repository = aws_ecr_repository.this.name
  policy     = data.aws_iam_policy_document.allow_ecr_read.json
}

```

### Debug Output

https://gist.github.com/NiklasWagner/b48d8ccbc30118d2d0aac1cd89a1f00a

### Expected Behavior

Running `terraform apply` multiple times should not show any "Objects have changed outside of Terraform" warnings.

The `DiffSuppressFunc` should be used before the planing phase(?).

### Actual Behavior

Running `terraform apply` multiple times results in "Objects have changed outside of Terraform" warnings. This is due to the AWS API responding with the policy document in different order each time.

The Terraform AWS provider uses a [DiffSuppressFunc](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#diffsuppressfunc) which [already handles](https://github.com/hashicorp/terraform-provider-aws/blob/ceccbcb0d178716ee8713514026ecbccff46fc3a/aws/resource_aws_ecr_repository_policy.go#L38) the [random order issue correctly by using a hashmap](https://github.com/jen20/awspolicyequivalence/blob/8b377d2e0fe02b0b097741f61b33c029af6afd7f/aws_policy_equivalence.go#L213-L214).

Saidly (it looks like that) the `DiffSuppressFunc` is not used when comparing resources within the "Objects have changed outside of Terraform" logic.

```bash
$ t apply
aws_ecr_repository.this: Refreshing state... [id=aaa2-ecr-bug]
aws_ecr_repository_policy.this: Refreshing state... [id=aaa2-ecr-bug]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_ecr_repository_policy.this has been changed
  ~ resource "aws_ecr_repository_policy" "this" {
        id          = "aaa2-ecr-bug"
      ~ policy      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              + "arn:aws:iam::733016082947:root",
                                "arn:aws:iam::630737231557:root",
                              - "arn:aws:iam::173546646657:root",
                                "arn:aws:iam::159609169035:root",
                              - "arn:aws:iam::733016082947:root",
                              + "arn:aws:iam::173546646657:root",
                            ]
                        }
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (2 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` (should create the resources)
3. `terraform apply` (should show a diff in the Pricipal ARN list, if not run multiple times)

### References

Multiple resources are affected in the AWS provider. All with the same policy document issue in different resources:

- https://github.com/hashicorp/terraform-provider-aws/issues/19444
- https://github.com/hashicorp/terraform-provider-aws/issues/19627
- https://github.com/hashicorp/terraform-provider-aws/issues/20107
- https://github.com/hashicorp/terraform-provider-aws/issues/17024
- https://github.com/hashicorp/terraform-provider-aws/issues/13144
- https://github.com/hashicorp/terraform-provider-aws/issues/20456
- https://github.com/hashicorp/terraform-provider-aws/issues/19365

**Comment by NiklasWagner** [comment]
Hi @apparentlymart

thanks for moving my issue to the correct place. Its understandable that the behaviour of the existing SDK is probably not going to change but its great to see that Hashicorp is already working on a new framework and already have a existing issue basically covering my report :)

Thanks for the quick reply, looking forward to have this design issue fixed at some point.

**Comment by bflad** [comment]
The next version of terraform-plugin-sdk/v2, unreleased at the moment, but slated to be v2.11.0 adds an additional `DiffSuppressOnRefresh` field to `helper/schema.Schema`. When enabled, this checks the `DiffSuppressFunc` during refresh. If the planned value matches the old state value via the `DiffSuppressFunc`, the old value will be preserved (or put another way, the planned value will be ignored). This should help mitigate cases like these where the `DiffSuppressFunc` implementations were likely put in place with the expectation that this would already happen in the SDK, however it previously did not.

We expect `DiffSuppressOnRefresh` to be generally safe to apply in most cases where `DiffSuppressFunc` is already being used, however it is not enabled by default for backwards compatibility.
