### ISSUE TITLE
Make schema.InternalMap as proper part of the SDK

### ISSUE THREAD

**Issue by nfx** [hashicorp/terraform-plugin-sdk#814]
### SDK version
v2.7.0+

### Use-cases
In testing and other places within provider it's embarrassingly common to use `map[string]*schema.Schema`, which has useful type methods - `Data()`, `DeepCopy()`, `Diff()`, `Validate()`. Plus, `schema.InternalMap` type alias is way shorter to write (`schema.Map` would probably be even shorter).

**Comment by bflad** [comment]
Hey @nfx 👋  Thank you for raising this.

As we move closer to [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework) reaching full parity with this SDK (as of right now the main items left being supporting resource state upgrades and `timeouts` blocks), the provider coding part of this project is going to enter more and more into maintenance mode. Increasing the public API surface area of the code could make long-term maintenance more problematic. We would also need to ensure that any design is thought through upfront, which any amount of effort with this codebase is detrimental towards finalizing our efforts with the new framework. To that end, we would strongly prefer to leave the implementation details of `InternalMap` where they are today.

Thanks again for the suggestion though.
