### ISSUE TITLE
Planning considers only the current values with no way for the plugin to tell that the value will change after apply

### ISSUE THREAD

**Issue by OmarElawady** [hashicorp/terraform-plugin-sdk#818]
### SDK version
```
github.com/hashicorp/terraform-plugin-sdk/v2 v2.8.0
```

### Relevant provider source code

```go
package hashicups

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceCoffees() *schema.Resource {
	return &schema.Resource{
		ReadContext:   dataSourceCoffeesRead,
		CreateContext: dataSourceCoffeesCreate,
		UpdateContext: dataSourceCoffeesUpdate,
		DeleteContext: dataSourceCoffeesDelete,
		Schema: map[string]*schema.Schema{
			"name": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
			},
			"number": &schema.Schema{
				Type:     schema.TypeInt,
				Required: true,
			},
			"computed_name": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
			},
			"favorite_number": &schema.Schema{
				Type:     schema.TypeMap,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeInt},
			},
		},
	}
}

func dataSourceCoffeesRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	return diags
}

func dataSourceCoffeesUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	// Warning or errors can be collected in a slice type
	var diags diag.Diagnostics
	name := d.Get("name").(string)
	d.Set("computed_name", name)
	d.Set("favorite_number", map[string]int{name: d.Get("number").(int)})
	return diags
}

func dataSourceCoffeesCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	// Warning or errors can be collected in a slice type
	var diags diag.Diagnostics
	name := d.Get("name").(string)
	d.Set("computed_name", name)
	d.Set("favorite_number", map[string]int{name: d.Get("number").(int)})
	d.SetId("1")
	return diags
}

func dataSourceCoffeesDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	// Warning or errors can be collected in a slice type
	var diags diag.Diagnostics
	d.SetId("")
	return diags
}
```

### Terraform Configuration Files

```hcl

provider "hashicups" {}


resource "hashicups_test" "master" {
  name = "john"
  number = 6
}

resource "hashicups_test" "minion" {
  name = hashicups_test.master.computed_name
  number = hashicups_test.master.favorite_number["john"]
}

output "minio_favorite_number" {
  value = hashicups_test.minion.favorite_number["john"]
}
```

### Expected Behavior
 
A way for the plugin to inform the CLI that a value may change after apply, preventing planning of resources depending on to-be-known variables. And possibly notifying the user after the apply if there are out-of-date resources that need subsequent applies.

### Actual Behavior
1. Changing the master number takes three applies to reflect in the output variable (without a clear message to the user).
2. Changing all johns to another name gives an error "Invalid index" in the minion resource, since it tries to reference the old `favorite_number` dict during planning.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform apply`
3. `terraform apply`

### References
I tried to make minimally reproducible examples of issues we face in developing a new terraform plugin (a very close [issue](https://github.com/threefoldtech/terraform-provider-grid/issues/13))

**Comment by bflad** [comment]
Hi @OmarElawady 👋  Thank you for raising this and sorry if you were not able to eventually find the [Customizing Differences](https://www.terraform.io/plugin/sdkv2/resources/customizing-differences) functionality available in this SDK via the [`Resource` type `CustomizeDiff` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Resource.CustomizeDiff). Implementing this additional logic should allow you to denote the expected _computed_ (provider supplied) value on an attribute, which must be marked as `Computed: true`, during the Terraform planning operation. If you have further questions about how to implement this type of provider functionality, please reach out on the [HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/31), where there are more provider developers able to offer suggestions than the issue tracker here.
