### ISSUE TITLE
Migrate to github.com/hashicorp/hc-install for Acceptance Testing Installation

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#823]
### Description

The upstream dependency https://github.com/hashicorp/terraform-exec has removed the `tfinstall` package. Terraform binary search and Installation as part of the acceptance testing handling in this project will now need to use the new github.com/hashicorp/hc-install to upgrade terraform-exec.

### References

- https://github.com/hashicorp/terraform-exec/pull/235

**Comment by bflad** [comment]
We'll likely want something like this feature request to land so we can keep our logic simpler: https://github.com/hashicorp/hc-install/issues/39

**Comment by radeksimko** [comment]
hc-install `v0.3.0` was just cut which includes `fs.AnyVersion` `ExactBinPath` field. https://github.com/hashicorp/hc-install/releases/tag/v0.3.0 so this should be unblocked.

Let me know if there is anything else preventing you from adopting the library and I'd be happy to look into it. 😉

**Comment by bflad** [comment]
I think v0.3.0 with the `Validate()` fixes were talking about should be good to get us migrated! I will open a pull request and manually test out the acceptance testing framework behaviors once that's released. 👍

**Comment by bflad** [comment]
Wow! I really went down a rabbit hole here because I didn't realize `tfinstall` was automatically running `terraform version` itself, which when using `TF_LOG_PATH` in the acceptance testing framework had that output show up in that log file. Since that output no longer exists by default with `hc-install`, the file was empty and I thought something weird was happening with loggers. 😅

**Comment by radeksimko** [comment]
Personally I would consider debugging output from `terraform version` as part of installation unnecessary in that context, but happy to hear other opinions 😄 

The relevant logic is basically all here https://github.com/hashicorp/hc-install/blob/7e86c538be9d48d3ff55df4553b39b1527d08664/product/terraform.go#L29-L49

**Comment by radeksimko** [comment]
@bflad Sorry for the late note, but in case you want to do any debugging and get some output you can pass a logger via `SetLogger`:
https://pkg.go.dev/github.com/hashicorp/hc-install#Installer.SetLogger

We don't send any `terraform version` stdout/stderr there, but it should otherwise be generally verbose enough to be able to debug problems in all other areas. I also opened https://github.com/hashicorp/hc-install/issues/46 to track this problem.
