### ISSUE TITLE
TestStep SkipFunc should not error but print to stdout

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-plugin-sdk#824]
It seems that [SkipFunc](https://github.com/hashicorp/terraform-plugin-sdk/blob/008381a3961560cdea904b9663725fa4243fabb4/helper/resource/testing.go#L457) would be more helpful in test steps if it printed a message to stdout instead of erroring the test. that is how `t.Skip()` works

```
type TestStep struct {
    ...

	// SkipFunc is called before applying config, but after PreConfig
	// This is useful for defining test steps with platform-dependent checks
	SkipFunc func() (bool, error)
```

work arounds are easy enough for now:
```
SkipFunc: func() (bool, error) {
	if myVar != "" {
		return false, nil
	}
	fmt.Println("Environment variable MYVAR must be set.")
	return true, nil
},
```

**Comment by bflad** [comment]
Hi @drewmullen! 👋  The `SkipFunc` handling has been around for quite some time ([origination back in combined Terraform repository](https://github.com/hashicorp/terraform/pull/15957)). The `error` return is explicitly for returning a logical error in the skip function itself, not for denoting whether the test step should be skipped. I believe that behavior is correct.

The `testing` package does however provide the [`T.Logf()` functionality](https://pkg.go.dev/testing#T.Logf), which could be used in the acceptance testing framework's logic in addition to outputting a warning log (which itself requires enabling Terraform's logging):

https://github.com/hashicorp/terraform-plugin-sdk/blob/9cecd719095910f47ea6810329a18947dc6e353b/helper/resource/testing_new.go#L111-L114

So I think if you or anyone is interested in remediating this issue:

- Update the `TestStep.SkipFunc` Go documentation to explain the bool and error returns
- Add `t.Logf()` where the warning log is also emitted

Please reach out with any questions. 👍
