### ISSUE TITLE
[ResourceData] GetChange -> GetStringChange, GetSetChange, GetMapChange, GetBoolChange, ... - add typed change detection

### ISSUE THREAD

**Issue by nfx** [hashicorp/terraform-plugin-sdk#831]
### Use-cases
Whenever we have to check for changes, we always have to cast old and new to appropriate types, which would always be the same by definition:
https://github.com/databrickslabs/terraform-provider-databricks/blob/94cd29cac948fb0d055ccb4a61e5b6f5bdc577be/workspace/resource_workspace_conf.go#L50-L52

### Attempted Solutions
Keep casting

### Proposal
Introduce strongly typed change getters - GetStringChange, GetSetChange, GetMapChange, GetBoolChange, ...

**Comment by bookshelfdave** [comment]
Hello @nfx  - Thanks for submitting an SDK issue, we've taken a look at your proposal. This is something that we believe is addressed in the design of the [plugin framework](https://www.terraform.io/docs/plugin/framework/), and won't be addressing in SDKv2. While the proposed solution is easy to implement for primitives (TypeBool, TypeInt, TypeString etc), it's non-trivial to implement for aggregate types (TypeMap, TypeSet, TypeList) and would exponentially increase the surface area of the SDK.

If you'd like this functionality in your own provider, something like this would work:
```go
func getStringChange(d *schema.ResourceData, key string) (string, string, error) {
  oldRaw, newRaw := d.GetChange(key)
  oldStr, oldOk := oldRaw.(string)
  newStr, newOk := newRaw.(string)

  if !oldOk {
    return "", "", fmt.Errorf("old value is not a string: %T", oldRaw)
  }

  if !newOk {
    return "", "", fmt.Errorf("new value is not a string: %T", newRaw)
  }

  return oldStr, newStr, nil
}
```


If for some reason you're unable to use the framework, please reach out to us via the [Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/310) so we can better understand your plugin development needs. If any other SDK issues pop up, feel free to submit additional issues. 


Thanks -
Dave

**Comment by nfx** [comment]
@bookshelfdave i had only primitive types in mind, though why should it be challenging for `*schema.Set` - it's simple type cast from `interface{}`?
