### ISSUE TITLE
generating (3rd party) provider documentation from sources?

### ISSUE THREAD

**Issue by gliptak** [hashicorp/terraform-plugin-sdk#87]
I might have missed this in the documentation, but is there a way to generate (3rd party) provider documentation from sources similar to the ones at:

https://www.terraform.io/docs/providers/index.html

Thanks

https://github.com/hashicorp/terraform/issues/12941

**Comment by gordonbondon** [comment]
I've noticed that baiducloud provider has a package to generate their documentation from schema - https://github.com/terraform-providers/terraform-provider-baiducloud/tree/master/gendocs.

I have not tried it myself though.

**Comment by gliptak** [comment]
@gordonbondon currently https://github.com/terraform-providers/terraform-provider-baiducloud/blob/master/gendocs/main.go is hardcoded to ```baiducloud``` and it might be generalized.

Which ```terraform``` repo tooling like this might land into?

**Comment by paultyng** [comment]
On a related note, things are evolving in this space, for one, the registry is launching and [will be serving versioned docs there](https://registry.terraform.io/providers/hashicorp/aws/2.44.0/docs). Additionally, we are looking to expand data available in `terraform providers schema` to include more information useful in documentation (ie. descriptions in plaintext or markdown for resources in addition to attributes, deprecation flags, etc).

**Comment by davewongillies** [comment]
Other prior art for inspiration:

* https://github.com/patrickdappollonio/terraform-gendocs
* https://github.com/bflad/tfproviderdocs (only checks though)

**Comment by paultyng** [comment]
Going to merge this in to #177 , I agree docs generation is an important feature, the direction we are taking though, especially w/rt the registry, is not one inside the provider binary itself (or importing its code), but one that can query the schema from a binary.
