### ISSUE TITLE
How to debug terraform

### ISSUE THREAD

**Issue by d-apurva** [hashicorp/terraform-plugin-sdk#88]
Is there any better way to debug terraform provider other than using TF_LOG=DEBUG.
Please list the steps required to reproduce the log which i did.

set TF_LOG=DEBUG
set TF_TF_LOG_PATH=/tmp/log
terraform apply
observe TRACE level logs in the file /tmp/log

Please let me know if there is better way than this.

**Comment by asubmani** [comment]
> @tamsky
> 
> > Is there any way around this?
> 
> Not at this time that I'm aware of unfortunately, the `TF_LOG` environment variable is passed between Terraform Core and the Providers at the moment.
> 
> To give an update on the original "how to debug a Terraform Provider" question: I'm aware of some folks using VSCode's debugger to do this - by placing a breakpoint in the Resource's Create/Read method - and then debugging an Acceptance Test, which will end up calling into the Create/Read methods of the Resource. I've not tried this personally - but since other folks have mentioned this approach works for them I felt it's worth noting.

Hi @tombuildsstuff Would you know any repositories or documentation on how to use vscode to debug terraform?

**Comment by PSanetra** [comment]
I have submitted a PR, which would make it easier to filter for log lines of certain terraform providers: https://github.com/hashicorp/terraform/pull/25086

**Comment by paddycarver** [comment]
:wave: hey y'all, so I took a look into some of the concerns behind this.

First, good news: improved support for debugging providers using tools like delve is planned for the v2 release of the SDK, which we're working on pushing out the door now. You'll need Terraform 0.12.26 or higher to take advantage of it, and your provider will need to be using v2 of the SDK, but ti should allow debugging with delve in tests and with production binaries. We will publish documentation on how to do this when it lands.

Second, bad news: this doesn't fix the logging situation. As a println-based debugger myself, I recognise the current logging situation isn't ideal. I've had success in my own provider development with logging to a file, using unique strings in log messages, and searching for those strings, but that's obviously a... rough experience that we could improve on. Unfortunately, Terraform's logging situation could stand some reworking, and that work isn't planned in the immediate future. I had a fruitful conversation about a design direction for logging _just_ a provider's output to a specific file, however, and that may be an incremental improvement we can deliver before Terraform's logging situation gets updated. Given that we're busy with getting v2 of the SDK out the door, however, and that the core team is busy getting 0.13 out the door, this incremental improvement is likely going to need to wait until the dust clears on those releases before it can be undertaken. And even then, it would require coordination between the core team and the SDK team, and we both have lengthy backlogs, so I can't promise a timeline, just that someone has looked at it and found a potential path forward.

**Comment by PSanetra** [comment]
@paddycarver did you have a look at the PR https://github.com/hashicorp/terraform/pull/25086? I think it would greatly improve the logging situation without any changes in the terraform-plugin-sdk and with minimal changes in terraform-core.

**Comment by paddycarver** [comment]
Hey @PSanetra! I took a look at the PR in question, and I think that's a question for the Core team to answer. Right now, the logging infrastructure in Terraform is just fiddly, and they want to overhaul it entirely, because it can be hard to reason about after years of accreting layers of patches. So even though your change is small in terms of code, it still poses risk in terms of unknown interactions. How big a risk and how willing they are to take it is a question that I can't answer for them, unfortunately. I imagine after 0.13 gets wrapped up and delivered, you'll get some more engagement there.

**Comment by ScottSuarez** [comment]
> First, good news: improved support for debugging providers using tools like delve is planned for the v2 release of the SDK, which we're working on pushing out the door now. You'll need Terraform 0.12.26 or higher to take advantage of it, and your provider will need to be using v2 of the SDK, but ti should allow debugging with delve in tests and with production binaries. We will publish documentation on how to do this when it lands.

Hey @paddycarver, was wondering if there was any update on possibly getting some documentation for working with Delve and Terraform.

**Comment by cemckenzie** [comment]
To anyone reading this thread, please use TF_LOG=TRACE and not DEBUG, which has internal information.  Also to avoid issues of multithreaded log messages, you can set -parallelism=1 on the command line and TFE_PARALLELISM=1 in cloud/enterprise to single thread the run.

**Comment by paddycarver** [comment]
I've opened hashicorp/terraform-website#1584 to add some docs on the state of debugging as of 0.15.0. I'll make sure these documents stay updated as we continue to build out support for more advanced and powerful debugging capabilities.

**Comment by paddycarver** [comment]
Our docs are now live on the website: https://www.terraform.io/docs/extend/debugging.html

There's also #695 available now for comment. It's a proposal for the solution I think will close out this issue. While making Terraform providers more debuggable is something we'll always be interested in and working towards, I think that represents the end of a focused project on the subject. We're very interested in hearing your thoughts and feedback. :)

**Comment by satyamuralidhar** [comment]
> Is there any better way to debug terraform provider other than using TF_LOG=DEBUG.
> Please list the steps required to reproduce the log which i did.
> 
> set TF_LOG=DEBUG
> set TF_TF_LOG_PATH=/tmp/log
> terraform apply
> observe TRACE level logs in the file /tmp/log
> 
> Please let me know if there is better way than this.

is that we use logs set path log.sh file and call it from main.tf using provisioners. is this the right approach or any different kind of approach for  logs

**Comment by Feliksas** [comment]
I don't know if it is really worth a separate issue, since v0.12.x branch is long deprecated, and probably only weirdos like me still tinker with it :) But basically, if you follow the manual and set up the TF_REATTACH_PROVIDERS environment variable, Terraform seems to ignore it and still looks for the provider binary in ~/.terraform.d/

**Comment by bflad** [comment]
Hi folks 👋 

There is information about how to setup recent versions of the SDK with additional logging and debuggers such as `delve` available at https://www.terraform.io/plugin/sdkv2/debugging. If you have a question about this functionality, please start a new topic in the [HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/31). If you have specific bug report or feature request, please open a new issue and we can take a fresh look. Thanks!

**Comment by hablutzel1** [comment]
To debug old Terraform providers (pre Terraform Plugin SDK versions 2.0.0 if I'm not wrong), you can use the technique described in https://groups.google.com/g/delve-dev/c/RTtmwkJe5Jw/m/sD1RylCWGwAJ.
