### ISSUE TITLE
Changing default value to nil for TypeInt in Optional parameter [ Custom Providers Development ]

### ISSUE THREAD

**Issue by jeyanthimuthuram** [hashicorp/terraform-plugin-sdk#90]
Hi,

### Questions 
* Is there any way to set default value of `TypeInt` to `nil` in optional parameters in Schema? 

* Is there any way to find the value is provided by user or it is auto-set ?

### Terraform Version
Terraform v0.10.8

### Use Case
**I am building custom terraform provider ,there I need to call api's through the configuration** 

* I have some default values , that is optional I and even if I am passing nothing in tf configuration it is making them zero.
*  And I can't able to filter while making json request ( because that field may or may not hold zero , and I don't know any way to differentiate between user input and auto-set value)

Please suggest a way I can make it work ?

**Comment by Sh4d1** [comment]
Any news regarding this issue?

**Comment by jakubpech** [comment]
We tried to use V2 SDK from branch "version2" today and run `d.Set(key, nil)`. Unfortunately, the value of the key was still the zero value (false, 0, ""). Will proper handling of nil be a part of initial V2 SDK release or is it something more complex, which will be added later?

**Comment by paultyng** [comment]
The best tracking issue will be #261. The v2 branch paves the way for us to start exposing this new functionality, but we will probably do it via new code paths to not break existing code.
