### ISSUE TITLE
`CustomizeDiff` "invalid key" error after v2.11.0 upgrade

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-sdk#908]
### SDK version

```console
% go list -m github.com/hashicorp/terraform-plugin-sdk/...
github.com/hashicorp/terraform-plugin-sdk/v2 v2.11.0
```

### Relevant provider source code

https://github.com/hashicorp/terraform-provider-aws/blob/912b97cae977943ab75ddca24d68ad8ffe9ff91a/internal/service/autoscaling/group.go#L605-L612

```go
 CustomizeDiff: customdiff.Sequence( 
 	customdiff.ComputedIf("launch_template.0.id", func(_ context.Context, diff *schema.ResourceDiff, meta interface{}) bool { 
 		return diff.HasChange("launch_template.0.name") 
 	}), 
 	customdiff.ComputedIf("launch_template.0.name", func(_ context.Context, diff *schema.ResourceDiff, meta interface{}) bool { 
 		return diff.HasChange("launch_template.0.id") 
 	}), 
 ),
```

### References

Relates https://github.com/hashicorp/terraform-provider-aws/pull/23698.

After upgrade to **v2.11.0** the AWS Provider is now getting an error

```
Error: unable to set "launch_template.0.name" to unknown: SetNewComputed: invalid key: launch_template.0.name
```

when the code above runs. This is successful on **v2.10.1**.

**Comment by bflad** [comment]
Correction, this will land in 2.12.0 since there's already been an enhancement. I'll just cut that release right now though.
