### ISSUE TITLE
Allow schema keys to work in sets/ lists with MaxItems > 1

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-plugin-sdk#928]
_Note: please let me know if this FR should be in the framework repo instead and ill gladly move it: https://github.com/hashicorp/terraform-plugin-framework_

### Use-cases
The framework providers helper keys:
```go
ConflictsWith []string
ExactlyOneOf  []string
AtLeastOneOf  []string
RequiredWith  []string
```

These helper keys are great but when an argument is nested theres currently no way to use them unless the structure is `MaxItems: 1`.

[Example](https://github.com/hashicorp/terraform-provider-aws/blob/13c56a7ff6be0638398611fd478e3e48540f0772/internal/service/apigateway/usage_plan.go#L117) of usage with `MaxItems: 1`:

```go
"rate_limit": {
    Type:         schema.TypeFloat,
    Default:      0,
    Optional:     true,
    AtLeastOneOf: []string{"throttle_settings.0.burst_limit", "throttle_settings.0.rate_limit"},
},
```

### Attempted Solutions

You cannot validate these structures in schema but you can during runtime evaluation

### Proposal

Allow for a character to mean "iterable", ex `#` below

```go
"attachment_policies": {
    Type:     schema.TypeList,
    Required: true,
    MinItems: 1,
    Elem: &schema.Resource{
        Schema: map[string]*schema.Schema{
            ...
            "actions": {
                Type:     schema.TypeList,
                Required: true,
                MaxItems: 1,
                Elem: &schema.Resource{
                    Schema: map[string]*schema.Schema{
                        "association_method": {
                            Type:     schema.TypeString,
                            Required: true,
                            AtLeastOneOf: []string{
                                // the # is a placeholder for iterables
                                "attachment_policies.#.actions.0.segment",
                                "attachment_policies.#.actions.0.tag_value_of_key",
                        },
                        "segment": {
                            Type:     schema.TypeString,
                            Optional: true,
                            ConflictsWith: []string{"attachment_policies.#.actions.0.tag_value_of_key"},
                        },
                        "tag_value_of_key": {
                            Type:     schema.TypeString,
                            Optional: true,
                            ConflictsWith: []string{"attachment_policies.#.actions.0.segment"},
                        },
									},
```

**Comment by bflad** [comment]
Hi @drewmullen 👋  Thank you for raising this.

For full transparency, this is not likely to be implemented in this project before enhancement work stops, however we do have plans to allow for validators to use "relative" or attribute path "matching" support over in terraform-plugin-framework once https://github.com/hashicorp/terraform-plugin-framework/issues/81 is sorted.

That being said, we do have a near duplicate issue here in https://github.com/hashicorp/terraform-plugin-sdk/issues/470, so to consolidate efforts and discussions, I'm going to close this in preference of the existing one. Thanks!

**Comment by drewmullen** [comment]
thank you for pointing that out!
