### ISSUE TITLE
Environment variables wiped out

### ISSUE THREAD

**Issue by pmenglund** [hashicorp/terraform-plugin-sdk#935]
In 1c932cf6a5bc0b11cdc2abddf1fba4846beb3ba5 this change was made:
`internal/plugintest/helper.go`:
```go
	err = tf.SetEnv(map[string]string{
 		EnvCheckpointDisable: "1",
 	})
```

Which now causes the environment to be wiped, as once `tf.SetEnv()`  is called it no longer copies `os.Environ`
```go
	tf := Terraform{
		execPath:   execPath,
		workingDir: workingDir,
		env:        nil, // explicit nil means copy os.Environ
		logger:     log.New(ioutil.Discard, "", 0),
	}

```

Reverting back to v2.12.0 fixes the issue.

### SDK version
```
v2.13.0
```

### Relevant provider source code

n/a

### Terraform Configuration Files

Set the environment variable `TF_VAR_TESTING` and use

```hcl
variable TESTING {
  type = string
}
```

### Debug Output

```
    resource_gcs_integration_test.go:20: Step 1/1 error: Error running pre-apply refresh: variable "TESTING" was required but not supplied
```

### Expected Behavior

The environment variable `TF_VAR_TESTING` should be available

### Actual Behavior
```
    resource_xxx_integration_test.go:20: Step 1/1 error: Error running pre-apply refresh: variable "TESTING" was required but not supplied
```

### Steps to Reproduce

1. create a test which uses an environment variable2. 
2. run the test and the environment it wiped

### References
Introduced in 1c932cf6a5bc0b11cdc2abddf1fba4846beb3ba5

**Comment by bflad** [comment]
Hi @pmenglund 👋  Thank you for raising this and sorry you ran into trouble here. Your assessment here is correct where previously all environment variables were copied to Terraform CLI during acceptance testing. While using `TF_VARS_` environment variables can potentially be problematic in parallel testing scenarios, there is not currently a good alternative short of `fmt.Sprintf()` with the configuration and removing this capability was certainly a regression introduced in 2.13.0 which will be fixed.

**Comment by pmenglund** [comment]
I'm using it to inject GCP credentials into the provider. Is the recommended way to templatize it and use something like this instead
```
variable TESTING {
  type = string
  default = "{{ .Testing }}"
}
```
