### ISSUE TITLE
testStepNewConfig - option to output configuration being used?

### ISSUE THREAD

**Issue by jan-g** [hashicorp/terraform-plugin-sdk#944]
### SDK version
All

### Use-cases
We've a complex series of plugin tests. Some of these test steps require prerequisites - fixtures, or other resources created (or located) prior to execution. For pre-existing fixtures, these tests rely upon injecting appropriate TF vars to identify them.

It's not always clear, when running such a test case, what's missing from the configuration.

The ability to look at the test output and see the TF configuration that's supplied to each step would be hugely beneficial.

An option (or even default behaviour) to dump the TF config for each test step prior to executing the step would make troubleshooting this much more straightforward.

### Proposal

extend testStepNewConfig to emit the step's configuration just after it's been written out.

**Comment by bflad** [comment]
Hi @jan-g 👋  Thank you for raising this. This appears to be similar in nature to https://github.com/hashicorp/terraform-plugin-sdk/issues/700, so to consolidate discussions and efforts, I'm going to close this issue in preference of the existing one. I'd recommend 👍  reacting and subscribing there. Thanks again.
