### ISSUE TITLE
vendored grpc library causes panics if a plugin attempts to compile against any other library that uses grpc, vendored or not

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-plugin-sdk#95]
### Terraform Version
```
0.10.8, but the problem exists in 0.11.x, too
```

### Crash Output
The only relevant part is right here:

```
panic: http: multiple registrations for /debug/requests
```

### Expected Behavior
It shouldn't panic

### Actual Behavior
panic

### Steps to Reproduce
Compile any plugin against both terraform and some other library which also has a dependency on grpc (the etcd/clientv3 client is a good example).  Make sure the code in the plugin actually initializes gRPC, at which point, the code will panic because gRPC attempts to register golang/x/trace against debug/requests in its initializer, which happens before any code can execute to prevent it, and that 2nd registration blows up.  If the various libraries were NOT using vendored versions of the libraries, initialization would only happen once no matter how many times it is imported, since it would recognize that all duplicate import were for the same library and would only init once.  The net result is that it is impossible to write a provider for etcd because it isn't possible to build a provider that uses the etcd client.

### References
google search for 'gRPC "panic: http: multiple registrations"' will find dozens, if not hundreds, of reports of this problem.

**Comment by paultyng** [comment]
In v2 of the plugin, we should finally be fully separate from the core repo so no more transitive dependency issue, hopefully solving this, especially for smaller providers.

**Comment by paddycarver** [comment]
I believe this issue is resolved in v2. Please open a new issue if the problem persists.
