### ISSUE TITLE
Emit failure reasons in debug logs

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-plugin-sdk#956]
### SDK version

```
	github.com/hashicorp/terraform-plugin-sdk/v2 v2.10.1
```

### Use-cases

This will make it easier to view debug logs, as they'll contain additional context on the failure reason without needing to check the test runner's summary view for the direct failure.

This would hopefully include test checks as well as failures at the config stage like unexpected diffs.

### Attempted Solutions

N/A

### Proposal

As part of the test framework, capture and emit test failure reasons in the debug log. See an example like https://gist.github.com/rileykarson/7c9494a513b94118cfddc73a3b79fb8a, where "fail" and "error" don't appear in the debug logs (for a relevant reason) but do in the summary view. This led to a contributor not too familiar with debug logs looking into one of the unrelated failure messages as they weren't aware they should check the summary view in the build log.

**Comment by bflad** [comment]
Hey @rileykarson 👋  Thanks for raising this. I've submitted https://github.com/hashicorp/terraform-plugin-sdk/pull/958, which I believe should cover this ask. Can you please double check that is what you are looking for?

**Comment by rileykarson** [comment]
Looks right to me!

**Comment by bflad** [comment]
Thanks for confirming! I've pulled this in, but considering we just cut a release yesterday, I'm going to see if there are additional things that come in before cutting another.
