### ISSUE TITLE
Provider no longer publishes to registry

### ISSUE THREAD

**Issue by aaronstillwell** [hashicorp/terraform-plugin-sdk#980]
Hi folks. Sorry for raising this issue here, but I'm lost as where else to go.

Back in March, I released a new release for my [provider](https://github.com/aaronstillwell/terraform-provider-dokku), v0.4.1. The terraform registry never picked it up, despite attempting to resync with GitHub from the registry UI.

I emailed terraform-registry@hashicorp.com on March 13th, but never got a response.

I raised this discuss post - https://discuss.hashicorp.com/t/terraform-registry-isnt-registering-latest-release/39837 but still haven't been able to figure out the problem.

I've since re-created the release twice, but still nothing.

Would anyone be able to assist in getting this provider releasing again?

**Comment by bookshelfdave** [comment]
Hi @aaronstillwell - We're tracking this down internally and should have an update shortly.

**Comment by bookshelfdave** [comment]
The registry engineers took a look: there is a branch named `v0.4.1` and the release is also tagged with `v0.4.1`, which causes some ambiguity issues. Try deleting the branch and resync.

**Comment by aaronstillwell** [comment]
🤦 thank you @bookshelfdave! This has indeed resolved the issue.
