### ISSUE TITLE
Sporadically seeing "Error: Invalid provider configuration" in acceptance tests

### ISSUE THREAD

**Issue by matthewcummings** [hashicorp/terraform-plugin-sdk#981]
### SDK version

```
github.com/hashicorp/terraform-plugin-sdk/v2 v2.17.0
```

### Relevant provider source code

```go
https://github.com/cloudtruth/terraform-provider-cloudtruth
```

### Terraform Configuration Files

I have a (growing) number of acceptance tests and I'm seeing them fail occasionally, although I see this behavior most often when 3+ tests are running in parallel via the GitHub Actions matrix strategy.
Here's one such test run:
https://github.com/cloudtruth/terraform-provider-cloudtruth/runs/6844409807?check_suite_focus=true

I don't think this is a bug in my code but I'm not ruling out anything at this point. I _think_ there's a race condition somewhere in here and I have seen tests fail occasionally in isolation (non running concurrently) although I have not yet been able to reproduce such failures locally.

### Expected Behavior

Tests should pass and use the defined-in-code provider config.
### Actual Behavior

One tests per run fails with an "Invalid provider configuration" error.
### Steps to Reproduce

See https://github.com/cloudtruth/terraform-provider-cloudtruth/runs/6844409807?check_suite_focus=true

Any help is appreciated, thank you.

**Comment by matthewcummings** [comment]
@bflad here's a better example: https://github.com/cloudtruth/terraform-provider-cloudtruth/runs/6935714340?check_suite_focus=true

From what I can see, this is not failing in my code. It looks like it might be an issue with the registry being unavailable although it's not currently clear why the test would be querying the registry in this case as it should be running the locally compiled version of the provider. I haven't had a chance to dig into this more, will try to add more context when I can. 
Any guidance is appreciated.

**Comment by matthewcummings** [comment]
OK, thanks. I will investigate further @detro

**Comment by matthewcummings** [comment]
@detro OK. . . I think this may be an issue with my backend (the backend behind my provider) and not core Terraform or the SDK. It wasn't clear at first but I've add more logging recently and the occasional errors that I see now clearly look like 502s from our API. On that note, I am going to close this ticket and will reopen it or create a new one if I can reproduce this behavior and it seems to be an issue on the TF side.
Thank you

**Comment by detro** [comment]
Thank you for investigating this ticket to conclusion.
👋
