### ISSUE TITLE
Can't decode data in provider

### ISSUE THREAD

**Issue by raphink** [hashicorp/terraform-plugin-sdk#99]
In https://github.com/camptocamp/terraform-provider-pass/issues/6, we're hitting a situation where Terraform fails to decode a structured data to store it into a parameter.

This seems to be linked to the way https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go works, but I'm not sure if it's our provider code that is wrong or if it's a bug.

**Comment by paultyng** [comment]
Merging this with #62 for richer map support.
